#if defined fast_sh_array_module_aux_inc
  #endinput
#endif
#define fast_sh_array_module_aux_inc


/* Hero array module
*
* (c) Copyright 2026 ThrashBrat
*
* This file is provided as is (no warranties).
*/

/*

no return value

*/

native sh_init_hero_array();
/*

bool
 
 
*/
native bool:sh_get_user_has_hero(id, the_hero_id)
/*

no return value
 
*/
native sh_set_user_has_hero(id, the_hero_id, bool:the_value_to_set)


