#if defined sh_aux_fx_natives_consts_pt2
  #endinput
#endif
#define sh_aux_fx_natives_consts_pt2



//, sprite1; new gSpriteFire, hero_spawn_hud_msg_sync

/*sprite1 = precache_model("sprites/white.spr")*/
	/*gSpriteSmoke = precache_model("sprites/steam1.spr")
	smoke = precache_model("sprites/steam1.spr")
	gSpriteFire = precache_model("sprites/explode1.spr")
	gSpriteBurning = precache_model("sprites/xfire.spr")
*/
	/*white = precache_model("sprites/shockwave.spr")
	fire = precache_model("sprites/zerogxplode.spr")
	gSpriteLaser = precache_model("sprites/laserbeam.spr")
	//m_trail = precache_model("sprites/smoke.spr")
	blood1 = precache_model("sprites/blood.spr");
	blood2 = precache_model("sprites/bloodspray.spr");*/
	/*g_iFireSprite = precache_model("sprites/flame.spr");
	g_iSmokeSprite[0] = precache_model("sprites/black_smoke3.spr");*/
	/*g_iSmokeSprite[1] = precache_model("sprites/steam1.spr");*/


new mdl_gib_head,mdl_gib_meat,mdl_gib_flesh,spr_blood_spray,spr_blood_drop,mdl_gib_spine,mdl_gib_lung,mdl_gib_legbone

