#define I_WANT_CONSTANTS
#define I_WANT_MISC_FUNCS
#define I_WANT_MATH_FUNCS
#define I_WANT_QUICK_CHECKS
#include "../my_include/superheromod.inc"
#include "../task_allocator_inc/task_allocator_aux_stuff.inc"
#include "ester_inc/ester_global.inc"
#include "ester_inc/ester_flight.inc"
#include "sh_aux_stuff/sh_aux_inc.inc"
#include "sh_aux_stuff/sh_aux_stuff_natives_pt1.inc"
#include "sh_aux_stuff/sh_aux_stuff_natives_pt3.inc"
#include "sh_aux_stuff/sh_aux_stuff_natives_pt4.inc"
#include "shinobu_knife/shinobu_general.inc"



#define PLUGIN "Superhero ester flight funcs"
#define VERSION "1.0.0"
#include "../my_include/my_author_header.inc"
new gHeroID = -1
new gHeroID_shinobu = -1
new g_ester_is_reborn_mode_mask = 0
new g_ester_is_denied_mask = 0
new g_flying_mask = 0
new g_smashed_someone_mask = 0
new g_smashed_breakable_mask = 0
new g_is_glowing_mask = 0


new pcvar_ester_flyspeed,
pcvar_ester_fly_health_spend_pct,
pcvar_ester_calculation_time_period,
pcvar_ester_calculation_chance_numerator,
pcvar_ester_fly_knock_enemies_force,
pcvar_ester_damage_reflect_coeff,
pcvar_ester_reborn_weak_mode_hp,
pcvar_ester_calculation_chance_denominator
new pcvar_ester_fly_knock_enemies;
new pcvar_ester_calculation_times
new pcvar_ester_explosion_damage,
pcvar_ester_explosion_radius
new pcvar_ester_explosion_ignore_user
new pcvar_ester_total_respawn_attempts
new pcvar_ester_anti_pussy_engaged

new Float:g_ester_blow_up_time_left[SH_MAXSLOTS+1]
new g_ester_respawned_attempts[SH_MAXSLOTS+1]
new g_which_team_is_user[SH_MAXSLOTS+1]
new g_saved_coords[SH_MAXSLOTS+1][3]
new g_last_coords[SH_MAXSLOTS+1][3]


new dmg_source_name_short_ester_flight_drain[SAFE_BUFFER_SIZE+1]="ester_flight_drain"
new dmg_source_name_long_ester_flight_drain[SAFE_BUFFER_SIZE+1]="ester_flight_drain"
new ester_flight_drain_wpn_id



new ESTER_REBORN_CALCULATION_LOOP_TASKID,
		ESTER_REBORN_POSITION_CHECK_TASKID,
		ESTER_REBORN_GLOW_TASKID,
		ESTER_REBORN_TEAM_CHECK_TASKID ,
		ESTER_REBORN_EXPLOSION_DELAY_TASKID,
		ESTER_FLIGHT_DRAIN_GLOBAL_TASKID

//----------------------------------------------------------------------------------------------
public plugin_init()
{
	// Plugin Info
	register_plugin(PLUGIN, VERSION, AUTHOR)
	// DO NOT EDIT THIS FILE TO CHANGE CVARS, USE THE SHCONFIG.CFG
	pcvar_ester_flyspeed = register_cvar("ester_flyspeed", "1000.0")
	pcvar_ester_fly_health_spend_pct = register_cvar("ester_fly_health_spend_pct", "25.0")
	pcvar_ester_explosion_damage = register_cvar("ester_explosion_damage", "300.0")
	pcvar_ester_explosion_radius = register_cvar("ester_explosion_radius", "400.0")
	pcvar_ester_explosion_ignore_user = register_cvar("ester_explosion_ignore_user", "1")
	pcvar_ester_fly_knock_enemies = register_cvar("ester_fly_knock_enemies", "1")
	pcvar_ester_fly_knock_enemies_force = register_cvar("ester_fly_knock_enemies_force", "100.0")
	pcvar_ester_calculation_time_period = register_cvar("ester_calculation_time_period", "25.0")
	pcvar_ester_calculation_times = register_cvar("ester_calculation_times", "10")
	pcvar_ester_calculation_chance_numerator = register_cvar("ester_calculation_chance_numerator", "4.0")
	pcvar_ester_calculation_chance_denominator = register_cvar("ester_calculation_chance_denominator", "6.0")
	pcvar_ester_damage_reflect_coeff = register_cvar("ester_damage_reflect_coeff", "0.8")
	pcvar_ester_total_respawn_attempts = register_cvar("ester_total_respawn_attempts", "4")
	pcvar_ester_reborn_weak_mode_hp = register_cvar("ester_reborn_weak_mode_hp", "160.0")
	pcvar_ester_anti_pussy_engaged = register_cvar("ester_anti_pussy_engaged", "0")
	
	
	register_custom_touchable("player","ester_break_shit",breakable_vector,1)
	register_custom_touchable("player","ester_charge_impact",player_vector,1)

	register_forward(FM_CmdStart, "OnCmdStart")
	
	
	RegisterHam(Ham_TakeDamage, "player", "Ester_Knockback", 1,true)
	RegisterHam(Ham_TakeDamage, "player", "Ester_DamageReflect",_,true)

	ESTER_REBORN_CALCULATION_LOOP_TASKID=allocate_typed_task_id(player_task)
	ESTER_REBORN_POSITION_CHECK_TASKID=allocate_typed_task_id(player_task)
	ESTER_REBORN_GLOW_TASKID=allocate_typed_task_id(player_task)
	ESTER_REBORN_TEAM_CHECK_TASKID=allocate_typed_task_id(player_task)
	ESTER_REBORN_EXPLOSION_DELAY_TASKID=allocate_typed_task_id(player_task)
	ESTER_FLIGHT_DRAIN_GLOBAL_TASKID=allocate_typed_task_id(generic_task)


	set_task(FLIGHT_DRAIN_INFLICT_PERIOD,"ester_drain_loop",ESTER_FLIGHT_DRAIN_GLOBAL_TASKID,_,_,"b")
}
public plugin_cfg(){

	gHeroID= ester_get_hero_id()
	gHeroID_shinobu = shinobu_get_hero_id()
	ester_flight_drain_wpn_id=sh_log_custom_damage_source(
								gHeroID,
								dmg_source_name_short_ester_flight_drain,
								dmg_source_name_long_ester_flight_drain,
								0)
}
public ester_drain_loop(task_id){

	if(!sh_is_active()) return

	if(sh_is_freezetime()) return
	static hp;
	for(new id=1;id<sh_maxplayers()+1;id++){


		if(!is_user_alive(id)||!sh_user_has_hero(id,gHeroID)||
				!Get_BitVar(g_ester_is_reborn_mode_mask,id)){
				continue;
		}
		if(get_user_godmode(id)){
			
			continue
		
		}
		hp=get_user_health(id)
		new lost_hp = floatround(float(hp)*(cvar_val(float,pcvar_ester_fly_health_spend_pct)*0.01))
		sh_extra_damage(id, id, lost_hp,
					dmg_source_name_short_ester_flight_drain,
					_,_,_,_,_,
					SH_NEW_DMG_DRAIN,
					ester_flight_drain_wpn_id)



	}
}
deny_next_reborn(id,bool:is_sillycide=true){
	
	if(Get_BitVar(g_ester_is_denied_mask,id)){
		return
	}
	sh_chat_message(id,gHeroID,is_sillycide?ESTER_SUICIDE_FAIL_MSG:ESTER_RESPAWN_FAIL_MSG)

	emit_sound(id, CHAN_AUTO,NULL_SOUND , VOL_NORM, ATTN_NORM, SND_STOP, PITCH_NORM);

	emit_sound(id, CHAN_AUTO,ESTER_RESPAWN_FAIL_SOUND , VOL_NORM, ATTN_NORM, 0, PITCH_NORM);

	g_ester_respawned_attempts[id]=is_sillycide?
				cvar_val(num, pcvar_ester_total_respawn_attempts):
				g_ester_respawned_attempts[id]
	
	Assign_BitVar(g_ester_is_denied_mask,id,true_for_macro)
}
public plugin_natives(){

	register_native("ester_get_reborn_mode","_ester_get_reborn_mode",0);
	register_native("ester_set_reborn_mode","_ester_set_reborn_mode",0);
	register_native("ester_get_respawn_attempts_remaining","_ester_get_respawn_attempts_remaining");
	
}
public Ester_DamageReflect(id, idinflictor, attacker, Float:damage, damagebits)
{
	if ( !sh_is_active() || !is_user_alive(id)||!is_user_alive(attacker)||(id==attacker)) return HAM_IGNORED

	if(cs_get_user_team(id)==cs_get_user_team(attacker)){
	
		return HAM_IGNORED;
	
	}
	if(Get_BitVar(g_flying_mask,id)&&
		sh_user_has_hero(id,gHeroID)&&
		Get_BitVar(g_ester_is_reborn_mode_mask,id)&&
		!Get_BitVar(g_smashed_someone_mask,id)){
		
			sh_extra_damage(attacker, id,floatround(
					cvar_val(float, pcvar_ester_damage_reflect_coeff)*damage),
				new_dmg_type_names[_:SH_NEW_DMG_SHOCK],
				_,_,_,_,_,
				SH_NEW_DMG_SHOCK,
				get_weapon_id_for_generic_dmg_source(SH_NEW_DMG_SHOCK))


			directed_spark(id, attacker)
			damage=1.0+damage- (damage*floatclamp(
				cvar_val(float, pcvar_ester_damage_reflect_coeff)
				,0.0,1.0))
			SetHamParamFloat(4, damage);
	
	}
	return HAM_IGNORED
}
inc_user_ester_respawn_attempts(id){
	
	if(is_user_connected(id)&&sh_is_active()&&sh_user_has_hero(id,gHeroID)){
		
		g_ester_respawned_attempts[id]=g_ester_respawned_attempts[id]<
				cvar_val(num, pcvar_ester_total_respawn_attempts)?
				g_ester_respawned_attempts[id]+1:
				cvar_val(num, pcvar_ester_total_respawn_attempts)
	
	}
	
}
public Ester_Knockback(id)
{
	if ( !sh_is_active() ||!is_user_alive(id)|| 
		!Get_BitVar(g_ester_is_reborn_mode_mask,id)) return HAM_IGNORED
	
	set_pdata_float(id, fPainShock, 1.0, 5)

	return HAM_IGNORED
}

remove_user_flight_fx(id){
	
	if(!is_user_connected(id)||!sh_user_has_hero(id,gHeroID)||!sh_is_active()) return
	
	trail(id,GREEN,0,0)
	emit_sound(id, CHAN_BODY,NULL_SOUND, VOL_NORM, ATTN_NORM, 0, PITCH_NORM);

	emit_sound(id, CHAN_AUTO, ester_blowup_sounds[curr_player_sound[id]],
				VOL_NORM, ATTN_NORM, SND_STOP, PITCH_NORM);
	
	UnSet_BitVar(g_is_glowing_mask, id);
	UnSet_BitVar(g_flying_mask, id);
	
	
}
public _ester_get_reborn_mode(iPlugins,iParams){
	new id=get_param(1)
	
	return Get_BitVar(g_ester_is_reborn_mode_mask,id);

}

public _ester_get_respawn_attempts_remaining(iPlugins,iParams){
	
	new id=get_param(1)
	
	return g_ester_respawned_attempts[id]
	
	

}
public _ester_set_reborn_mode(iPlugins,iParams){
	new id=get_param(1)
	new value=get_param(2)

	if(!value){

		Set_BitVar(g_smashed_someone_mask,id);
		Set_BitVar(g_smashed_breakable_mask,id);
		UnSet_BitVar(g_ester_is_reborn_mode_mask,id)	
	}
	else{

		UnSet_BitVar(g_smashed_someone_mask,id);
		UnSet_BitVar(g_smashed_breakable_mask,id);
		Set_BitVar(g_ester_is_reborn_mode_mask,id)	

	}
}
public OnCmdStart(id, uc_handle, seed)
{	
	if(!sh_is_active()||sh_is_freezetime()){
		return FMRES_IGNORED
	}
	if(!is_user_alive(id)||!sh_user_has_hero(id,gHeroID)||
			!Get_BitVar(g_ester_is_reborn_mode_mask,id)){
			return FMRES_IGNORED;
	}

	if(sh_get_stun(id)){
		UnSet_BitVar(g_flying_mask,id)
		if(Get_BitVar(g_is_glowing_mask,id)){
			UnSet_BitVar(g_is_glowing_mask,id)
			remove_user_flight_fx(id)
			
		}
		return FMRES_IGNORED;
	}
	static buttons,oldbuttons; 
	buttons = get_uc(uc_handle, UC_Buttons)
	
	oldbuttons = entity_get_int(id,EV_INT_oldbuttons)
	if((buttons & IN_DUCK)&&(buttons &IN_JUMP))
	{ 
		if(!(oldbuttons & IN_DUCK)||!(oldbuttons &IN_JUMP)){
			
			if(float(get_user_health(id)) > cvar_val(float,pcvar_ester_reborn_weak_mode_hp)){
				
				emit_sound(id, CHAN_AUTO, FLIGHT_IGNITION, VOL_NORM, ATTN_NORM, 0, PITCH_NORM);
				
			}
			if(float(get_user_health(id)) > cvar_val(float,pcvar_ester_reborn_weak_mode_hp)){
				trail(id,COLOR_STRONG,6,20)
				emit_sound(id, CHAN_BODY, FLIGHT_POWER, VOL_NORM, ATTN_NORM, 0, PITCH_NORM);
			}
			else{
				trail(id,COLOR_WEAK,1,10)
				emit_sound(id, CHAN_BODY, FLIGHT_HUM, VOL_NORM, ATTN_NORM, 0, PITCH_NORM);
				
				
			}
			UnSet_BitVar(g_smashed_someone_mask,id);
			UnSet_BitVar(g_smashed_breakable_mask,id);
			Set_BitVar(g_flying_mask,id)
		}
		if(generate_int(0, FlameAndSoundRate) <3)
		{
			static Float:Velocity[3]

			static Float:curr_hp_ratio,
						Float:flight_speed,
						max_hp_to_use
			
			max_hp_to_use = (sh_user_has_hero(id,gHeroID_shinobu)?shinobu_get_max_hp():sh_get_max_hp(id))

			curr_hp_ratio = float(get_user_health(id))/float(max_hp_to_use)
			
			flight_speed = floatmax(210.0,cvar_val(float,pcvar_ester_flyspeed)*curr_hp_ratio)
			
			velocity_by_aim(id, floatround(flight_speed), Velocity)
		
			entity_set_vector(id, EV_VEC_velocity, Velocity)
		
			if(!Get_BitVar(g_is_glowing_mask,id)){
				Set_BitVar(g_is_glowing_mask,id)
				
			}
		}
		
	}
	else{
		UnSet_BitVar(g_flying_mask,id)
		if(Get_BitVar(g_is_glowing_mask,id)){
			UnSet_BitVar(g_is_glowing_mask,id)
			remove_user_flight_fx(id)
			
		}
		
		
	}
	return FMRES_IGNORED;
}

//----------------------------------------------------------------------------------------------
public plugin_precache()
{
	
	engfunc(EngFunc_PrecacheSound,FLIGHT_HUM );
	engfunc(EngFunc_PrecacheSound,FLIGHT_POWER );
	engfunc(EngFunc_PrecacheSound,FLIGHT_IGNITION );
	engfunc(EngFunc_PrecacheSound,FLIGHT_WEAK );
	engfunc(EngFunc_PrecacheSound,ESTER_RESPAWN_FAIL_SOUND );
	
	for(new i=0;i<ESTER_NUM_BLOWUPSOUNDS;i++){
		engfunc(EngFunc_PrecacheSound,ester_blowup_sounds[i] );	
	}
	
}
//---------------------------------------------------------------------------------------------- 

public sh_client_death(id, killer, headshot, const wpnDescription[]){
	if ( !sh_is_inround()){
		return PLUGIN_CONTINUE
	}
	new has_hero=sh_user_has_hero(id,gHeroID)
	if ( !is_user_connected(id) || !has_hero||!is_user_connected(killer)){
		return PLUGIN_CONTINUE
	}
	if(Get_BitVar(g_ester_is_denied_mask, id)){

		return PLUGIN_CONTINUE
	}
	ester_remove_statuses(id)
	if(killer==id){
		if(has_hero&&
				cvar_val(bool,pcvar_ester_anti_pussy_engaged)){
			
			deny_next_reborn(id)
			return PLUGIN_CONTINUE
			
		}
		else if(has_hero){
			
			sh_chat_message(id,gHeroID,ESTER_SUICIDE_SCOURN_MSG)
			
			
		}
	}
	g_ester_blow_up_time_left[id]=0.0

	ester_set_reborn_mode(id,1)

	g_which_team_is_user[id] = get_user_team(id)

	// Save users origin on death
	get_user_origin(id, g_saved_coords[id])
	g_saved_coords[id][2] += 60

	// Look for self to raise from dead
	if ( !is_user_alive(id) && (g_ester_respawned_attempts[id]<
				cvar_val(num,pcvar_ester_total_respawn_attempts)) ) {
		new parm[2]
		parm[0] = id
		parm[1] = 0
		set_task(floatmax(PRE_RESPAWN_MESSAGE_RELAY,
				cvar_val(float,pcvar_ester_calculation_time_period)
				-PRE_RESPAWN_MESSAGE_RELAY), "ester_reborn_loop_task", id+ESTER_REBORN_CALCULATION_LOOP_TASKID, parm, sizeof(parm))
	}
	else if (!is_user_alive(id)){
		
		deny_next_reborn(id,false)

	}
	return PLUGIN_CONTINUE
}

public ester_reborn_loop_task(parm[2]){
	
	new id= parm[0]
	if(is_user_alive(id)&&sh_user_has_hero(id,gHeroID)){
		
		return
		
	}
	new Float:chance=generate_float(0.0,1.0)
	if(chance<(cvar_val(float,pcvar_ester_calculation_chance_numerator)/
						cvar_val(float,pcvar_ester_calculation_chance_denominator))){
	
		ester_respawn(parm)
		
	}
	else if(parm[1]<cvar_val(num,pcvar_ester_calculation_times)){

		parm[1]++
		set_task(floatmax(PRE_RESPAWN_MESSAGE_RELAY,
			cvar_val(float,pcvar_ester_calculation_time_period)-PRE_RESPAWN_MESSAGE_RELAY), "ester_reborn_loop_task", id+ESTER_REBORN_CALCULATION_LOOP_TASKID, parm, sizeof(parm))
	

	}
	
	
	
}
//----------------------------------------------------------------------------------------------
public ester_respawn(parm[2])
{
	new id = parm[0]
	if ( !is_user_connected(id) || is_user_alive(id) ) return
	if ( !sh_user_has_hero(id,gHeroID)) return
	if ( (g_ester_respawned_attempts[id]>=
				cvar_val(num,pcvar_ester_total_respawn_attempts))||
				!sh_is_inround()) return
	if ( g_which_team_is_user[id]!= get_user_team(id) ) return //prevents respawning spectators

	sh_chat_message(id,gHeroID, "%s",ester_sentences[generate_int(0,ESTER_NUM_SENTENCES-1)])
	new user_name[128]
	get_user_name(id,user_name,127)
	sh_chat_message(0,gHeroID, "%s! They've been reborn!",user_name)
	sh_chat_message(id,gHeroID, "%d attempts to change left",
			cvar_val(num,pcvar_ester_total_respawn_attempts)-g_ester_respawned_attempts[id])

	// Double spawn prevents the no HUD glitch
	
	revival(id)
	revival(id)
	ester_set_reborn_mode(id,1)
	curr_player_sound[id]=generate_int(0,ESTER_NUM_BLOWUPSOUNDS-1)
	emit_sound(id, CHAN_AUTO,ester_blowup_sounds[curr_player_sound[id]] , VOL_NORM, ATTN_NORM, 0, PITCH_NORM);

	inc_user_ester_respawn_attempts(id)
	g_ester_blow_up_time_left[id]=ESTER_REBORN_EXPLOSION_DELAY_TIME

	set_task(1.0, "ester_teamcheck", id+ESTER_REBORN_TEAM_CHECK_TASKID, parm, sizeof(parm))

	// Teleport the player
	set_user_origin(id, g_saved_coords[id])

	positionChangeTimer(id)
}
public godmode_render_update(id){
	
	id-=ESTER_REBORN_GLOW_TASKID
	
	if(is_user_alive(id)&&sh_user_has_hero(id,gHeroID)){
		
		if(!is_user_bot(id)){
			client_print(id,print_center,"Blowing up in %0.2f...",g_ester_blow_up_time_left[id])
		}
		g_ester_blow_up_time_left[id]=g_ester_blow_up_time_left[id]-FLIGHT_GODMODE_THINK_TIME
		sh_set_rendering(id,255,255,255,255, kRenderFxGlowShell,kRenderTransColor)
		remove_glow_user(id,FLIGHT_GODMODE_THINK_TIME)
		if(g_ester_blow_up_time_left[id]>0.0){
			set_task(FLIGHT_GODMODE_THINK_TIME,"godmode_render_update",id+ESTER_REBORN_GLOW_TASKID)
		}
		else{


			new param[1]
			param[0]=0
			BlowUp(param,id+ESTER_REBORN_EXPLOSION_DELAY_TASKID)
		}
	}
	
	
}
//----------------------------------------------------------------------------------------------
public ester_teamcheck(parm[2])
{
	new id = parm[0]

	if ( g_which_team_is_user[id] != get_user_team(id) ) {
		sh_chat_message(id, gHeroID, ESTER_REBORN_TEAM_CHANGE_MSG)
		user_kill(id,1)
		deny_next_reborn(id)
		ester_remove_statuses(id)
	}
}
//----------------------------------------------------------------------------------------------
public sh_round_new(){

	g_ester_is_denied_mask = 0

}
public sh_round_end(){

	arrayset(g_ester_respawned_attempts,0,SH_MAXSLOTS+1)
	arrayset(g_ester_blow_up_time_left,0.0,SH_MAXSLOTS+1)
	g_flying_mask = 0
	// Reset the cooldown on round end, to start fresh for a new round
	for (new id = 1; id < sh_maxplayers()+1; id++) {
		if(is_user_connected(id)&&sh_user_has_hero(id,gHeroID)){
			ester_set_reborn_mode(id,0)
			ester_remove_statuses(id)
		}
	}
}
//----------------------------------------------------------------------------------------------
public positionChangeTimer(id)
{
	if ( !is_user_alive(id) ) return

	get_user_origin(id, g_last_coords[id])
	new Float:velocity[3]
	entity_get_vector(id, EV_VEC_velocity, velocity)

	if ( velocity[0]==0.0 && velocity[1]==0.0 ) {
		// Force a Move (small jump)
		velocity[0] += 20.0
		velocity[2] += 100.0
		entity_set_vector(id, EV_VEC_velocity, velocity)
	}

	set_task(floatmax(PRE_RESPAWN_MESSAGE_RELAY,
			cvar_val(float,pcvar_ester_calculation_time_period)-PRE_RESPAWN_MESSAGE_RELAY) * 0.5, "positionChangeCheck", id+ESTER_REBORN_POSITION_CHECK_TASKID)
}
ester_remove_statuses(id){

	if(is_user_connected(id)&&sh_user_has_hero(id,gHeroID)){
		
		remove_task(id+ESTER_REBORN_EXPLOSION_DELAY_TASKID)
		set_user_godmode(id,0)
		remove_user_flight_fx(id)
	}
	
}
//----------------------------------------------------------------------------------------------
public positionChangeCheck(id)
{
	id -= ESTER_REBORN_POSITION_CHECK_TASKID

	if ( !is_user_alive(id) ) return

	new origin[3]
	get_user_origin(id, origin)

	// Kill this player if Stuck in Wall!
	if ( g_last_coords[id][0] == origin[0] && g_last_coords[id][1] == origin[1] && g_last_coords[id][2] == origin[2] && is_user_alive(id) ) {
		user_kill(id,1)
		sh_chat_message(id, gHeroID, ESTER_WALL_STUCK_MSG)
		deny_next_reborn(id)
		ester_remove_statuses(id)
		ester_set_reborn_mode(id,0)
	}
	else{
		sh_set_godmode(id,ESTER_REBORN_EXPLOSION_DELAY_TIME)
	
		godmode_render_update(id+ESTER_REBORN_GLOW_TASKID)
	
	}
}
//----------------------------------------------------------------------------------------------
public BlowUp(param[1],id)
{
	id-=ESTER_REBORN_EXPLOSION_DELAY_TASKID

	if(!sh_is_freezetime()&&is_user_alive(id)&&sh_user_has_hero(id,gHeroID)&&(param[0]<ESTER_REBORN_EXPLOSION_NUMBER)){
		param[0]++
		explosion(gHeroID,id,
			cvar_val(float,pcvar_ester_explosion_radius),
			cvar_val(float,pcvar_ester_explosion_damage)
			,default_explode_knock_force_magnitude,
			cvar_val(bool,pcvar_ester_explosion_ignore_user))
		set_task(ESTER_REBORN_EXPLOSION_PERIOD,"BlowUp",id+ESTER_REBORN_EXPLOSION_DELAY_TASKID,param,1)
	}
	else{
		ester_remove_statuses(id)
	}
		
	
}
public revival(id)
{
	ExecuteHamB(Ham_Spawn, id) 
	if(is_user_alive(id)){
		setScreenFlash(id, 0, 0, 0, 0, 255 )  //Black flash indicating revival
	}
}
//----------------------------------------------------------------------------------------------
public ester_break_shit(pToucher,pTouched){

	if (pev_valid(pToucher)!=2){
		
		return
	}
	if (!is_user_alive(pToucher)){

		return
	}

	if (pev_valid(pTouched)<1){
		
		return
	}

	if (!sh_user_has_hero(pToucher,gHeroID)||
							Get_BitVar(g_smashed_breakable_mask,pToucher)||
							!Get_BitVar(g_ester_is_reborn_mode_mask,pToucher)||
							!Get_BitVar(g_flying_mask,pToucher)){

		return
	}
	Set_BitVar(g_smashed_breakable_mask, pToucher)
	sh_set_stun(pToucher,1.0,200.0)

	static Float:killer_velocity[3],Float:killer_origin[3],Float:killer_speed
	
	entity_get_vector(pToucher,EV_VEC_origin,killer_origin)
	entity_get_vector(pToucher,EV_VEC_velocity,killer_velocity)

	killer_speed=floatmax(1.0,vector_length(killer_velocity))

	explosion_custom_entity(pToucher,
							150.0,(0.2*killer_speed),
							"func_breakable",
							cvar_val(float, pcvar_ester_fly_knock_enemies_force))

	entity_get_vector(pToucher,EV_VEC_velocity,killer_velocity)
	multiply_3d_vector_by_scalar(killer_velocity,0.5,killer_velocity)
	set_velocity_from_origin(pToucher,killer_origin,killer_speed)


}
public ester_charge_impact(pToucher, pTouched) {


if (pev_valid(pToucher)!=2){
	
	return
}
if (!is_user_alive(pToucher)){

	return
}

if (pev_valid(pTouched)<1){
	
	return
}

if (!sh_user_has_hero(pToucher,gHeroID)||
						Get_BitVar(g_smashed_someone_mask,pToucher)||
						!Get_BitVar(g_ester_is_reborn_mode_mask,pToucher)||
						!Get_BitVar(g_flying_mask,pToucher)||
						!cvar_val(bool, pcvar_ester_fly_knock_enemies)){

	return
}
if(!is_user_alive(pTouched)){
	
	return
}
if(pTouched==pToucher){

	return
}
if(sh_clients_are_same_team(pToucher,pTouched)){

	return
}

sh_set_stun(pToucher,1.0,200.0)

Set_BitVar(g_smashed_someone_mask, pToucher)
static Float:killer_velocity[3],Float:killer_origin[3],Float:killer_speed

entity_get_vector(pToucher,EV_VEC_origin,killer_origin)
entity_get_vector(pToucher,EV_VEC_velocity,killer_velocity)

killer_speed=floatmax(1.0,vector_length(killer_velocity))

explosion(gHeroID,pToucher,150.0,(0.2*killer_speed),
		cvar_val(float, pcvar_ester_fly_knock_enemies_force),1)
entity_get_vector(pToucher,EV_VEC_velocity,killer_velocity)
multiply_3d_vector_by_scalar(killer_velocity,0.5,killer_velocity)
set_velocity_from_origin(pToucher,killer_origin,killer_speed)


}