/* CVARS - copy and paste to shconfig.cfg


//Blood Angel V2
angel_level 0
angel_health 100		//Default 100 (no extra health)
angel_armor 150		//Default 150
angel_gravity 1.0		//Default 1.0 = no extra gravity (0.50 is 50% normal gravity, ect.)
angel_speed -1		//Default -1 = no extra speed, this cvar is for all weapons set to 250 or higher to be faster
angel_m4a1mult 1.3	//Damage multiplyer for his m4a1

*/

#define I_WANT_CONSTANTS
#define I_WANT_MISC_FUNCS
#define I_WANT_QUICK_CHECKS
#include "../my_include/superheromod.inc"
#include "sh_aux_stuff/sh_aux_inc.inc"
#include "darkangel_inc/darkangel_inc.inc"
#include "sh_aux_stuff/sh_aux_stuff_natives_pt3.inc"
#include "sh_aux_stuff/sh_aux_stuff_natives_pt5.inc"
#include "sh_aux_stuff/sh_aux_stuff_natives_pt9.inc"
#include "darkangel_inc/darkangel_inc.inc"
#include "../my_include/my_author_header.inc"

// GLOBAL VARIABLES
new HeroName[] = "Dark angel v2"
new gHeroID
new Float: MEGA_DARK_KNOCKBACK
new Float:m4dmgmult


new dmg_source_name_short_MEGA_DARK_DARKLY_DAKR_DARKNESS_DESPAIR_E[SAFE_BUFFER_SIZE+1]="darkly_dark_d"
new dmg_source_name_log_MEGA_DARK_DARKLY_DAKR_DARKNESS_DESPAIR_E[SAFE_BUFFER_SIZE+1]="darkly_dark_d"
new custom_dmg_id_darkly_dark_d

//----------------------------------------------------------------------------------------------
public plugin_init()
{
	
	my_authored_register_func("SUPERHERO Dark Angel v2", "2.0", "Detox/KitKat",true,AUTHOR )
	
	// DO NOT EDIT THIS FILE TO CHANGE CVARS, USE THE SHCONFIG.CFG
	create_cvar("darkangel_level", "0")
	create_cvar("darkangel_health", "100")
	create_cvar("darkangel_armor", "150")
	create_cvar("darkangel_gravity", "1.0")
	create_cvar("darkangel_speed", "-1")
	create_cvar("darkangel_knockback", "2.0")
	create_cvar("darkangel_m4a1mult", "1.3")
	
	// FIRE THE EVENT TO CREATE THIS SUPERHERO!
	gHeroID=shCreateHero(HeroName, "Dark Angel m4!", "Get dark angels Powerfull m4! 'MUAHAHAHH FEEL THE WRATH OF MY ANGER!!!! THE MIGHT OF MY POWER!!!!' This is him speaking MAHAHAHAHAAAAAAHHHH!!!!!", false, "darkangel_level")
	
	sh_register_admin_only_hero(gHeroID,ADMIN_IMMUNITY,1,
					"HOW DARE YOU CHALLENGE THE DARK LOOOOOORRDDD!!!! STUPID IDIOT IMBECILE JOCK!")


	sh_register_superheromod_weapon_model(gHeroID,CSW_M4A1,"models/shmod/toxic_cat_m4.mdl")
	
	custom_dmg_id_darkly_dark_d=sh_log_custom_damage_source(gHeroID,
				dmg_source_name_short_MEGA_DARK_DARKLY_DAKR_DARKNESS_DESPAIR_E,
				dmg_source_name_log_MEGA_DARK_DARKLY_DAKR_DARKNESS_DESPAIR_E,
				0)
	// EVENTS
	
	register_event("CurWeapon", "weapon_change", "be", "1=1")
	register_event("Damage", "darkangel_damage", "b", "2!0")
	// Let Server know about the hero's variables
	shSetShieldRestrict(HeroName)
	shSetMaxHealth(HeroName, "darkangel_health")
	shSetMaxArmor(HeroName, "darkangel_armor")
	shSetMinGravity(HeroName, "darkangel_gravity")
	shSetMaxSpeed(HeroName, "darkangel_speed", "[22]")
}
//----------------------------------------------------------------------------------------------
public plugin_cfg()
{
	loadCVARS();
}
//----------------------------------------------------------------------------------------------
public loadCVARS()
{

	
	m4dmgmult=get_cvar_float("darkangel_m4a1mult")
	MEGA_DARK_KNOCKBACK=get_cvar_float("darkangel_knockback")
}

public plugin_natives(){

	register_native("darkangel_get_hero_id","_darkangel_get_hero_id");



}
public _darkangel_get_hero_id(iPlugin,iParams){
	
	return gHeroID

}
//----------------------------------------------------------------------------------------------
public sh_hero_init(id, heroID, sh_init_mode:mode){
	if(heroID!=gHeroID) return

	if(sh_get_user_has_hero(id,gHeroID) )
	{
			darkangel_weapons(id)
	}
	else{
			sh_drop_weapon(id, CSW_M4A1)
	}
}
//----------------------------------------------------------------------------------------------
public sh_client_spawn(id)
{
	if(sh_get_user_has_hero(id,gHeroID) ){
		
		darkangel_weapons(id)
	}
}
//----------------------------------------------------------------------------------------------
public darkangel_weapons(id)
{
	if ( !sh_is_active() || !is_user_alive(id) || !sh_get_user_has_hero(id,gHeroID)  )
		return
	
	sh_give_weapon(id, CSW_M4A1)
}


public do_knockback(id,Float:extraDamage){
	new origin[3];
	new Float:forigin[3]
	get_user_origin(id,origin)
	forigin[0] = float(origin[0])
	forigin[1] = float(origin[1])
	forigin[2] = float(origin[2])
	set_velocity_from_origin(id, forigin, MEGA_DARK_KNOCKBACK*(extraDamage+1)) 
	
	
}
//----------------------------------------------------------------------------------------------
public weapon_change(id)
{
	if ( !sh_is_active() || !sh_get_user_has_hero(id,gHeroID) )
		return
	
	new wpnid = read_data(2)
	
	if ( wpnid != CSW_M4A1 )
		return
	
	new clip = read_data(3)
	
	// Never Run Out of Ammo!
	if ( clip == 0 ){
		sh_reload_ammo(id)
	}
}
//----------------------------------------------------------------------------------------------
public darkangel_damage(id)
{
	if ( !sh_is_active() || !is_user_alive(id) )
		return
	
	new weapon, bodypart, attacker = get_user_attacker(id, weapon, bodypart)
	
	if ( (attacker==id)||!is_user_connected(attacker)) return
	
	if ( sh_get_user_has_hero(attacker,gHeroID) && weapon == CSW_M4A1)
	{
		new damage = read_data(2)
		
		// do extra damage
		//also... it bypasses godmode.
		//cuz why not
		if(get_user_godmode(id)){
		
			sh_set_godmode(id,0.0)
			
		}
		new Float:extraDamage = damage * m4dmgmult - damage
		if ( extraDamage > 0.0 ){
			sh_extra_damage(id,attacker,floatround(extraDamage),
								my_hitpoint_enum:bodypart ,
								_,_,_,_,
								SH_NEW_DMG_IVE_STUDIED_THE_BLADE,
								custom_dmg_id_darkly_dark_d)
		}
		do_knockback(id,extraDamage);
	}
}