#define I_WANT_CONSTANTS
#define I_WANT_QUICK_CHECKS
#include "../my_include/superheromod.inc"
#include "sh_aux_stuff/sh_aux_inc.inc"
#include "./superheromod_help_files_includes/superheromod_help_files.inc"
#include "sh_aux_stuff/sh_aux_stuff_natives_pt9.inc"
#include "chikoi_inc/chikoi_inc.inc"
#include "../my_include/my_author_header.inc"

#define CHIKOI_THE_MAID_PHYSICAL_PROPERTY "Smallness"

#define CHIKOI_NUM_DEATH_SOUNDS 1 
stock chikoi_death_sounds[CHIKOI_NUM_DEATH_SOUNDS][]={
	"shmod/chikoi_death_sound.wav"
}

// GLOBAL VARIABLES
new gHeroID
new const gHeroName[] = "Chikoi the Maid"
new custom_dmg_id=0;

//----------------------------------------------------------------------------------------------
public plugin_init()
{
	// Plugin Info
	register_plugin("SUPERHERO Chikoi the Maid", "1.0", AUTHOR)
	
	
	// DO NOT EDIT THIS FILE TO CHANGE CVARS, USE THE SHCONFIG.CFG
	create_cvar("chikoi_level", "8")
	gHeroID=shCreateHero(gHeroName, "Small maid!", "Become headshot only! But it really is headshot only! 1Shot 1Kill!", false, "chikoi_level" )
	static hero_name_arr[STRLEN_FOR_NAMES];
	arrayset(hero_name_arr,0,sizeof hero_name_arr)
	add(hero_name_arr,charsmax(hero_name_arr),gHeroName,charsmax(gHeroName))
	superheromod_help_link_hero(gHeroID, "Chikoi the maid: Help file","chikoi_the_maid_folder/","chikoi_help_file.html",hero_name_arr)

	RegisterHam(Ham_TakeDamage,"player","chikoi_damage",_,true)
	RegisterHam(Ham_TraceAttack,"player","chikoi_physical_body",_,true)
	
	sh_assign_hero_bit(gHeroID,SH_SMALL_HERO,true);
	


	custom_dmg_id=sh_log_custom_damage_source(gHeroID,
			CHIKOI_THE_MAID_PHYSICAL_PROPERTY ,
			CHIKOI_THE_MAID_PHYSICAL_PROPERTY,
			0)
	
}
public plugin_natives(){

	register_native("chikoi_get_hero_id","_chikoi_get_hero_id")

}

public _chikoi_get_hero_id(iPlugin, iParams){

	return gHeroID
}
//----------------------------------------------------------------------------------------------
public ham_Chikoi_fallDamage(this, inflictor, attacker, Float:damage, damagebits)
{
	
	return HAM_IGNORED
}
dmg_message(id, attacker){
	new attacker_name[128];
	get_user_name(attacker,attacker_name,127);
	sh_chat_message(id,gHeroID,"%s has killed Chikoi the Maid, the Small Maid, at your service.",attacker_name)

}

public chikoi_damage(id, idinflictor, attacker, Float:damage, damagebits){

	
if ( !sh_is_active() || !is_user_alive(id) || !sh_get_user_has_hero(id,gHeroID) ) return HAM_IGNORED

if ( damagebits & DMG_FALL ){
	return HAM_SUPERCEDE
}

static inflictor_classname[64];

entity_get_string(idinflictor,EV_SZ_classname,inflictor_classname,63)

if(equal(inflictor_classname,"grenade")){

	return HAM_SUPERCEDE
}
return HAM_IGNORED
}

public chikoi_physical_body(id, attacker, Float:damage, Float:direction[3], tracehandle, damagebits){

	if(damage<=0.0){
		return HAM_IGNORED
	}
	if(!is_user_alive(id)){

		return HAM_IGNORED;

	}
	if(!sh_get_user_has_hero(id,gHeroID) ){

		return HAM_IGNORED;

	}
	if(sh_clients_are_same_team(id,attacker)){

		return HAM_IGNORED
	}
	new hitgroup=get_tr2(tracehandle,TR_iHitgroup);
	switch(hitgroup){
		case HIT_CHEST:{
			set_tr2(tracehandle,TR_iHitgroup,HIT_HEAD);
			SetHamParamTraceResult(5,tracehandle)
			set_user_godmode(id,0)
			sh_extra_damage(id, attacker, 1, MY_HIT_HEAD,SH_DMG_KILL,
						_,_,_,
						SH_NEW_DMG_SQUASHED,custom_dmg_id)

		}
		default:{
			return HAM_SUPERCEDE
		}
	}
	return HAM_IGNORED;
}

public sh_extra_damage_fwd_pre(&victim, &attacker, &damage,  &my_hitpoint_enum:bodypart,&sh_damage_mode:dmgMode, &sh_extra_damage_flags:sh_extra_dmg_flags, const Float:dmgOrigin[3],&dmg_type,&sh_thrash_brat_dmg_type:new_dmg_type,custom_weapon_id){
	if ( !sh_is_active() ||  !is_user_connected(victim)||!is_user_connected(attacker)){
	
		return DMG_FWD_PASS
	}
	if(sh_get_user_has_hero(victim,gHeroID) ){
		if(sh_clients_are_same_team(victim,attacker)){
			return DMG_FWD_PASS
		
		}
		new bool:headshot= (bodypart==MY_HIT_HEAD)
		new bool:is_self_drain_damage= ((victim==attacker)&&(new_dmg_type==SH_NEW_DMG_DRAIN))
		if(headshot&&!is_self_drain_damage){
			
			set_user_godmode(victim,0)
			damage=get_user_health(victim)+1;
			dmgMode=SH_DMG_KILL
			new_dmg_type=SH_NEW_DMG_SQUASHED
			dmg_message(victim,attacker)
			return DMG_FWD_PASS
		}
		else {
			return DMG_FWD_BLOCK
		}
	}
	return DMG_FWD_PASS
}
	
public plugin_precache()
{
	
	for(new i=0;i<CHIKOI_NUM_DEATH_SOUNDS;i++){
		
		engfunc(EngFunc_PrecacheSound, chikoi_death_sounds[i])
		
	}
	
}
public sh_client_death(id,killer,my_hitpoint_enum:hitpoint,custom_wpn_id)
{
	if ( !is_user_connected(id)){
		return
	}
	if(sh_get_user_has_hero(id,gHeroID) ){
		if(custom_wpn_id==custom_dmg_id){
			emit_sound(id, CHAN_VOICE, chikoi_death_sounds[generate_int(0,(sizeof chikoi_death_sounds) -1)], 1.0, 0.0,0,PITCH_NORM)
		}
		if(is_user_connected(killer)&&(killer!=id)){
			dmg_message(id,killer)
		}
	}

}