// GAMBIT! - from the X-men. Can convert any inorganic object's potential energy into kinetic energy on contact.

/* CVARS - copy and paste to shconfig.cfg

//Gambit
gambit_level 0
gambit_grenademult 60.9		//Damage multiplyer from orginal damage amount (def 60.9)
gambit_grenadetimer 30.0		//How many seconds delay for new grenade after nade is thrown (def 30.0)
gambit_cooldown 120.0		//How many seconds until extra grenade damage can be used again (def 120.0)

*/

/*
* v1.3 - vittu - 9/27/05
*      - Fixed up cooldown to only be set once.
*      - Removed some useless checks.
*
* v1.2 - vittu - 6/19/05
*      - Minor code clean up.
*
* v1.1 - vittu - 5/10/05
*      - Fixed giving new grenades using a more reliable event.
*      - Fixed grenade timer to only be set if you have no nades,
*          avoids timer exploiting.
*      - Added cooldown cvar, sets only if someone is hurt by gambit.
*      - Added grenade glow and trail only for gambit nades.
*
*   Hero Created by Vectren
*/
#define I_WANT_QUICK_CHECKS
#define I_WANT_CONSTANTS
#include "../my_include/superheromod.inc"
#include "sh_aux_stuff/sh_aux_inc.inc"
#include "../my_include/my_author_header.inc"


#define AMMOX_HEGRENADE 12

// GLOBAL VARIABLES
new gHeroName[]="Gambit"
new bool:gWillHit[SH_MAXSLOTS+1]
new gGrenTrail
new gHeroID;
new Float:gTotalChance
new const HEGRENADE_MODEL[] = "models/w_hegrenade.mdl"
new pcvar_dmg_mult


new dmg_source_name_short_euromilhoes[SAFE_BUFFER_SIZE+1]="euromilhoes"
new dmg_source_name_log_euromilhoes[SAFE_BUFFER_SIZE+1]="euromilhoes"
new custom_dmg_id_euromilhoes


new user_hegrenade_count[SH_MAXSLOTS+1] = {0, ...},
	prev_user_hegrenade_count[SH_MAXSLOTS+1] = {0, ...}
	
//----------------------------------------------------------------------------------------------
public plugin_init()
{
	// Plugin Info
	my_authored_register_func("SUPERHERO Gambit", "1.3", "Vectren / vittu",true,AUTHOR)

	// DO NOT EDIT THIS FILE TO CHANGE CVARS, USE THE SHCONFIG.CFG
	register_cvar("gambit_level", "0")
	pcvar_dmg_mult = register_cvar("gambit_grenademult", "60.9")
	register_cvar("gambit_grenadetimer", "30.0")
	register_cvar("gambit_chance", "6.0") // 6.0 means 1 in 6 chance. 6.1 means 1 in 6.1
	register_cvar("gambit_powertimer", "6.0") //timer for powernades

	// FIRE THE EVENT TO CREATE THIS SUPERHERO!
	gHeroID=shCreateHero(gHeroName, "Kinetically Charged Nades", "Charge your HE Grenades with Kinetic Energy for Extra Damage, refill HE Grenades. ^nYou get a random chance of causing massive damage", false, "gambit_level")

	custom_dmg_id_euromilhoes = sh_log_custom_damage_source(gHeroID,
					dmg_source_name_short_euromilhoes,
					dmg_source_name_log_euromilhoes,0)


	// EXTRA NADE DAMAGE
	RegisterHam(Ham_TakeDamage,"player","gambit_damage",_,true)

	// FIND THROWN GRENADES
	register_event("AmmoX", "on_AmmoX", "b")
}
//----------------------------------------------------------------------------------------------
public plugin_cfg()
{
	loadCVARS()
}
//----------------------------------------------------------------------------------------------
public loadCVARS()
{
	// These cvars are checked very often
	gTotalChance=get_cvar_float("gambit_chance")
}
//----------------------------------------------------------------------------------------------
public plugin_precache()
{
	gGrenTrail = engfunc(EngFunc_PrecacheModel,"sprites/zbeam5.spr")
}
//----------------------------------------------------------------------------------------------
public grenade_throw(id, gid, wid)
{
	if(sh_get_user_has_hero(id,gHeroID) &&!sh_get_cooldown_flag(id)){
	if(wid == CSW_HEGRENADE){
		gWillHit[id]=(generate_float(0.0,gTotalChance)<1.0)
		entity_set_int(gid,EV_INT_iuser1,gWillHit[id])
		sh_chat_message(id,gHeroID,"GAMBLE IT ALL! You valliant survivor!")
		if ( gWillHit[id])
		{
			
			sh_chat_message(id,gHeroID,"Euromilhoes! A criar excentricos! Todas as semanas!")
		}
	}
	}
} 
//----------------------------------------------------------------------------------------------
public sh_hero_init(id, heroID, sh_init_mode:mode){
	if(heroID!=gHeroID) return

	if(sh_get_user_has_hero(id, gHeroID) && is_user_alive(id) ) {
		gambit_weapons(id)
	}
}
//----------------------------------------------------------------------------------------------
public sh_client_spawn(id)
{
	if ( sh_is_active() && sh_get_user_has_hero(id,gHeroID) && is_user_alive(id) ) {
		sh_unset_cooldown_flag(id)
		set_task(0.1, "gambit_weapons", id)
		
	}
}
//----------------------------------------------------------------------------------------------
public gambit_weapons(id)
{
	if ( sh_is_active() && sh_get_user_has_hero(id,gHeroID) && is_user_alive(id) ) {
		sh_give_weapon(id, CSW_HEGRENADE)
	}
}
public gambit_damage(id, idinflictor, attacker, Float:damage, damagebits)
{
	if ( !sh_is_active() || !is_user_alive(id)||!is_user_connected(attacker)||!sh_get_user_has_hero(attacker,gHeroID)) return HAM_IGNORED
	new gambit_charged= entity_get_int(idinflictor,EV_INT_iuser1)
	if ( gambit_charged ) {
		if ( is_user_alive(id) ) {
			// do extra damage
			new extraDamage = floatround(damage * cvar_val(float, pcvar_dmg_mult) - damage)
			if (extraDamage > 0) {
				sh_extra_damage(id, attacker, extraDamage,
						_,_,_,_,_,
						SH_NEW_DMG_DARK_ARTS,
						custom_dmg_id_euromilhoes)
			}
		}
		new cooldown_params[2]
		cooldown_params[0]=idinflictor
		cooldown_params[1]=attacker
		set_task(0.2,"cooldown",idinflictor,cooldown_params,2)
	}
	return HAM_IGNORED
	
}
//----------------------------------------------------------------------------------------------
public cooldown(parm[])
{
	new grenade = parm[0]

	if(!is_valid_ent(grenade )) return 
	new szClassNamePtr[32]
	entity_get_string(grenade , EV_SZ_classname, szClassNamePtr, 31)
	if ( !equal(szClassNamePtr, "grenade")) return
	
	new id = parm[1]

	entity_set_int(grenade,EV_INT_iuser1,false)

	if ( !is_user_alive(id) || sh_get_cooldown_flag(id)) return

	// Cooldown will only be set if user hurts someone with a gambit nade
	new Float:gambitCooldown = get_cvar_float("gambit_powertimer")
	if (gambitCooldown > 0.0) ultimateTimer(id, gambitCooldown)
}
//----------------------------------------------------------------------------------------------
public on_AmmoX(id)
{
	if ( !sh_is_active() || !is_user_alive(id) ) return

	new iAmmoType = read_data(1)

	if ( iAmmoType == AMMOX_HEGRENADE && sh_get_user_has_hero(id,gHeroID) ) {
		prev_user_hegrenade_count[id] = user_hegrenade_count[id]
		user_hegrenade_count[id] = read_data(2)
		if ( (user_hegrenade_count[id]<prev_user_hegrenade_count[id])) {

			set_task(get_cvar_float("gambit_grenadetimer"), "gambit_weapons", id)

			if ( !sh_get_cooldown_flag(id) && gWillHit[id]) {
				// Have to Find the current HE grenade
				new iCurrent = -1
				while ( ( iCurrent = find_ent_by_class(iCurrent, "grenade") ) > 0 ) {
					new string[128]
					entity_get_string(iCurrent, EV_SZ_model, string, 127)

					if ( id == entity_get_edict(iCurrent, EV_ENT_owner) && equal(HEGRENADE_MODEL, string)) {

						new Float:glowColor[3] = {225.0, 0.0, 20.0}

						// Make the nade glow
						entity_set_int(iCurrent, EV_INT_renderfx, kRenderFxGlowShell)
						entity_set_vector(iCurrent, EV_VEC_rendercolor, glowColor)

						// Make the nade a bit invisible to make glow look better
						entity_set_int(iCurrent, EV_INT_rendermode, kRenderTransAlpha)
						entity_set_float(iCurrent, EV_FL_renderamt, 100.0 )

						// Make a trail
						message_begin(MSG_BROADCAST ,SVC_TEMPENTITY)
						write_byte(22)			//TE_BEAMFOLLOW
						write_short(iCurrent)	// entity:attachment to follow
						write_short(gGrenTrail)	// sprite index
						write_byte(10)		// life in 0.1's
						write_byte(10)		// line width in 0.1's
						write_byte(225)	// colour
						write_byte(90)
						write_byte(102)
						write_byte(255)	// brightness
						message_end()
					}
				}
			}
		}
		if (user_hegrenade_count[id] > 0) {
			// Got a new nade remove the timer
			remove_task(id)
		}
	}
}
//----------------------------------------------------------------------------------------------
