#define I_WANT_CONSTANTS
#define I_WANT_QUICK_CHECKS

#include "../my_include/superheromod.inc"
#include "sh_aux_stuff/sh_aux_inc.inc"
#include "../my_include/my_author_header.inc"
#include "custom_grenades/custom_grenades.inc"
#include "grim_reaper_inc/grim_reaper_inc.inc"
#include "chikoi_inc/chikoi_inc.inc"
#include "sh_aux_stuff/sh_aux_stuff_natives_pt5.inc"

#define YOWAI_SLAY_THANKS_FOR_THAT_ENTITY_CLASSNAME "Thanks for that"



new dmg_source_name_short_thanks[SAFE_BUFFER_SIZE+1]=
			YOWAI_SLAY_THANKS_FOR_THAT_ENTITY_CLASSNAME
new dmg_source_name_log_thanks[SAFE_BUFFER_SIZE+1]=
			YOWAI_SLAY_THANKS_FOR_THAT_ENTITY_CLASSNAME
new custom_dmg_id_thanks

#define YOWAI_PLAYER_MODEL "models/player/yowai/yowai.mdl"

// GLOBAL VARIABLES
new gHeroID
new gHeroID_chikoi = -1

new const gHeroName[] = "Yowai"
new g_hits[SH_MAXSLOTS+1] = {0, ...}
new g_yowai_mode_mask = 0
new g_max_hits_player[SH_MAXSLOTS+1]

new gHeroLevel
new dmg_threshold
new num_weak_hits
new max_hits,max_inc_lvl_inc,max_hits_p_inc

//----------------------------------------------------------------------------------------------
public plugin_init()
{
	// Plugin Info
	register_plugin("SUPERHERO Yowai", "1.0", AUTHOR)
	
	// DO NOT EDIT THIS FILE TO CHANGE CVARS, USE THE SHCONFIG.CFG
	create_cvar("Yowai_level", "8")
	create_cvar("Yowai_num_weak_hits", "30")
	create_cvar("Yowai_dmg_threshold", "150")
	create_cvar("Yowai_max_hits", "90")
	create_cvar("Yowai_max_hits_per_inc", "5")
	create_cvar("Yowai_hits_inc_lvl_gap", "5")
	gHeroID=shCreateHero(gHeroName, "Meek Maid", "Accumulate hits... and... whatever I guess I dont really know", true, "Yowai_level" )
	sh_register_superheromod_model(gHeroID,
								YOWAI_PLAYER_MODEL,
								YOWAI_PLAYER_MODEL,
								"yowai",
								"",
								"")

	custom_dmg_id_thanks=sh_log_custom_damage_source(gHeroID,
				dmg_source_name_short_thanks,
				dmg_source_name_log_thanks,
				0)

	RegisterHam(Ham_TakeDamage, "player", "Yowai_normal_damage",_,true)
	
}
//----------------------------------------------------------------------------------------------
public sh_hero_init(id, heroID, sh_init_mode:mode){
	if(heroID!=gHeroID) return

	if(sh_get_user_has_hero(id, gHeroID)){
		
		update_max_hits(id)
		reset_Yowai_user(id)
	}
	
}
public reset_Yowai_user(id){
	
	g_max_hits_player[id]=0;
	g_hits[id]=0;
	UnSet_BitVar(g_yowai_mode_mask,id)
	
	if(!is_user_bot(id)){
		sh_chat_message(id,gHeroID,"WAAAAAAhhhhhh~.... Sir? When is the end of my shift?")
	}
	
	
}
public update_max_hits(id){
	
	g_max_hits_player[id]=min(max_hits,num_weak_hits+(max_hits_p_inc*((sh_get_user_lvl(id)-gHeroLevel)/max_inc_lvl_inc)));
	
}

public status_hud(id){

	new chat_msg[130];
	
	if(!is_user_bot(id)){
		if(Get_BitVar(g_yowai_mode_mask,id)){
			formatex(chat_msg,129,"%d hit%s out of %d left until you finally die^n",
								g_hits[id],
								g_hits[id] == 1 ? "" : "s", 
								g_max_hits_player[id]);
		}
		sh_chat_message(id,gHeroID,"%s",chat_msg);
	}
}
//----------------------------------------------------------------------------------------------
public plugin_cfg()
{
	loadCVARS();
}
//----------------------------------------------------------------------------------------------
public loadCVARS()
{
	gHeroLevel=get_cvar_num("Yowai_level");
	max_hits=get_cvar_num("Yowai_max_hits");
	max_inc_lvl_inc=get_cvar_num("Yowai_hits_inc_lvl_gap")
	max_hits_p_inc=get_cvar_num("Yowai_max_hits_per_inc")
	dmg_threshold=get_cvar_num("Yowai_dmg_threshold")
	num_weak_hits=get_cvar_num("Yowai_num_weak_hits")
	
	gHeroID_chikoi = chikoi_get_hero_id()

}


//----------------------------------------------------------------------------------------------
public sh_client_spawn(id)
{
if ( sh_get_user_has_hero(id,gHeroID) &&is_user_alive(id) && sh_is_active() ) {
	
	give_custom_grenades(id,GREN_SHRAPNEL,6)
	reset_Yowai_user(id)
	update_max_hits(id)
}

}
public Inc_hits(id){

	if(g_hits[id]<g_max_hits_player[id]){
		g_hits[id]++;
	}

}

stock dmg_message(id,Float:damage){
	if(is_user_alive(id)){
		if(sh_get_user_has_hero(id,gHeroID) &&Get_BitVar(g_yowai_mode_mask,id)){
				if(!is_user_bot(id)){

				sh_chat_message(id,gHeroID,"Dont worry, ... youll be fine, like always... sigh... damage: %.0f is a scratch",damage)
				status_hud(id);
			}
		}
		Inc_hits(id)
	}

}
public Yowai_normal_damage(id, idinflictor, attacker, Float:damage, damagebits)
{

if(!sh_is_active()||sh_is_freezetime()) return HAM_IGNORED

if ( !is_user_alive(id) ) return HAM_IGNORED

if (!is_user_connected(attacker)) return HAM_IGNORED

if(sh_get_user_has_hero(id,gHeroID) && Get_BitVar(g_yowai_mode_mask,id)){
	
	new Float:tg_damage=floatmin(float(get_user_health(id)),float(dmg_threshold))
	if(g_hits[id]>=g_max_hits_player[id]){
		
		set_user_godmode(id,0)
		sh_extra_damage(id, attacker, 1,
					MY_HIT_HEAD,
					SH_DMG_KILL,
					_,_,_,
					SH_NEW_DMG_DARK_ARTS,
					custom_dmg_id_thanks)

		return HAM_IGNORED
	}
	else if(damage>=tg_damage){
		
		dmg_message(id,damage)
			
	}
	damage=0.0
	SetHamParamFloat(4, damage);
	
}
return HAM_IGNORED
}

//----------------------------------------------------------------------------------------------
public sh_hero_key(id, heroID, sh_key_mode:key)
{
if ( gHeroID != heroID ||!sh_get_user_has_hero(id,gHeroID) ) return

switch(key)
{
	case SH_KEYDOWN: {
		Yowai_kd(id)
	}
}
}
//----------------------------------------------------------------------------------------------
public Yowai_kd(id)
{

if (sh_is_freezetime() || !is_user_alive(id)||!sh_get_user_has_hero(id,gHeroID) ||Get_BitVar(g_yowai_mode_mask,id) ) {
	return
}
if ( sh_get_user_has_hero(id,gHeroID_chikoi)) {
	sh_sound_deny(id)
	sh_chat_message(id,gHeroID,"You have chikoi enabled. Will not enable")
	return
}
Set_BitVar(g_yowai_mode_mask,id)

sh_chat_message(id,gHeroID,"Activated yowai mode.")

}

public dmg_fwd_ret_id:sh_extra_damage_fwd_pre(&victim, &attacker, &damage,  &my_hitpoint_enum:bodypart,&sh_damage_mode:dmgMode, &sh_extra_damage_flags:sh_extra_dmg_flags, const Float:dmgOrigin[3],&dmg_type,&sh_thrash_brat_dmg_type:new_dmg_type, custom_weapon_id){
	if ( !sh_is_active() ||  !is_user_connected(victim)||!is_user_connected(attacker)){
	
		return DMG_FWD_PASS
	}
	if(sh_get_user_has_hero(victim,gHeroID) &&Get_BitVar(g_yowai_mode_mask,victim)){
		new tg_damage=min(get_user_health(victim),dmg_threshold)
		if((g_hits[victim]>=g_max_hits_player[victim])||
			(custom_weapon_id==sh_get_death_scythe_wpn_id())){
			
			
			set_user_godmode(victim,0)
			damage=get_user_health(victim)+1;
			dmgMode=SH_DMG_KILL
			return DMG_FWD_PASS
		}
		else if(damage>=tg_damage){
			dmg_message(victim,float(damage))
		}
		return DMG_FWD_BLOCK
	}
	return DMG_FWD_PASS
}
