#define I_WANT_CONSTANTS
#define I_WANT_QUICK_CHECKS
#define I_WANT_MISC_FUNCS
#include "../my_include/superheromod.inc"
#include "../task_allocator_inc/task_allocator_aux_stuff.inc"
#include "sh_aux_stuff/sh_aux_inc.inc"
#include "sh_aux_stuff/sh_aux_stuff_natives_pt1.inc"
#include "sh_aux_stuff/sh_aux_stuff_natives_pt3.inc"
#include "maria_riveter_inc/maria_riveter_funcs.inc"
#include "../my_include/my_author_header.inc"

new gHealthDrainValveMask = 0
new gHealthDrainValveTimerStartedMask = 0

// GLOBAL VARIABLES
//new gHeroID
new const gHeroName[] = "Maria"
new Float:gHealthDrainValveTimer[SH_MAXSLOTS+1]
new g_maria_points[SH_MAXSLOTS+1]
new Float:g_base_radius[SH_MAXSLOTS+1]
new Float:g_normal_radius[SH_MAXSLOTS+1]
new gNumRivets[SH_MAXSLOTS+1]

new Float:heal_period

new pcvar_maria_max_rivets
new pcvar_base_points
new pcvar_max_points
new pcvar_points_heal_coeff
new pcvar_points_radius_pct
new pcvar_dmg_points_pct
new pcvar_selfless_index
new pcvar_max_radius
new pcvar_base_radius
new pcvar_base_heal
new pcvar_maria_alpha
new pcvar_health_drain_begin_threshold
new pcvar_health_drain_end_threshold
new pcvar_begin_open_valve_timer;
new gHeroID


//----------------------------------------------------------------------------------------------
public plugin_init()
{
	// Plugin Info
	register_plugin("SUPERHERO Maria!", "1.0", AUTHOR)
	
	
	// DO NOT EDIT THIS FILE TO CHANGE CVARS, USE THE SHCONFIG.CFG
	register_cvar("maria_level", "8")
	register_cvar("maria_heal_period", "0.33")
	pcvar_maria_max_rivets = register_cvar("maria_num_rivets", "100")
	pcvar_points_radius_pct = register_cvar("maria_points_radius_pct", "0.1")
	pcvar_base_radius = register_cvar("maria_base_radius", "500")
	pcvar_health_drain_begin_threshold = register_cvar("maria_health_drain_begin_threshold", "500")
	pcvar_health_drain_end_threshold = register_cvar("maria_health_drain_end_threshold", "100")
	pcvar_begin_open_valve_timer = register_cvar("maria_begin_open_valve_timer", "3.0")
	pcvar_max_radius = register_cvar("maria_max_radius", "1000")
	pcvar_base_points = register_cvar("maria_base_points", "1000")
	pcvar_base_heal= register_cvar("maria_base_heal", "1000")
	pcvar_maria_alpha = register_cvar("maria_heal_alpha", "60")
	pcvar_max_points = register_cvar("maria_max_points", "1000")
	pcvar_dmg_points_pct = register_cvar("maria_dmg_points_pct", "0.1")
	pcvar_selfless_index = register_cvar("maria_selfless_index", "0.9")
	pcvar_points_heal_coeff = register_cvar("maria_points_heal_coeff", "4")
	gHeroID=shCreateHero(gHeroName, "Maria", "Martyr! Heal nearby teamates & become transparent", false, "maria_level",true )
	
	register_forward(FM_TraceLine,"fw_traceline");
	register_event("Damage", "maria_damage", "b", "2!0")

	init_hud_syncs()
}
public plugin_natives(){

	register_native("maria_riveter_dec_num_rivets","_maria_riveter_dec_num_rivets",0);
	register_native("maria_riveter_get_num_rivets","_maria_riveter_get_num_rivets",0);
	register_native("maria_riveter_set_num_rivets","_maria_riveter_set_num_rivets",0);
	
	
	register_native("maria_get_hero_id","_maria_get_hero_id",0);
	

	

}

public _maria_riveter_set_num_rivets(iPlugin,iParams){
	new id= get_param(1)
	new value_to_set=get_param(2)
	gNumRivets[id]=value_to_set;
}
public _maria_get_hero_id(iPlugin,iParams){
	
	return gHeroID
}
public _maria_riveter_get_num_rivets(iPlugin,iParams){


	new id= get_param(1)
	return gNumRivets[id]

}

public _maria_riveter_dec_num_rivets(iPlugin,iParams){


	new id= get_param(1)
	gNumRivets[id]-= (gNumRivets[id]>0)? 1:0

}
public sh_round_end(){

	remove_entity_name(MARIA_PROJECTILE_CLASSNAME)

}
//----------------------------------------------------------------------------------------------
public plugin_cfg()
{
	loadCVARS();
}
//----------------------------------------------------------------------------------------------
public loadCVARS()
{
	heal_period=get_cvar_float("maria_heal_period")

	set_task(heal_period, "maria_loop",_,_,_, "b")
}

//----------------------------------------------------------------------------------------------
public sh_hero_init(id, heroID, mode){
	
	if(sh_user_has_hero(id, gHeroID)){

		UnSet_BitVar(gHealthDrainValveMask,id);
		Set_BitVar(gHealthDrainValveTimerStartedMask,id);

		g_maria_points[id]=cvar_val(num, pcvar_base_points);
		g_base_radius[id]=cvar_val(float, pcvar_base_radius);
		gNumRivets[id]=cvar_val(num, pcvar_maria_max_rivets);
		gHealthDrainValveTimer[id]=cvar_val(float, pcvar_begin_open_valve_timer);

		
		maria_weapons(id)
	}
	else{
		sh_drop_weapon(id,MARIA_WEAPON_CLASSID,true);
		g_maria_points[id]=0;
		g_base_radius[id]=0.0
	}
	
	
}
//----------------------------------------------------------------------------------------------
maria_weapons(id)
{
	if ( sh_is_active() && is_user_alive(id)&&sh_user_has_hero(id,gHeroID) ) {
		sh_give_weapon(id, MARIA_WEAPON_CLASSID,true)
		new weapon_id=find_ent_by_owner(-1,MARIA_WEAPON,id);
		if(is_valid_ent(weapon_id)){
			cs_set_weapon_ammo(weapon_id, CLIP_SIZE);
			cs_set_user_bpammo(id, MARIA_WEAPON_CLASSID,gNumRivets[id]-CLIP_SIZE);
		}
	}
}
add_points(id,Float:damage){
	
	g_maria_points[id]=min(
		cvar_val(num, pcvar_max_points),
			g_maria_points[id]+(floatround(damage*cvar_val(float, pcvar_dmg_points_pct))))
	
	
}
public client_disconnected(id){

	g_maria_points[id]=0;
	g_base_radius[id]=0.0

}
calculate_healing(id,Float:values[2]){

new Float: maria_health=float(get_user_health(id))
new Float:value=heal_period*cvar_val(float, pcvar_base_heal)*
			cvar_val(float, pcvar_selfless_index)*
			(float(g_maria_points[id])/float(cvar_val(num, pcvar_max_points)));
values[1]=maria_health;
values[0]=(maria_health>value)?value:0.0;

}


bool:heal_teamate(id,i){
	if(!sh_is_active()||!is_user_alive(i)||!is_user_alive(id)||!hasRoundStarted()){
		
		
		return false
	}
	if(!sh_user_has_hero(id,gHeroID) ){
		
		
		return false
	}
	new Float:values[2]
	calculate_healing(id,values)

	new bool:result=generic_heal(heal_hp_hud_msg_sync,i,values[0]*
			cvar_val(float, pcvar_points_heal_coeff),_,INVIS,1,heal_period*2,_,1,0)
	if(result){
		sh_extra_damage(id,id,floatround(values[0]),"Selflessness",0)
		heal_stream(id,i,_,190)
	}
	return result

}

maria_heal_loop(id){

if(!sh_is_active()){

	return
}
if(!is_user_connected(id)){
	
	return
}
if(!is_user_alive(id)){

	return
}
if(!sh_user_has_hero(id,gHeroID) ){
	return
}
if(!Get_BitVar(gHealthDrainValveMask,id)){


	return;
}
static entlist[33];
static Float:client_origin[3]
entity_get_vector(id,EV_VEC_origin,client_origin)
new num_found = find_sphere_class(id,"player", g_normal_radius[id] ,entlist, 32);
new bool:healed=false;
for(new p=0;p<num_found;p++){
	new i=entlist[p]
	if(!is_user_alive(i)||(i==id)) continue;

	if(!sh_clients_are_same_team(i,id)) continue;
	
	if(float(get_user_health(id))>
			float(sh_get_max_hp(id))*
			(1.0-cvar_val(float, pcvar_selfless_index))){
		
		healed=heal_teamate(id,i)
		
	}
}
if(healed){

	set_render_with_color_const(id,LTGREEN,1,cvar_val(num, pcvar_maria_alpha),100,1)
	remove_glow_user(id,heal_period)
	
}
make_shockwave(client_origin,g_normal_radius[id],LineColors[LTGREEN],1,3,2,20,40)

}
public maria_damage(id)
{
	if ( !sh_is_active() || !is_user_alive(id)||!is_user_connected(id) ||!sh_user_has_hero(id,gHeroID) ) return
	
	new  Float:damage= float(read_data(2))
	
	add_points(id,damage)
}
public fw_traceline(Float:v1[3],Float:v2[3],noMonsters,id)
{
	if( !sh_is_active() || !is_user_alive(id) ||!sh_user_has_hero(id,gHeroID)  ||is_user_bot(id))
		return FMRES_IGNORED;

	
	// get ent looking at
	static ent, body;
	get_user_aiming(id, ent, body);
	
	// if looking at something
	if( pev_valid(ent))
	{
		if((pev(ent,pev_solid)==SOLID_SLIDEBOX)&&(get_user_team(id)==get_user_team(ent))){
			static hud_msg[128]
			static client_name[127]
			get_user_name(ent,client_name,127)
			new client_health=get_user_health(ent)
			formatex(hud_msg,127,"[SH] %s: HP of %s: %d/%d",gHeroName,client_name,client_health,sh_get_max_hp(ent))
			client_print(id,print_center,"%s",hud_msg)
			
		}	
		
	}	
	return FMRES_IGNORED;
}
public maria_loop(id){

	if ( !sh_is_active()) return

	for(new i=1;i < sh_maxplayers()+1;i++){
		if(is_user_alive(i)&&sh_user_has_hero(i,gHeroID)){
			update_stats(i)
			if((get_user_health(i)>=cvar_val(num, pcvar_health_drain_begin_threshold))){
					Set_BitVar(gHealthDrainValveTimerStartedMask,i)
					
			}
			gHealthDrainValveTimer[i]-=((Get_BitVar(gHealthDrainValveTimerStartedMask,i)&&(gHealthDrainValveTimer[i]>0.0))?heal_period:0.0)
			
			maria_heal_loop(i)
		}
	}
	
	
}
update_stats(id){
	
	if(sh_user_has_hero(id,gHeroID) ){
		g_normal_radius[id]=floatmin(floatadd(g_base_radius[id],floatmul(float(g_maria_points[id]),cvar_val(float, pcvar_points_radius_pct))),cvar_val(float, pcvar_max_radius));
		if(!Get_BitVar(gHealthDrainValveMask, id)&&
				(get_user_health(id)>=cvar_val(num, pcvar_health_drain_begin_threshold))&&
				(gHealthDrainValveTimer[id]<=0.0)){
			
			Set_BitVar(gHealthDrainValveMask, id)
			sh_chat_message(id,gHeroID,"Health drain valve opened!");
			return;
		}
		if(Get_BitVar(gHealthDrainValveMask, id)&&
				(get_user_health(id)<=cvar_val(num, pcvar_health_drain_end_threshold))){
			UnSet_BitVar(gHealthDrainValveMask, id);
			UnSet_BitVar(gHealthDrainValveTimerStartedMask, id);
			gHealthDrainValveTimer[id]=cvar_val(float, pcvar_begin_open_valve_timer)

			sh_chat_message(id,gHeroID,"Health drain valve closed.");
			
		}
	}
	
	
}

//----------------------------------------------------------------------------------------------
public sh_client_spawn(id)
{	
	if(is_user_alive(id) && sh_is_active()){
		if ( sh_user_has_hero(id,gHeroID) ) {

			gNumRivets[id]=cvar_val(num, pcvar_maria_max_rivets)
			UnSet_BitVar(gHealthDrainValveMask,id);
			gHealthDrainValveTimer[id]=cvar_val(float, pcvar_begin_open_valve_timer)
			Set_BitVar(gHealthDrainValveTimerStartedMask,id);
			g_maria_points[id]=cvar_val(num, pcvar_base_points);
			maria_weapons(id)
		}
	}
	
}