/* CVARS - copy and paste to shconfig.cfg

//SuperNoodle
SuperNoodle_level 9
SuperNoodle_health 200		//how much health SuperNoodle has
SuperNoodle_armor 100		//how much armor SuperNoodle has
SuperNoodle_m3mult 2.0		//Damage multiplyer for his M3
supernoodle_m249mult 1.5 //damage for his assault rifle
supernoodle_elitemult 2.5 //damage for his elites
supernoodle_g3sg1mult 2.5 //damage for his precision rifle

*/

#include "../my_include/superheromod.inc"
#include "q_barrel_inc/sh_q_barrel.inc"
#include "h_rifle_inc/sh_h_rifle.inc"
#include "arifle_inc/sh_arifle.inc"
#include "sliphantom_inc/sliphantom_inc.inc"
#include "../my_include/my_author_header.inc"

// GLOBAL VARIABLES
new gHeroName[]="SuperNoodle"
new gHeroID


new dmg_source_name_short_super_shotgun[SAFE_BUFFER_SIZE+1]="4arrel"
new dmg_source_name_log_super_shotgun[SAFE_BUFFER_SIZE+1]="4Barrel"
new custom_dmg_id_super_shotgun

new dmg_source_name_short_hunt_rifle[SAFE_BUFFER_SIZE+1]="hunting_rifle"
new dmg_source_name_log_hunt_rifle[SAFE_BUFFER_SIZE+1]="hunting_rifle"
new custom_dmg_id_hunt_rifle

new dmg_source_name_short_arifle[SAFE_BUFFER_SIZE+1]="assault_rifle"
new dmg_source_name_log_arifle[SAFE_BUFFER_SIZE+1]="assault_rifle"
new custom_dmg_id_arifle

new dmg_source_name_short_the_pistols[SAFE_BUFFER_SIZE+1]="the_pistols"
new dmg_source_name_log_the_pistols[SAFE_BUFFER_SIZE+1]="the_pistols"
new custom_dmg_id_the_pistols

//----------------------------------------------------------------------------------------------
public plugin_init()
{
	// Plugin Info
	register_plugin("SUPERHERO SuperNoodle", "1.0", AUTHOR)

	// DO NOT EDIT THIS FILE TO CHANGE CVARS, USE THE SHCONFIG.CFG
	create_cvar("SuperNoodle_level", "9")
	create_cvar("SuperNoodle_health", "200")
	create_cvar("SuperNoodle_armor", "100")
	create_cvar("supernoodle_m249mult", "1.5")
	create_cvar("supernoodle_elitemult", "1.5")
	create_cvar("SuperNoodle_dbarrel_mult", "2.0")
	create_cvar("SuperNoodle_scoutmult", "2.0")

	// FIRE THE EVENT TO CREATE THIS SUPERHERO!
	gHeroID=shCreateHero(gHeroName, "All GEARED UP!", "Super Shotgun, Precision & Assault Rifle & Dual Pistols from DUSK!/Extra Damage for all these/Unlimited Ammo. Extra HP and AP.", false, "SuperNoodle_level")


	custom_dmg_id_super_shotgun=sh_log_custom_damage_source(gHeroID,
				dmg_source_name_short_super_shotgun,
				dmg_source_name_log_super_shotgun,0)
	
	custom_dmg_id_hunt_rifle=sh_log_custom_damage_source(gHeroID,
				dmg_source_name_short_hunt_rifle,
				dmg_source_name_log_hunt_rifle,0)
	
	custom_dmg_id_arifle=sh_log_custom_damage_source(gHeroID,
				dmg_source_name_short_arifle,
				dmg_source_name_log_arifle,0)
	
	custom_dmg_id_the_pistols=sh_log_custom_damage_source(gHeroID,
				dmg_source_name_short_the_pistols,
				dmg_source_name_log_the_pistols,0)
	
	RegisterHam(Ham_TraceAttack,"player","SuperNoodle_damage",_,true)

	// Let Server know about SuperNoodle's Variable
	shSetMaxHealth(gHeroName, "SuperNoodle_health")
	shSetMaxArmor(gHeroName, "SuperNoodle_armor")
	shSetShieldRestrict(gHeroName)
}
public plugin_natives(){

	register_native("supernoodle_get_hero_id","_supernoodle_get_hero_id")

}
public _supernoodle_get_hero_id(iPlugins,iParams){
	
	return gHeroID

}
//----------------------------------------------------------------------------------------------
public sh_hero_init(id, heroID, sh_init_mode:mode){
	if(heroID!=gHeroID) return

	if(sh_get_user_has_hero(id, gHeroID)){
		
			SuperNoodle_weapons(id)
	}
	//This gets run if they had the power but don't anymore
	else {
		h_rifle_unset_h_rifle(id)
		arifle_unset_arifle(id)
		q_barrel_unset_q_barrel(id)
		sh_drop_weapon(id, CSW_M249,true)
		sh_drop_weapon(id, CSW_ELITE,true)
	}
	
}
//----------------------------------------------------------------------------------------------
public sh_client_spawn(id)
{
	if ( sh_is_active() && sh_get_user_has_hero(id,gHeroID)  && is_user_alive(id) ) {
		SuperNoodle_weapons(id)

	}
}
//----------------------------------------------------------------------------------------------
public SuperNoodle_weapons(id)
{
	if ( sh_is_active() && is_user_alive(id) && sh_get_user_has_hero(id,gHeroID)  ) {
		q_barrel_set_q_barrel(id)
		h_rifle_set_h_rifle(id)
		arifle_set_arifle(id)
		sh_give_weapon(id, CSW_ELITE)
	}
}
//RegisterHam(Ham_TraceAttack,"player","SuperNoodle_damage",_,true)
//----------------------------------------------------------------------------------------------
public SuperNoodle_damage(id, attacker, Float:damage, Float:Direction[3], Ptr, DamageBits)
{	

	if(damage<=0.0){
		return HAM_IGNORED
	}

	if ( !sh_is_active() || !is_user_alive(id) ) return HAM_IGNORED




	if ((attacker==id)||!is_user_connected(attacker)||!sh_get_user_has_hero(attacker,gHeroID)) return HAM_IGNORED


	new my_hitpoint_enum:the_hitpoint= my_hitpoint_enum:get_tr2(Ptr,TR_Hitgroup)


	new weapon = get_user_weapon(attacker)
	
	new extraDamage = 1
	new custom_wpn_to_use = -1;

	switch(weapon){
		case CSW_M3: {
			extraDamage = floatround(damage * get_cvar_float("SuperNoodle_dbarrel_mult") - damage)
			custom_wpn_to_use = custom_dmg_id_super_shotgun
		}
		case CSW_SCOUT: {
			extraDamage = floatround(damage * get_cvar_float("supernoodle_scoutmult") - damage)
			custom_wpn_to_use = custom_dmg_id_hunt_rifle
			
		}
		case CSW_M249: {
			extraDamage = floatround(damage * get_cvar_float("supernoodle_m249mult") - damage)
			custom_wpn_to_use = custom_dmg_id_arifle
			
		}
		case CSW_ELITE:{
			extraDamage = floatround(damage * get_cvar_float("supernoodle_elitemult") - damage)
			custom_wpn_to_use = custom_dmg_id_the_pistols
			
		}
		default:{
			return HAM_IGNORED
		}
	}
	if (extraDamage > 0){
		sh_extra_damage( id, attacker,extraDamage,
							the_hitpoint,
							_,_,_,_,
							SH_NEW_DMG_SUPER_BULLET,
							custom_wpn_to_use)
	}
	return HAM_IGNORED
}