#define I_WANT_QUICK_CHECKS
#define I_WANT_CONSTANTS
#define I_WANT_MISC_FUNCS
#include "../my_include/superheromod.inc"
#include "yandere_inc/sh_yandere_inc.inc"
#include "yandere_inc/sh_yandere_psychosis.inc"
#include "jetplane_inc/sh_jetplane_mg_funcs.inc"
#include "jetplane_inc/sh_jetplane_funcs.inc"
#include "jetplane_inc/sh_jetplane_bomb_funcs.inc"
#include "jetplane_inc/sh_yandere_get_set.inc"
#include "jetplane_inc/sh_jetplane_rocket_funcs.inc"
#include "sh_aux_stuff/sh_aux_inc.inc"
#include "./superheromod_help_files_includes/superheromod_help_files.inc"
#include "bleed_knife_inc/sh_bknife_fx.inc"
#include "sh_aux_stuff/sh_aux_stuff_natives_pt1.inc"
#include "sh_aux_stuff/sh_aux_funcs_misc_pt2.inc"
#include "sh_aux_stuff/sh_aux_stuff_natives_pt2.inc"
#include "sh_aux_stuff/sh_aux_stuff_natives_pt3.inc"
#include "sh_aux_stuff/sh_aux_stuff_natives_pt12.inc"
#include "sh_aux_stuff/sh_aux_stuff_natives_pt4.inc"
#include "sh_aux_stuff/sh_aux_stuff_natives_pt9.inc"
#include "special_fx_inc/sh_gatling_special_fx.inc"
#include "../my_include/my_author_header.inc"
#include "sh_aux_stuff/sh_aux_stuff_natives_pt5.inc"


stock const yandere_sentences[5][]={
	"Hiss.... Hiss.... Hiss.... Hiss.....",
	"Where are you... where... are you...",
	"Come out to plaaaaayyyy... There is NO WAY IM LETTING ANY OF YOU GO NOW!!!!!",
	"I hear their voices... I hear them... Then want... they want... red and black",
	"I want... all your blood. All of it.... and water the graves of my family with it."
}


new gHeroID
stock hud_sync
new Float:degen_iter_period

new pcvar_base_dmg_mult,
pcvar_dmg_pct_per_inc,
pcvar_base_extra_speed,
pcvar_speed_inc_per_inc,
pcvar_psychosis_degen_health_threshold,
pcvar_psychosis_degen_pct

new pcvar_angry_speed,
pcvar_angry_dmg_mult,
pcvar_angry_gravity,
pcvar_angry_degen_pct,
pcvar_angry_hitheal_pct,
pcvar_explode_radius,
pcvar_explode_maxdamage,
pcvar_curse_pct;
new pcvar_min_players
new pcvar_degen_health_extra_threshold
new pcvar_overheal_hp_max
new pcvar_trans_time
new generic_dmg_dark_arts = -1

//----------------------------------------------------------------------------------------------
public plugin_init()
{
	// Plugin Info
	register_plugin("SUPERHERO Selfless Yandere", "1.0", AUTHOR)
	// DO NOT EDIT THIS FILE TO CHANGE CVARS, USE THE SHCONFIG.CFG
	create_cvar("yandere_level", "8")
	create_cvar("yandere_degen_iter_period", "0.1")
	pcvar_base_dmg_mult = create_cvar("yandere_base_dmg_mult", "1.0")
	pcvar_dmg_pct_per_inc = create_cvar("yandere_dmg_pct_per_inc", "0.35")
	pcvar_explode_radius = create_cvar("yandere_explode_radius", "1")
	pcvar_explode_maxdamage = create_cvar("yandere_explode_maxdamage", "1")
	pcvar_psychosis_degen_pct = create_cvar("yandere_psychosis_degen_pct", "20.0")
	pcvar_psychosis_degen_health_threshold = create_cvar("yandere_psychosis_degen_health_threshold", "50.0")
	pcvar_trans_time = create_cvar("yandere_trans_time", "4.0")
	pcvar_base_extra_speed = create_cvar("yandere_base_extra_speed", "500")
	pcvar_speed_inc_per_inc = create_cvar("yandere_speed_inc_per_inc", "50")
	pcvar_curse_pct = create_cvar("yandere_angry_curse_pct", "0.5")
	pcvar_angry_speed = create_cvar("yandere_angry_speed", "1000")
	pcvar_angry_gravity = create_cvar("yandere_angry_gravity", "0.25")
	pcvar_angry_dmg_mult = create_cvar("yandere_angry_dmg_mult", "5.0")
	pcvar_angry_degen_pct = create_cvar("yandere_angry_degen_pct", "10.0")
	pcvar_overheal_hp_max = create_cvar("yandere_overheal_hp_max", "1000.0")
	pcvar_degen_health_extra_threshold = create_cvar("yandere_degen_health_extra_threshold", "500.0")
	pcvar_angry_hitheal_pct = create_cvar("yandere_angry_hitheal_pct", "1.0")
	pcvar_min_players = create_cvar("yandere_min_players", "6")
	gHeroID=shCreateHero(gHeroName, "YANDERE!", "Protect live teamates and avenge dead ones!", true, "yandere_level",true )
	

	sh_assign_hero_bit(gHeroID,SH_EXPLOSION_POWERS, true)

	sh_assign_hero_bit(gHeroID,hero_property_flags_id:53, true)

	sh_register_admin_only_hero(gHeroID,ADMIN_IMMUNITY,13,
				"No access was granted")


	static hero_name_arr[STRLEN_FOR_NAMES];
	arrayset(hero_name_arr,0,sizeof hero_name_arr)
	add(hero_name_arr,charsmax(hero_name_arr),gHeroName,charsmax(gHeroName))
	superheromod_help_link_hero(gHeroID, "Yandere: Help file","yandere_folder/","yandere_help_file.html",hero_name_arr)
	
	sh_register_superheromod_model(gHeroID,
								"models/player/yanderu/yanderu.mdl",
								"models/player/yanderu/yanderuT.mdl",
								"yanderu",
								"",
								"")
	sh_register_superheromod_model(gHeroID,
								"models/player/superyanderu/superyanderu.mdl",
								"models/player/superyanderu/superyanderuT.mdl",
								"superyanderu",
								"",
								"")
	sh_register_superheromod_model(gHeroID,
								"models/player/yanderu_psycho/yanderu_psycho.mdl",
								"models/player/yanderu_psycho/yanderu_psycho.mdl",
								"yanderu_psycho",
								"",
								"")

	register_event("Damage", "yandere_damage", "b", "2!0")
	register_event("CurWeapon", "weaponChange", "be", "1=1")

	RegisterHam(Ham_TraceAttack,"player","Yandere_ham_trace_damage",_,true)

	register_ham_hook_multiple(Ham_TraceAttack,
						full_entity_array_for_trace_attack,
						length_of_trace_attack_entity_array,
						"Yandere_Fire_Weapon",
						1,
						true)
	

	register_forward(FM_CmdStart, "yandere_angry_idle_checks")

	custom_dmg_id_senpai_avenger=sh_log_custom_damage_source(
								gHeroID,
								dmg_source_name_short_senpai_avenger,
								dmg_source_name_log_senpai_avenger,
								0)

	custom_dmg_id_drain=sh_log_custom_damage_source(
								gHeroID,
								dmg_source_name_short_drain,
								dmg_source_name_log_drain,
								0)

	custom_dmg_id_rage=sh_log_custom_damage_source(
								gHeroID,
								dmg_source_name_short_rage,
								dmg_source_name_log_rage,
								0)

	set_task( YANDERE_CYCLE_PERIOD, "yandere_loop", _, _, _, "b")

	init_hud_syncs()
	init_explosion_defaults()
}
public plugin_natives(){

	register_native("yandere_get_is_super","_yandere_get_is_super");
	register_native("yandere_get_hero_id","_yandere_get_hero_id");



}
public _yandere_get_hero_id(iPlugin,iParams){
	
	return gHeroID

}
public _yandere_get_is_super(iPlugin,iParams){
	new id= get_param(1)
	
	//return gSuperAngry[id]
	return Get_BitVar(gSuperAngryMask,id)

}

public yandere_angry_idle_checks(id, uc_handle){

	
	if(!sh_is_active()||sh_is_freezetime()){
		return FMRES_IGNORED
	}
	if(!is_user_alive(id)) return FMRES_IGNORED

	if(!sh_get_user_has_hero(id,gHeroID) ||!Get_BitVar(gSuperAngryMask,id)) return FMRES_IGNORED
	static butnprs

	Set_BitVar(gIdleAngryMask,id)
	butnprs =  get_uc(uc_handle, UC_Buttons);

	if (butnprs&IN_ATTACK || butnprs&IN_ATTACK2 || butnprs&IN_RELOAD || butnprs&IN_USE) UnSet_BitVar(gIdleAngryMask,id)

	if (butnprs&IN_JUMP) UnSet_BitVar(gIdleAngryMask,id)
	if (butnprs&IN_FORWARD || butnprs&IN_BACK || butnprs&IN_LEFT || butnprs&IN_RIGHT) UnSet_BitVar(gIdleAngryMask,id)
	if (butnprs&IN_MOVELEFT || butnprs&IN_MOVERIGHT) UnSet_BitVar(gIdleAngryMask,id)

	return FMRES_IGNORED

}
public Yandere_ham_trace_damage(Victim, Attacker, Float:Damage, Float:Direction[3], Ptr, DamageBits)
{
	if ( !sh_is_active() || !is_user_alive(Victim)||!is_user_alive(Attacker)){

		return HAM_IGNORED
	}

	new my_hitpoint_enum:the_hitpoint= my_hitpoint_enum:get_tr2(Ptr,TR_Hitgroup)

	return do_bleed_knife_attack(Victim,Attacker,gHeroID,15,65,
				sh_get_user_has_hero(Attacker,gHeroID) && Get_BitVar(gSuperAngryMask,Attacker),_,_,_,_,the_hitpoint)

	
}
//----------------------------------------------------------------------------------------------
public sh_hero_init(id, heroID, sh_init_mode:mode){
	if(heroID!=gHeroID) return

	if(sh_get_user_has_hero(id,gHeroID) ){
	
		gNormalSpeed[id]=cvar_val(float,pcvar_base_extra_speed)
		gBaseSpeed[id]=cvar_val(float,pcvar_base_extra_speed);
		UnSet_BitVar(gPlayedSoundMask,id)
		
	}
	else{
		killyandere(id,true)
	}
	
	
}

public get_first_alive(){


new the_players[SH_MAXSLOTS], pnum	
get_players(the_players, pnum, "a")
for (new k = 0; k < pnum; k++) {
	//will immediatly return valid value if pnum is >0
	return the_players[k]
}
return -1;


}
public yandere_sentence_loop(id){
	
	if ( !sh_is_active() || sh_is_freezetime() ||!sh_is_inround()) return
	new the_players[SH_MAXSLOTS], pnum, i		
	get_players(the_players, pnum, "a")
	for (new k = 0; k < pnum; k++) {
		
		i = the_players[k]

		if(sh_get_user_has_hero(i,gHeroID) &&Get_BitVar(gSuperAngryMask,i)){

			if(Get_BitVar(gIdleAngryMask,i)||(get_user_health(i)>
						cvar_val(num,pcvar_degen_health_extra_threshold))){
				
				static client_name[128]
				new user_health=get_user_health(i)
				new degen_dmg_2_take= (float(user_health)>cvar_val(float, pcvar_psychosis_degen_pct))?
											floatround((float(user_health)-cvar_val(float, pcvar_psychosis_degen_health_threshold))*
														degen_iter_period*
														0.01*
														(sh_get_id_bit(i,SH_IS_PSYCHOSIS)?cvar_val(float, pcvar_psychosis_degen_pct):
															cvar_val(float,pcvar_angry_degen_pct)),floatround_ceil)*
														(Get_BitVar(gIdleAngryMask,i)?2:1):0
	
				if(degen_dmg_2_take>0){
					new client_origin[3]
					get_user_origin(i,client_origin)
					new Float:floatalpha=25.0+floatmax(0.0,floatmin(120.0,255.0*(float(user_health)/float(cvar_val(num,pcvar_overheal_hp_max)))))
					sh_screen_fade(i, 0.5, 2.5, LineColors[RED][0], LineColors[RED][1], LineColors[RED][2], floatround(floatalpha))
					
					sh_extra_damage(i,i,degen_dmg_2_take,
									MY_HIT_HEAD,
									_,_,_,_,
									SH_NEW_DMG_DRAIN,custom_dmg_id_drain)
					
					fx_bleed(client_origin)
					if(degen_iter_period>1.0){
							get_user_name(i,client_name,127)
							emit_sound(i, CHAN_AUTO, YANDERE_CYCLE, 1.0, 0.0, 0, PITCH_NORM)
							sh_chat_message(0,gHeroID,"%s: %s",client_name,yandere_sentences[generate_int(0,4)])
					}
				}
				
			}
		}
	}
}

notify_yanderes_about_team_life(id=-1,disconnected=0){
	if(!sh_is_active()) return
	
	if(!disconnected){
		if(!is_user_connected(id)) return
	}
	
	new the_players[SH_MAXSLOTS], pnum, i		
	
	get_players(the_players, pnum, "a")
	
	for (new k = 0; k < pnum; k++) {
		
		i = the_players[k]

		if(!sh_get_user_has_hero(i,gHeroID) ) continue;

		if(!(disconnected)){
			if(!sh_clients_are_same_team(id,i)){
				if((id!=i)){
					continue;
				}
			}
		}
		sh_get_player_counts(i,1,g_mates_alive[i],g_mates_dead[i])
		new bool:can_transform= (get_playersnum(0)>=cvar_val(num,pcvar_min_players))&&(g_mates_alive[i]<=0)
		if(can_transform && !Get_BitVar(gSuperAngryMask,i) && sh_is_inround() &&!sh_is_freezetime()){

			Set_BitVar(gTransTimerStartedMask,i)

		}
		else{

			UnSet_BitVar(gTransTimerStartedMask,i)

		}
		
		update_stats(i)
		if(!sh_is_freezetime()&&!sh_get_stun(i)){
			set_user_maxspeed(i,gNormalSpeed[i])
		}
	}


}
public yandere_loop(id){
	if ( !sh_is_active() || sh_is_freezetime() ) return

	new the_players[SH_MAXSLOTS], pnum, i		
	get_players(the_players, pnum, "a")
	for (new k = 0; k < pnum; k++) {
		
		i = the_players[k]

		if(!sh_get_user_has_hero(i,gHeroID)){
			continue
		}
		if(!is_user_bot(i)&&Get_BitVar(gTransTimerStartedMask,i)){
			client_print(i,print_center,"All teamates died! Grief will take over in... %0.2fs^n",gTransTimer[i])
		}
		yandere_timer_transform(i)
	}
}


update_stats(id){

	if(!is_user_alive(id)) return
	if(!sh_get_user_has_hero(id,gHeroID) ) return
	
	new Float:maxspeed=get_user_maxspeed(id)
	
	if(Get_BitVar(gSuperAngryMask,id)){

		gNormalDmgMult[id]=cvar_val(float,pcvar_angry_dmg_mult)
		gNormalSpeed[id]=floatmax(cvar_val(float,pcvar_angry_speed),maxspeed);
		
	}
	else{
		gNormalDmgMult[id]=floatmin(floatadd(cvar_val(float,pcvar_base_dmg_mult),
					floatmul(cvar_val(float,pcvar_dmg_pct_per_inc),
					float(g_mates_dead[id]))),cvar_val(float,pcvar_angry_dmg_mult));
		gNormalSpeed[id]=floatmin(floatadd(gBaseSpeed[id],
				floatmul(cvar_val(float,pcvar_speed_inc_per_inc),float(g_mates_dead[id]))),
				cvar_val(float,pcvar_angry_speed));
	}
}
public yandere_timer_transform(id){
	
	if(Get_BitVar(gSuperAngryMask,id)){

		new Float:gravity=get_user_gravity(id)
		set_user_gravity(id,floatmin(cvar_val(float,pcvar_angry_gravity),gravity))
		if(g_mates_alive[id]>0){

			UnSet_BitVar(gSuperAngryMask,id)
			update_stats(id)
			sh_reset_min_gravity(id)
			set_user_maxspeed(id,gNormalSpeed[id])
			sh_chat_message(0,gHeroID,"Hah... What happened?");
			UnSet_BitVar(gPlayedSoundMask,id)
			if(user_has_weapon(id,YANDERE_WEAPON_CLASSID)){
				sh_drop_weapon(id, YANDERE_WEAPON_CLASSID,true)
			}

			emit_sound(id, CHAN_AUTO, YANDERE_WARCRIES[curr_player_sound[id]],
				VOL_NORM, ATTN_NORM, SND_STOP, PITCH_NORM);
		}
	}
	else{
		UnSet_BitVar(gIdleAngryMask,id)
		if(Get_BitVar(gTransTimerStartedMask,id)){

			gTransTimer[id]-= YANDERE_CYCLE_PERIOD
			if((gTransTimer[id]<=0.0)){
				
				Set_BitVar(gSuperAngryMask,id)
				update_stats(id)
				sh_reset_min_gravity(id)
				set_user_maxspeed(id,gNormalSpeed[id])
				if(!Get_BitVar(gPlayedSoundMask,id)){
					static client_name[128]
					get_user_name(id,client_name,127)
					sh_chat_message(0,gHeroID,"%s: Ok. NOW Im mad!",client_name);
					
					emit_sound(id, CHAN_AUTO, YANDERE_WARCRIES[curr_player_sound[id]],
						VOL_NORM, ATTN_NORM, SND_STOP, PITCH_NORM);
					curr_player_sound[id]=generate_int(0,num_yandere_warcries-1)
					emit_sound(id, CHAN_AUTO, YANDERE_WARCRIES[curr_player_sound[id]], 1.0, 0.0, 0, PITCH_NORM)
					Set_BitVar(gPlayedSoundMask,id)
				}
				gTransTimer[id]=cvar_val(float,pcvar_trans_time)
			}
		}
		else if(gTransTimer[id]!=cvar_val(float,pcvar_trans_time)){

			gTransTimer[id]=cvar_val(float,pcvar_trans_time)
		}
		if(Get_BitVar(gSuperAngryMask,id)&&is_user_alive(id)){
			UnSet_BitVar(gTransTimerStartedMask,id)
			BlowUp(id)
			jet_destroy(id)
			if(!sh_is_freezetime()){
				if(!user_has_weapon(id,YANDERE_WEAPON_CLASSID)){
					sh_give_weapon(id, YANDERE_WEAPON_CLASSID,true)
				}
			}
		}
	}

}

public client_disconnected(id){

	killyandere(id,true)
	notify_yanderes_about_team_life(-1,1)
}

//----------------------------------------------------------------------------------------------
public plugin_cfg()
{
loadCVARS();
}
//----------------------------------------------------------------------------------------------
public loadCVARS()
{
degen_iter_period=get_cvar_float("yandere_degen_iter_period")
generic_dmg_dark_arts = get_weapon_id_for_generic_dmg_source(SH_NEW_DMG_DARK_ARTS)

set_task( degen_iter_period, "yandere_sentence_loop", _, _, _, "b")

}
public sh_round_start(){

	for(new id=1;id<sh_maxplayers()+1;id++){

		if(!is_user_alive(id)) return

		if ( sh_get_user_has_hero(id,gHeroID) ) {
			if(get_user_maxspeed(id)<gNormalSpeed[id]){
				set_user_maxspeed(id,gNormalSpeed[id])
			}
		}

	}
}
//----------------------------------------------------------------------------------------------
public sh_client_spawn(id, bool:newRound)
{	if(is_user_alive(id) && sh_is_active()){
		g_is_cursed_masks[id]=0
		if ( sh_get_user_has_hero(id,gHeroID) ) {
			
			sh_drop_weapon(id, YANDERE_WEAPON_CLASSID,true)
			yandere_unpsychosis_user(id)
			sh_end_cooldown(id+SH_COOLDOWN_TASKID);
			UnSet_BitVar(gSuperAngryMask,id);
			UnSet_BitVar(gPlayedSoundMask,id);
			gNormalSpeed[id]=gBaseSpeed[id]=cvar_val(float,pcvar_base_extra_speed)
			gTransTimer[id]=cvar_val(float,pcvar_trans_time);
			UnSet_BitVar(gTransTimerStartedMask,id)
			emit_sound(id, CHAN_AUTO, YANDERE_CYCLE, 1.0, 0.0, SND_STOP, PITCH_NORM)
			emit_sound(id, CHAN_VOICE, YANDERE_PAIN, 1.0, 0.0, SND_STOP, PITCH_NORM)
			if(!newRound&&(get_user_maxspeed(id)<gBaseSpeed[id])){
				set_user_maxspeed(id,gBaseSpeed[id])
			}
		}
		notify_yanderes_about_team_life(id)
		
	}
	
}
public yandere_damage(id)
{
	if ( !sh_is_active() || !is_user_alive(id)) return PLUGIN_CONTINUE
	
	new  damage= read_data(2)
	new weapon, bodypart, attacker = get_user_attacker(id, weapon, bodypart)
	if ( !is_user_alive(attacker)) return PLUGIN_CONTINUE
	
	if(sh_clients_are_same_team(id,attacker)||(id==attacker)){
		return PLUGIN_CONTINUE
	}
	if ( sh_get_user_has_hero(attacker,gHeroID) ) {
		new Float:extraDamage =damage * gNormalDmgMult[attacker] - damage
		if (floatround(extraDamage) > 0.0){
			
			if(Get_BitVar(gSuperAngryMask,attacker)&&(weapon==YANDERE_WEAPON_CLASSID)){
				sh_extra_damage(id, attacker, floatround(extraDamage),
								my_hitpoint_enum:bodypart,
								_,_,_,_,
								SH_NEW_DMG_DARK_ARTS,
								custom_dmg_id_senpai_avenger)
			}
			else {
				sh_extra_damage(id, attacker, floatround(extraDamage),
								my_hitpoint_enum:bodypart,
								_,_,_,_,
								SH_NEW_DMG_DARK_ARTS,
								custom_dmg_id_rage)
			}
			if(Get_BitVar(gSuperAngryMask,attacker)){
				static attacker_name[128],client_name[128]
				get_user_name(attacker,attacker_name,127)
				get_user_name(id,client_name,127)
				sh_set_stun(id,2.0,default_stun_speed)
			
				generic_heal(heal_hp_hud_msg_sync,attacker,extraDamage*
					cvar_val(float,pcvar_angry_hitheal_pct),
					cvar_val(num,pcvar_overheal_hp_max),RED,1,_,70,1)
				if(!is_user_alive(id)){
					static Float:origin[3];
					// player fades.. 
					set_user_rendering(id, kRenderFxFadeSlow, 255, 255, 255, kRenderTransColor, 4); 
					entity_get_vector(id,EV_VEC_origin,origin)
					anime_kill_fx(origin)
					
				}
				if((weapon==CSW_KNIFE)&&!sh_get_user_has_hero(id,gHeroID) ){
					
					Set_BitVar(g_is_cursed_masks[id],attacker)
					
					if(!is_user_bot(attacker)){
						sh_chat_message(attacker,gHeroID,"%s has been cursed!",client_name)
					}
				
					if(!is_user_bot(id)){
						sh_chat_message(id,gHeroID,"%s has put a curse on you!",attacker_name)
					}
				
				}
			}
		}	
		
	}
	if( sh_get_user_has_hero(id,gHeroID)  && is_user_alive(attacker)){
		if(Get_BitVar(g_is_cursed_masks[attacker],id)){
			if(generate_float(0.0,1.0)<cvar_val(float,pcvar_curse_pct)){
				set_user_godmode(id,0)
				sh_extra_damage(attacker,id,1,_,
							SH_DMG_KILL,
							_,_,_,
							SH_NEW_DMG_DARK_ARTS,
							generic_dmg_dark_arts)
				UnSet_BitVar(g_is_cursed_masks[attacker],id)
			}
		}
	
	
	}
	return PLUGIN_CONTINUE
}
public plugin_precache()
{
	for(new i=0;i<num_yandere_warcries;i++){
		engfunc(EngFunc_PrecacheSound,YANDERE_WARCRIES[i])
	}
	engfunc(EngFunc_PrecacheSound,YANDERE_CYCLE)
	engfunc(EngFunc_PrecacheSound,YANDERE_THELAST)
	engfunc(EngFunc_PrecacheSound,YANDERE_THELAST2)
	engfunc(EngFunc_PrecacheSound,YANDERE_THELAST3)
	engfunc(EngFunc_PrecacheSound,YANDERE_PAIN)
	for(new i=0;i<NUM_YANDERE_PAIN_SOUNDS;i++){
		
		engfunc(EngFunc_PrecacheSound,yandere_pain_sounds[i])
	
	}
	engfunc(EngFunc_PrecacheModel,YANDERE_SHOTGUN_V_MODEL)
	engfunc(EngFunc_PrecacheModel,YANDERE_SHOTGUN_P_MODEL)
	engfunc(EngFunc_PrecacheModel,YANDERE_KNIFE_V_MODEL)
	engfunc(EngFunc_PrecacheModel,YANDERE_KNIFE_P_MODEL)
	engfunc(EngFunc_PrecacheModel,YANDERE_PSYCHO_KNIFE_V_MODEL)
	engfunc(EngFunc_PrecacheModel,YANDERE_PSYCHO_KNIFE_P_MODEL)

	
	
}


//----------------------------------------------------------------------------------------------
public sh_hero_key(id, heroID, sh_key_mode:key)
{
if ( gHeroID != heroID ||!sh_get_user_has_hero(id,gHeroID) ) return

switch(key)
{
	case SH_KEYDOWN: {
		yandere_kd(id)
	}
	
	case SH_KEYUP: {
		
		yandere_ku(id)
	}
}
}
public yandere_kd(id)
{
	
	if ( !is_user_alive(id)||!sh_get_user_has_hero(id,gHeroID) ) return

	if(Get_BitVar(gSuperAngryMask,id)){
		if ( sh_get_cooldown_flag(id)||
				sh_get_id_bit(id,SH_IS_PSYCHOSIS) ) {
			
			if(!is_user_bot(id)){
				sh_sound_deny(id)
				sh_chat_message(id,gHeroID,"Youve blown a fuse already! Wait a bit more to blow the next one, at least!")
			}
			return
		}
		new client_name[128]
		get_user_name(id,client_name,127)
		sh_chat_message(0,gHeroID,"%s LOST IT!!!!!",client_name)
		yandere_psychosis_user(id)
	}
	else{
		new bool:jet_deployed_here=bool:jet_deployed(id)
		if(!jet_loaded(id)&&!jet_deployed_here){

			if(!is_user_bot(id)){
				sh_sound_deny(id)
				sh_chat_message(id, gHeroID, "The jet is not loaded yet!")
			}
			return
			
		}

		if(jet_deployed_here){
			
			jet_destroy(id)
			
			if(!is_user_bot(id)){
				sh_chat_message(id, gHeroID, "You J-ed out!!")
			}
			return
			
		}
		yandere_jet_charge_user(id)
	
	
	}
}
//----------------------------------------------------------------------------------------------
public yandere_ku(id)
{
	
	if ( !is_user_alive(id) ||!sh_get_user_has_hero(id,gHeroID) ) {
		return
	}
	
	if(!jet_deployed(id)){
		
		yandere_jet_uncharge_user(id)
	}
}
public sh_round_end(){
	
	for(new i=1;i< sh_maxplayers()+1;i++){
		
		if(is_user_alive(i)){
			if(sh_get_user_has_hero(i,gHeroID) ){
				jet_destroy(i)
			}
			
		}
	
	}
	
	remove_entity_name(JETPLANE_BOMB_CLASSNAME)
	remove_entity_name(JETPLANE_SHELL_CLASSNAME)
	remove_entity_name(JETPLANE_ROCKET_CLASSNAME)
	
	new total_alive,total_dead;
	sh_get_player_counts(0,0,total_alive,total_dead)
	
	if(total_alive>1){
		return;
		
	}
	new last_alive=get_first_alive()
	if(!is_user_alive(last_alive)) return
	if(sh_get_user_has_hero(last_alive,gHeroID) && Get_BitVar(gSuperAngryMask,last_alive) ){
		static client_name[128]
		get_user_name(last_alive,client_name,127)
		sh_chat_message(0,gHeroID,"%s : What... have I done...",client_name)
		
	}
}

public Yandere_Fire_Weapon(Victim, Attacker, Float:Damage, Float:Direction[3], Ptr, DamageBits)
{
	generic_weapon_tracer_logic(Attacker,bool:Get_BitVar(gSuperAngryMask,Attacker),_,gHeroID,true,sh_custom_color:{RED,RED,RED})

}

killyandere(id,bool:dropping=false){
	
	if(!is_user_connected(id)||!sh_is_active()) return
	if(sh_get_user_has_hero(id,gHeroID) ||dropping){
		
		if(Get_BitVar(gSuperAngryMask,id)){
			static Float:origin[3]
			entity_get_vector(id,EV_VEC_origin,origin)
			fx_invisible(id)
			anime_kill_fx(origin)
			for(new i=1;i< sh_maxplayers()+1;i++){
				UnSet_BitVar(g_is_cursed_masks[i],id)
			}
			if(sh_get_id_bit(id,SH_IS_PSYCHOSIS)){
				yandere_unpsychosis_user(id)
			}
		}
		else if(jet_deployed(id)){
			
			jet_destroy(id);
		}
		UnSet_BitVar(gSuperAngryMask,id)
		sh_reset_min_gravity(id)
		sh_reset_max_speed(id)
		
		
	}
	g_is_cursed_masks[id]=0
}
public sh_client_death(id){
	
	killyandere(id)
	notify_yanderes_about_team_life(id)
}

//----------------------------------------------------------------------------------------------
public BlowUp(id)
{

	// blowup even if dead
	explosion(gHeroID,id,
		cvar_val(float,pcvar_explode_radius),
		cvar_val(float,pcvar_explode_maxdamage)
		,default_explode_knock_force_magnitude,1)
	
}
//----------------------------------------------------------------------------------------------

public weaponChange(id)
{
	if (!sh_is_active()) return
	if(!sh_get_user_has_hero(id,gHeroID) ) return

	new wpnid = read_data(2)

	if ( g_prevWeapon[id] != wpnid ) {
		if ((get_user_maxspeed(id) < gNormalSpeed[id])&&!sh_get_stun(id)&&sh_is_inround()&&!sh_is_freezetime()){
			set_user_maxspeed(id, gNormalSpeed[id])
		}
	}
	g_prevWeapon[id] = wpnid
	
	if (!Get_BitVar(gSuperAngryMask,id)) return
	
	
	if (wpnid == YANDERE_WEAPON_CLASSID) {
		set_pev(id, pev_viewmodel2,YANDERE_SHOTGUN_V_MODEL)
		set_pev(id, pev_weaponmodel2,YANDERE_SHOTGUN_P_MODEL)
	}
	else if (wpnid == CSW_KNIFE) {
		if(sh_get_id_bit(id,SH_IS_PSYCHOSIS)){
			set_pev(id, pev_viewmodel2,YANDERE_PSYCHO_KNIFE_V_MODEL)
			set_pev(id, pev_weaponmodel2,YANDERE_PSYCHO_KNIFE_P_MODEL)
		}
		else{
		
			set_pev(id, pev_viewmodel2,YANDERE_KNIFE_V_MODEL)
			set_pev(id, pev_weaponmodel2,YANDERE_KNIFE_P_MODEL)
		
		}
	}
}