#define I_WANT_QUICK_CHECKS
#define I_WANT_CONSTANTS
#define I_WANT_MISC_FUNCS
#include "../my_include/superheromod.inc"
#include "../task_allocator_inc/task_allocator_aux_stuff.inc"
#include "yandere_inc/sh_yandere_inc.inc"
#include "yandere_inc/sh_yandere_psychosis.inc"
#include "jetplane_inc/sh_jetplane_mg_funcs.inc"
#include "jetplane_inc/sh_jetplane_funcs.inc"
#include "jetplane_inc/sh_jetplane_bomb_funcs.inc"
#include "jetplane_inc/sh_yandere_get_set.inc"
#include "jetplane_inc/sh_jetplane_rocket_funcs.inc"
#include "sh_aux_stuff/sh_aux_inc.inc"
#include "./superheromod_help_files_includes/superheromod_help_files.inc"
#include "bleed_knife_inc/sh_bknife_fx.inc"
#include "sh_aux_stuff/sh_aux_stuff_natives_pt1.inc"
#include "sh_aux_stuff/sh_aux_stuff_natives_pt2.inc"
#include "sh_aux_stuff/sh_aux_stuff_natives_pt3.inc"
#include "sh_aux_stuff/sh_aux_stuff_natives_pt4.inc"
#include "special_fx_inc/sh_gatling_special_fx.inc"
#include "../my_include/my_author_header.inc"
#include "sh_aux_stuff/sh_aux_stuff_natives_pt5.inc"

stock hud_sync
new Float:degen_iter_period

new pcvar_base_dmg_mult,
pcvar_dmg_pct_per_inc,
pcvar_base_extra_speed,
pcvar_speed_inc_per_inc

new pcvar_angry_speed,
pcvar_angry_dmg_mult,
pcvar_angry_gravity,
pcvar_angry_degen_pct,
pcvar_angry_hitheal_pct,
pcvar_explode_radius,
pcvar_explode_maxdamage,
pcvar_curse_pct;
new pcvar_min_players
new pcvar_degen_health_extra_threshold
new pcvar_overheal_hp_max
new pcvar_trans_time
//----------------------------------------------------------------------------------------------
public plugin_init()
{
	// Plugin Info
	register_plugin("SUPERHERO Selfless Yandere", "1.0", AUTHOR)
	// DO NOT EDIT THIS FILE TO CHANGE CVARS, USE THE SHCONFIG.CFG
	register_cvar("yandere_level", "8")
	register_cvar("yandere_degen_iter_period", "0.1")
	pcvar_base_dmg_mult = register_cvar("yandere_base_dmg_mult", "1.0")
	pcvar_dmg_pct_per_inc = register_cvar("yandere_dmg_pct_per_inc", "0.35")
	pcvar_explode_radius = register_cvar("yandere_explode_radius", "1")
	pcvar_explode_maxdamage = register_cvar("yandere_explode_maxdamage", "1")
	pcvar_trans_time = register_cvar("yandere_trans_time", "4.0")
	pcvar_base_extra_speed = register_cvar("yandere_base_extra_speed", "500")
	pcvar_speed_inc_per_inc = register_cvar("yandere_speed_inc_per_inc", "50")
	pcvar_curse_pct = register_cvar("yandere_angry_curse_pct", "0.5")
	pcvar_angry_speed = register_cvar("yandere_angry_speed", "1000")
	pcvar_angry_gravity = register_cvar("yandere_angry_gravity", "0.25")
	pcvar_angry_dmg_mult = register_cvar("yandere_angry_dmg_mult", "5.0")
	pcvar_angry_degen_pct = register_cvar("yandere_angry_degen_pct", "10.0")
	pcvar_overheal_hp_max = register_cvar("yandere_overheal_hp_max", "1000.0")
	pcvar_degen_health_extra_threshold = register_cvar("yandere_degen_health_extra_threshold", "500.0")
	pcvar_angry_hitheal_pct = register_cvar("yandere_angry_hitheal_pct", "1.0")
	pcvar_min_players = register_cvar("yandere_min_players", "6")
	gHeroID=shCreateHero(gHeroName, "YANDERE!", "Protect live teamates and avenge dead ones!", true, "yandere_level",true )
	

	static hero_name_arr[STRLEN_FOR_NAMES];
	arrayset(hero_name_arr,0,sizeof hero_name_arr)
	add(hero_name_arr,charsmax(hero_name_arr),gHeroName,charsmax(gHeroName))
	superheromod_help_link_hero(gHeroID, "Yandere: Help file","yandere_folder/","yandere_help_file.html",hero_name_arr)
	
	sh_register_superheromod_model(gHeroID,
								"models/player/yanderu/yanderu.mdl",
								"models/player/yanderu/yanderuT.mdl",
								"yanderu",
								"",
								"")
	sh_register_superheromod_model(gHeroID,
								"models/player/superyanderu/superyanderu.mdl",
								"models/player/superyanderu/superyanderuT.mdl",
								"superyanderu",
								"",
								"")
	sh_register_superheromod_model(gHeroID,
								"models/player/yanderu_psycho/yanderu_psycho.mdl",
								"models/player/yanderu_psycho/yanderu_psycho.mdl",
								"yanderu_psycho",
								"",
								"")

	register_event("Damage", "yandere_damage", "b", "2!0")
	register_event("CurWeapon", "weaponChange", "be", "1=1")
	register_event("DeathMsg","death","a")
	
	register_srvcmd("yandere_init", "yandere_init")
	shRegHeroInit(gHeroName, "yandere_init")
	register_srvcmd("yandere_kd", "yandere_kd")
	shRegKeyDown(gHeroName, "yandere_kd")
	register_srvcmd("yandere_ku", "yandere_ku")
	shRegKeyUp(gHeroName, "yandere_ku")
	register_event("CurWeapon", "fire_weapon", "be", "1=1", "3>0")
	RegisterHam(Ham_TakeDamage,"player","Yandere_ham_damage",_,true)
	register_forward(FM_CmdStart, "yandere_angry_idle_checks")

	custom_dmg_id_senpai_avenger=sh_log_custom_damage_source(
								gHeroID,
								dmg_source_name_short_senpai_avenger,
								dmg_source_name_long_senpai_avenger,
								0)

	custom_dmg_id_drain=sh_log_custom_damage_source(
								gHeroID,
								dmg_source_name_short_drain,
								dmg_source_name_long_drain,
								0)

	custom_dmg_id_rage=sh_log_custom_damage_source(
								gHeroID,
								dmg_source_name_short_rage,
								dmg_source_name_long_rage,
								0)
	
	set_task( YANDERE_CYCLE_PERIOD, "yandere_loop", _, _, _, "b")

	init_hud_syncs()
	init_explosion_defaults()
}
public plugin_natives(){

	register_native("yandere_get_is_super","_yandere_get_is_super",0);
	register_native("yandere_get_hero_id","_yandere_get_hero_id",0);



}
public _yandere_get_is_super(iPlugin,iParams){
	new id= get_param(1)
	
	//return gSuperAngry[id]
	return Get_BitVar(gSuperAngryMask,id)

}
public _yandere_get_hero_id(iPlugin,iParams){
	
	return gHeroID

}

public yandere_angry_idle_checks(id, uc_handle){

	
	if(!sh_is_active()||sh_is_freezetime()) return FMRES_IGNORED;
	
	if(!is_user_alive(id)) return FMRES_IGNORED

	if(!sh_user_has_hero(id,gHeroID) ||!Get_BitVar(gSuperAngryMask,id)) return FMRES_IGNORED
	static butnprs

	Set_BitVar(gIdleAngryMask,id)
	butnprs =  get_uc(uc_handle, UC_Buttons);

	if (butnprs&IN_ATTACK || butnprs&IN_ATTACK2 || butnprs&IN_RELOAD || butnprs&IN_USE) UnSet_BitVar(gIdleAngryMask,id)

	if (butnprs&IN_JUMP) UnSet_BitVar(gIdleAngryMask,id)
	if (butnprs&IN_FORWARD || butnprs&IN_BACK || butnprs&IN_LEFT || butnprs&IN_RIGHT) UnSet_BitVar(gIdleAngryMask,id)
	if (butnprs&IN_MOVELEFT || butnprs&IN_MOVERIGHT) UnSet_BitVar(gIdleAngryMask,id)

	return FMRES_IGNORED

}
public Yandere_ham_damage(id, idinflictor, attacker, Float:damage, damagebits)
{


	if ( !sh_is_active() || !is_user_alive(id)||!is_user_alive(attacker)){

		return HAM_IGNORED
	}

	new ham_result=do_bleed_knife_attack(id,attacker,gHeroID,15,65,
				sh_user_has_hero(attacker,gHeroID) && Get_BitVar(gSuperAngryMask,attacker));



	return ham_result
	
}
public yandere_init()
{
	
	// First Argument is an id
	new temp[6]
	read_argv(1,temp,5)
	new id=str_to_num(temp)

	if(sh_user_has_hero(id,gHeroID) ){
		
		sh_reset_max_speed(id)
		gNormalSpeed[id]=cvar_val(float,pcvar_base_extra_speed)
		gBaseSpeed[id]=cvar_val(float,pcvar_base_extra_speed);
		UnSet_BitVar(gPlayedSoundMask,id)
		
	}
	else{
		killyandere(id,true)
	}
	
	
}

public get_first_alive(){


for(new i=1;i< sh_maxplayers()+1;i++){
	
	if(!is_user_connected(i)){
		
		
	}
	else if(is_user_alive(i)){
		
		return i;
	}
	
	
}
return -1;


}
public yandere_sentence_loop(id){
	
	if ( !sh_is_active() || sh_is_freezetime() ) return

	for(new i=1;i< sh_maxplayers()+1;i++){
		if(sh_is_active()&&is_user_alive(i)&&sh_user_has_hero(i,gHeroID) &&Get_BitVar(gSuperAngryMask,i)){
			
			
			if(Get_BitVar(gIdleAngryMask,i)||(get_user_health(i)>
						cvar_val(num,pcvar_degen_health_extra_threshold))){
				
				static client_name[128]
				new user_health=get_user_health(i)
				new degen_dmg_2_take= (float(user_health)>yandere_get_psychosis_degen_health_threshold())?
											floatround((float(user_health)-yandere_get_psychosis_degen_health_threshold())*
														degen_iter_period*
														0.01*
														(yandere_get_user_is_psychosis(i)?yandere_get_psychosis_degen_pct():
															cvar_val(float,pcvar_angry_degen_pct)),floatround_ceil)*
														(Get_BitVar(gIdleAngryMask,i)?2:1):0
	
				if(degen_dmg_2_take>0){
					new client_origin[3]
					get_user_origin(i,client_origin)
					new Float:floatalpha=25.0+floatmax(0.0,floatmin(120.0,255.0*(float(user_health)/float(cvar_val(num,pcvar_overheal_hp_max)))))
					sh_screen_fade(i, 0.5, 2.5, LineColors[RED][0], LineColors[RED][1], LineColors[RED][2], floatround(floatalpha))
					
					sh_extra_damage(i,i,degen_dmg_2_take,
									dmg_source_name_short_drain,1,
									_,_,_,_,_,
									SH_NEW_DMG_DRAIN,custom_dmg_id_drain)
					
					fx_bleed(client_origin)
					if(degen_iter_period>1.0){
							get_user_name(i,client_name,127)
							emit_sound(i, CHAN_AUTO, YANDERE_CYCLE, 1.0, 0.0, 0, PITCH_NORM)
							sh_chat_message(0,gHeroID,"%s: %s",client_name,yandere_sentences[generate_int(0,4)])
					}
				}
				
			}
		}
	}
}

notify_yanderes_about_team_life(id=-1,disconnected=0){
if(!sh_is_active()) return
if(!disconnected){
	if(!is_user_connected(id)) return
}
for(new i=1;i< sh_maxplayers()+1;i++){
	if(!is_user_alive(i)) continue;

	if(!sh_user_has_hero(i,gHeroID) ) continue;

	if(!(disconnected)){
		if(!sh_clients_are_same_team(id,i)){
			if((id!=i)){
				continue;
			}
		}
	}
	sh_get_player_counts(i,1,g_mates_alive[i],g_mates_dead[i])
	new bool:can_transform= (get_playersnum(0)>=cvar_val(num,pcvar_min_players))&&(g_mates_alive[i]<=0)
	if(can_transform && !Get_BitVar(gSuperAngryMask,i)){

		Set_BitVar(gTransTimerStartedMask,i)

	}
	else{

		UnSet_BitVar(gTransTimerStartedMask,i)

	}
	
	update_stats(i)
}


}
public yandere_loop(id){
	if ( !sh_is_active() || sh_is_freezetime() ) return

	for(new i=1;i< sh_maxplayers()+1;i++){

		if(!is_user_alive(i)||!sh_user_has_hero(i,gHeroID)){
			continue
		}
		if(!is_user_bot(i)&&Get_BitVar(gTransTimerStartedMask,i)){
			client_print(i,print_center,"All teamates died! Grief will take over in... %0.2fs^n",gTransTimer[i])
		}
		yandere_timer_transform(i)
	}
}


update_stats(id){

	if(!is_user_alive(id)) return
	if(!sh_user_has_hero(id,gHeroID) ) return
	
	new Float:maxspeed=get_user_maxspeed(id)
	
	if(Get_BitVar(gSuperAngryMask,id)){

		gNormalDmgMult[id]=cvar_val(float,pcvar_angry_dmg_mult)
		gNormalSpeed[id]=floatmax(cvar_val(float,pcvar_angry_speed),maxspeed);
		
	}
	else{
		gNormalDmgMult[id]=floatmin(floatadd(cvar_val(float,pcvar_base_dmg_mult),
					floatmul(cvar_val(float,pcvar_dmg_pct_per_inc),
					float(g_mates_dead[id]))),cvar_val(float,pcvar_angry_dmg_mult));
		gNormalSpeed[id]=floatmin(floatadd(gBaseSpeed[id],
				floatmul(cvar_val(float,pcvar_speed_inc_per_inc),float(g_mates_dead[id]))),
				cvar_val(float,pcvar_angry_speed));
	}
}
public yandere_timer_transform(id){
	
	if(Get_BitVar(gSuperAngryMask,id)){

		new Float:gravity=get_user_gravity(id)
		set_user_gravity(id,floatmin(cvar_val(float,pcvar_angry_gravity),gravity))
		if(g_mates_alive[id]>0){

			UnSet_BitVar(gSuperAngryMask,id)
			update_stats(id)
			sh_reset_min_gravity(id)
			set_user_maxspeed(id,gNormalSpeed[id])
			sh_chat_message(0,gHeroID,"Hah... What happened?");
			UnSet_BitVar(gPlayedSoundMask,id)
			if(user_has_weapon(id,YANDERE_WEAPON_CLASSID)){
				sh_drop_weapon(id, YANDERE_WEAPON_CLASSID,true)
			}
			for(new i=0;i<num_yandere_warcries;i++){
				emit_sound(id, CHAN_AUTO, YANDERE_WARCRIES[i], 1.0, 0.0, SND_STOP, PITCH_NORM)
			}
		}
	}
	else{
		UnSet_BitVar(gIdleAngryMask,id)
		if(Get_BitVar(gTransTimerStartedMask,id)){

			gTransTimer[id]-= YANDERE_CYCLE_PERIOD
			if(gTransTimer[id]<=0.0){
				
				Set_BitVar(gSuperAngryMask,id)
				update_stats(id)
				sh_reset_min_gravity(id)
				set_user_maxspeed(id,gNormalSpeed[id])
				if(!Get_BitVar(gPlayedSoundMask,id)){
					static client_name[128]
					get_user_name(id,client_name,127)
					sh_chat_message(0,gHeroID,"%s: Ok. NOW Im mad!",client_name);
					for(new i=0;i<num_yandere_warcries;i++){
						emit_sound(id, CHAN_AUTO, YANDERE_WARCRIES[i], 1.0, 0.0, SND_STOP, PITCH_NORM)
					}
					emit_sound(id, CHAN_AUTO, YANDERE_WARCRIES[generate_int(0,num_yandere_warcries-1)], 1.0, 0.0, 0, PITCH_NORM)
					Set_BitVar(gPlayedSoundMask,id)
				}
				gTransTimer[id]=cvar_val(float,pcvar_trans_time)
			}
		}
		else if(gTransTimer[id]!=cvar_val(float,pcvar_trans_time)){

			gTransTimer[id]=cvar_val(float,pcvar_trans_time)
		}
		if(Get_BitVar(gSuperAngryMask,id)&&is_user_alive(id)){
			UnSet_BitVar(gTransTimerStartedMask,id)
			BlowUp(id)
			jet_destroy(id)
			if(!sh_is_freezetime()){
				if(!user_has_weapon(id,YANDERE_WEAPON_CLASSID)){
					sh_give_weapon(id, YANDERE_WEAPON_CLASSID,true)
				}
			}
		}
	}

}

public client_disconnected(id){

	killyandere(id,true)
	notify_yanderes_about_team_life(-1,1)
}

//----------------------------------------------------------------------------------------------
public plugin_cfg()
{
loadCVARS();
}
//----------------------------------------------------------------------------------------------
public loadCVARS()
{
degen_iter_period=get_cvar_float("yandere_degen_iter_period")


set_task( degen_iter_period, "yandere_sentence_loop", _, _, _, "b")

}
//----------------------------------------------------------------------------------------------
public sh_client_spawn(id)
{	if(is_user_alive(id) && sh_is_active()){
		g_is_cursed_masks[id]=0
		if ( sh_user_has_hero(id,gHeroID) ) {
			
			sh_drop_weapon(id, YANDERE_WEAPON_CLASSID,true)
			yandere_unpsychosis_user(id)
			sh_end_cooldown(id+SH_COOLDOWN_TASKID);
			UnSet_BitVar(gSuperAngryMask,id);
			UnSet_BitVar(gPlayedSoundMask,id);
			gNormalSpeed[id]=gBaseSpeed[id]=cvar_val(float,pcvar_base_extra_speed)
			gTransTimer[id]=cvar_val(float,pcvar_trans_time);
			UnSet_BitVar(gTransTimerStartedMask,id)
			for(new i=0;i<num_yandere_warcries;i++){
				emit_sound(id, CHAN_AUTO, YANDERE_WARCRIES[i], 1.0, 0.0, SND_STOP, PITCH_NORM)
			}
			emit_sound(id, CHAN_AUTO, YANDERE_CYCLE, 1.0, 0.0, SND_STOP, PITCH_NORM)
			emit_sound(id, CHAN_VOICE, YANDERE_PAIN, 1.0, 0.0, SND_STOP, PITCH_NORM)
		}
		notify_yanderes_about_team_life(id)
	}
	
}
public yandere_damage(id)
{
	if ( !sh_is_active() || !is_user_alive(id)) return PLUGIN_CONTINUE
	
	new  damage= read_data(2)
	new weapon, bodypart, attacker = get_user_attacker(id, weapon, bodypart)
	new headshot = (bodypart == 1 ? 1 : 0)
	if ( !is_user_alive(attacker)) return PLUGIN_CONTINUE
	
	if(sh_clients_are_same_team(id,attacker)||(id==attacker)){
		return PLUGIN_CONTINUE
	}
	if ( sh_user_has_hero(attacker,gHeroID) ) {
		new Float:extraDamage =damage * gNormalDmgMult[attacker] - damage
		if (floatround(extraDamage) > 0.0){
			
			if(Get_BitVar(gSuperAngryMask,attacker)&&(weapon==YANDERE_WEAPON_CLASSID)){
				sh_extra_damage(id, attacker, floatround(extraDamage), dmg_source_name_short_senpai_avenger,
								headshot,
								_,_,_,_,_,
								SH_NEW_DMG_DARK_ARTS,
								custom_dmg_id_senpai_avenger)
			}
			else {
				sh_extra_damage(id, attacker, floatround(extraDamage), dmg_source_name_short_rage,
								headshot,
								_,_,_,_,_,
								SH_NEW_DMG_DARK_ARTS,
								custom_dmg_id_rage)
			}
			if(Get_BitVar(gSuperAngryMask,attacker)){
				static attacker_name[128],client_name[128]
				get_user_name(attacker,attacker_name,127)
				get_user_name(id,client_name,127)
				sh_set_stun(id,2.0,default_stun_speed)
			
				generic_heal(heal_hp_hud_msg_sync,attacker,extraDamage*
					cvar_val(float,pcvar_angry_hitheal_pct),
					cvar_val(num,pcvar_overheal_hp_max),RED,1,_,70,1)
				if(!is_user_alive(id)){
					static Float:origin[3];
					// player fades.. 
					set_user_rendering(id, kRenderFxFadeSlow, 255, 255, 255, kRenderTransColor, 4); 
					entity_get_vector(id,EV_VEC_origin,origin)
					anime_kill_fx(origin)
					
				}
				if((weapon==CSW_KNIFE)&&!sh_user_has_hero(id,gHeroID) ){
					
					Set_BitVar(g_is_cursed_masks[id],attacker)
					
					if(!is_user_bot(attacker)){
						sh_chat_message(attacker,gHeroID,"%s has been cursed!",client_name)
					}
				
					if(!is_user_bot(id)){
						sh_chat_message(id,gHeroID,"%s has put a curse on you!",attacker_name)
					}
				
				}
			}
		}	
		
	}
	if( sh_user_has_hero(id,gHeroID)  && is_user_alive(attacker)){
		if(Get_BitVar(g_is_cursed_masks[attacker],id)){
			if(generate_float(0.0,1.0)<cvar_val(float,pcvar_curse_pct)){
				set_user_godmode(id,0)
				sh_extra_damage(attacker,id,1,new_dmg_type_names[_:SH_NEW_DMG_DARK_ARTS],_,SH_DMG_KILL,
							_,_,_,_,
							SH_NEW_DMG_DARK_ARTS,
							get_weapon_id_for_generic_dmg_source(SH_NEW_DMG_DARK_ARTS))
				UnSet_BitVar(g_is_cursed_masks[attacker],id)
			}
		}
	
	
	}
	return PLUGIN_CONTINUE
}
public plugin_precache()
{
	for(new i=0;i<num_yandere_warcries;i++){
		engfunc(EngFunc_PrecacheSound,YANDERE_WARCRIES[i])
	}
	engfunc(EngFunc_PrecacheSound,YANDERE_CYCLE)
	engfunc(EngFunc_PrecacheSound,YANDERE_THELAST)
	engfunc(EngFunc_PrecacheSound,YANDERE_THELAST2)
	engfunc(EngFunc_PrecacheSound,YANDERE_THELAST3)
	engfunc(EngFunc_PrecacheSound,YANDERE_PAIN)
	for(new i=0;i<NUM_YANDERE_PAIN_SOUNDS;i++){
		
		engfunc(EngFunc_PrecacheSound,yandere_pain_sounds[i])
	
	}
	engfunc(EngFunc_PrecacheModel,YANDERE_SHOTGUN_V_MODEL)
	engfunc(EngFunc_PrecacheModel,YANDERE_SHOTGUN_P_MODEL)
	engfunc(EngFunc_PrecacheModel,YANDERE_KNIFE_V_MODEL)
	engfunc(EngFunc_PrecacheModel,YANDERE_KNIFE_P_MODEL)
	engfunc(EngFunc_PrecacheModel,YANDERE_PSYCHO_KNIFE_V_MODEL)
	engfunc(EngFunc_PrecacheModel,YANDERE_PSYCHO_KNIFE_P_MODEL)
	for(new i=0;i<sizeof(yandere_shotgun_sounds);i++){
	
		engfunc(EngFunc_PrecacheSound,yandere_shotgun_sounds[i] );
	
	}
	
	
}

public yandere_kd()
{
	new temp[6]
	
	// First Argument is an id with colussus Powers!
	read_argv(1,temp,5)
	new id=str_to_num(temp)
	
	if ( !is_user_alive(id)||!sh_user_has_hero(id,gHeroID) ) return PLUGIN_HANDLED

	if(Get_BitVar(gSuperAngryMask,id)){
		if ( sh_get_cooldown_flag(id)||yandere_get_user_is_psychosis(id) ) {
			
			if(!is_user_bot(id)){
				playSoundDenySelect(id)
				sh_chat_message(id,gHeroID,"Youve blown a fuse already! Wait a bit more to blow the next one, at least!")
			}
			return PLUGIN_HANDLED
		}
		emit_sound(id, CHAN_AUTO, yandere_pain_sounds[generate_int(0,NUM_YANDERE_PAIN_SOUNDS-1)], 1.0, 0.0, 0, PITCH_NORM)
		new client_name[128]
		get_user_name(id,client_name,127)
		sh_chat_message(0,gHeroID,"%s LOST IT!!!!!",client_name)
		yandere_psychosis_user(id)
	}
	else{
		if(!jet_loaded(id)&&!jet_deployed(id)){

			if(!is_user_bot(id)){
				playSoundDenySelect(id)
				sh_chat_message(id, gHeroID, "The jet is not loaded yet!")
			}
			return PLUGIN_HANDLED
			
		}

		if(jet_deployed(id)){
			
			jet_destroy(id)
			
			if(!is_user_bot(id)){
				sh_chat_message(id, gHeroID, "You J-ed out!!")
			}
			return PLUGIN_HANDLED
			
		}
		jet_charge_user(id)
	
	
	}
	
	return PLUGIN_HANDLED
}
//----------------------------------------------------------------------------------------------
public yandere_ku()
{
	new temp[6]
	
	read_argv(1,temp,5)
	new id=str_to_num(temp)
	
	if ( !is_user_alive(id) ||!sh_user_has_hero(id,gHeroID) ) {
		return PLUGIN_HANDLED
	}
	
	if(!jet_deployed(id)){
		
		jet_uncharge_user(id)
		return PLUGIN_HANDLED
	}
	
	
	return PLUGIN_HANDLED
}
public sh_round_end(){
	
	for(new i=1;i< sh_maxplayers()+1;i++){
		
		if(is_user_alive(i)){
			if(sh_user_has_hero(i,gHeroID) ){
				jet_destroy(i)
				
			}
			
		}
	
	}
	
	remove_entity_name(JETPLANE_BOMB_CLASSNAME)
	remove_entity_name(JETPLANE_SHELL_CLASSNAME)
	remove_entity_name(JETPLANE_ROCKET_CLASSNAME)
	
	new total_alive,total_dead;
	sh_get_player_counts(0,0,total_alive,total_dead)
	
	if(total_alive>1){
		return;
		
	}
	new last_alive=get_first_alive()
	if(!is_user_alive(last_alive)) return
	if(sh_user_has_hero(last_alive,gHeroID) ){
		static client_name[128]
		get_user_name(last_alive,client_name,127)
		sh_chat_message(0,gHeroID,"%s : What... have I done...",client_name)
		
	}
}
public fire_weapon(id)
{
	
	if ( !sh_user_has_hero(id,gHeroID)  ||!is_user_alive(id)||!Get_BitVar(gSuperAngryMask,id)) return PLUGIN_CONTINUE 
	new wpnid = read_data(2)		// id of the weapon 
	new ammo = read_data(3)		// ammo left in clip 
	
	if (gLastWeapon[id] == 0) gLastWeapon[id] = wpnid
	
	if ((gLastClipCount[id] > ammo)&&(gLastWeapon[id] == wpnid)) 
	{
		draw_aim_vector(id,{RED,RED,RED})
		
	}
	gLastClipCount[id] = ammo
	gLastWeapon[id]=wpnid;
	return PLUGIN_CONTINUE 
	
}
killyandere(id,bool:dropping=false){
	
	if(!is_user_connected(id)||!sh_is_active()) return
	if(sh_user_has_hero(id,gHeroID) ||dropping){
		
		if(Get_BitVar(gSuperAngryMask,id)){
			static Float:origin[3]
			entity_get_vector(id,EV_VEC_origin,origin)
			fx_invisible(id)
			anime_kill_fx(origin)
			for(new i=0;i< sh_maxplayers()+1;i++){
				UnSet_BitVar(g_is_cursed_masks[i],id)
			}
			if(yandere_get_user_is_psychosis(id)){
				yandere_unpsychosis_user(id)
			}
		}
		else if(jet_deployed(id)){
			
			jet_destroy(id);
		}
		UnSet_BitVar(gSuperAngryMask,id)
		sh_reset_min_gravity(id)
		
		
	}
	g_is_cursed_masks[id]=0
}
public death()
{	
	new id = read_data(2)
	killyandere(id)
	notify_yanderes_about_team_life(id)
}

//----------------------------------------------------------------------------------------------
public BlowUp(id)
{

	// blowup even if dead
	explosion(gHeroID,id,
		cvar_val(float,pcvar_explode_radius),
		cvar_val(float,pcvar_explode_maxdamage)
		,default_explode_knock_force_magnitude,1)
	
}
//----------------------------------------------------------------------------------------------

public weaponChange(id)
{
	if ( !is_user_alive(id)||!sh_is_active()) return
	if(!sh_user_has_hero(id,gHeroID) ) return

	new  wpnid = get_user_weapon(id)

	if ( g_prevWeapon[id] != wpnid ) {
		if ((get_user_maxspeed(id) < gNormalSpeed[id])&&!sh_get_stun(id)&&sh_is_inround()){
			set_user_maxspeed(id, gNormalSpeed[id])
		}
	}
	g_prevWeapon[id] = wpnid
	
	if (!Get_BitVar(gSuperAngryMask,id)) return
	
	
	if (wpnid == YANDERE_WEAPON_CLASSID) {
		set_pev(id, pev_viewmodel2,YANDERE_SHOTGUN_V_MODEL)
		set_pev(id, pev_weaponmodel2,YANDERE_SHOTGUN_P_MODEL)
	}
	else if (wpnid == CSW_KNIFE) {
		if(yandere_get_user_is_psychosis(id)){
			set_pev(id, pev_viewmodel2,YANDERE_PSYCHO_KNIFE_V_MODEL)
			set_pev(id, pev_weaponmodel2,YANDERE_PSYCHO_KNIFE_P_MODEL)
		}
		else{
		
			set_pev(id, pev_viewmodel2,YANDERE_KNIFE_V_MODEL)
			set_pev(id, pev_weaponmodel2,YANDERE_KNIFE_P_MODEL)
		
		}
	}
}