#define I_WANT_CONSTANTS
#define I_WANT_MISC_FUNCS
#define I_WANT_QUICK_CHECKS
#define I_WANT_CUSTOM_WEAPONS
#include "../my_include/superheromod.inc"
#include "../task_allocator_inc/task_allocator_aux_stuff.inc"
#include "sh_aux_stuff/sh_aux_inc.inc"
#include "../my_include/my_author_header.inc"

#define KOMAK_MISSED_SHOT "shmod/komak/missed_shot.wav"
#define KOMAK_GEAR_UP "shmod/komak/gear_up.wav"
#define KOMAK_BLOWN_ENGINE "shmod/komak/engine_down.wav"
#define KOMAK_FAST_SHOT "shmod/komak/fast_shot.wav"

#define BLOW_ENGINE 0
#define RESET_ON_MISS 1

// GLOBAL VARIABLES
new gHeroID
new const gHeroName[] = "Komak the Maid Mk. II (old)"
new g_komak_hits[SH_MAXSLOTS+1]
new g_komak_gear[SH_MAXSLOTS+1]
new Float:gCurrReloadRatio[SH_MAXSLOTS+1]
new Float:gCurrFireRatio[SH_MAXSLOTS+1]
new bool:gClutchDown[SH_MAXSLOTS+1]
new gEngineRepairTimer[SH_MAXSLOTS+1]

new const redline_color[4]={255,1,1,1}
new const broken_color[4]={10,10,10,0}
new const good_color[4]={1,255,1,0}
new const top_speed_color[4]={1,1,255,1}

#define MAX_GEARS 10
new Float:gear_ratios[MAX_GEARS]

new pcvar_base_reload_ratio
new pcvar_base_fire_ratio
new pcvar_max_reload_ratio
new pcvar_max_fire_ratio
new pcvar_reload_ratio_per_hit
new pcvar_fire_ratio_per_hit
new pcvar_blown_engine_cooldown

new max_gears
new max_rpm
new red_line
new Float:gear_ratio


new hud_sync
//----------------------------------------------------------------------------------------------
public plugin_init()
{
	// Plugin Info
	register_plugin("SUPERHERO Komak the Maid", "1.0", AUTHOR)
	
	
	// DO NOT EDIT THIS FILE TO CHANGE CVARS, USE THE SHCONFIG.CFG
	create_cvar("komak_level", "8")
	create_cvar("komak_max_rpm", "10")
	create_cvar("komak_max_gears", "5")
	create_cvar("komak_red_line", "20")
	create_cvar("komak_gear_ratio", "3")
	
	pcvar_base_reload_ratio = create_cvar("komak_base_reload_ratio", "0.2")
	pcvar_base_fire_ratio = create_cvar("komak_base_fire_ratio", "0.2")
	pcvar_max_reload_ratio = create_cvar("komak_max_reload_ratio", "0.2")
	pcvar_max_fire_ratio = create_cvar("komak_max_fire_ratio", "0.2")
	pcvar_fire_ratio_per_hit = create_cvar("komak_fire_ratio_per_hit", "0.2")
	pcvar_reload_ratio_per_hit = create_cvar("komak_reload_ratio_per_hit", "0.2")
	pcvar_blown_engine_cooldown = create_cvar("komak_blown_engine_cooldown", "30" )
	
	gHeroID=shCreateHero(gHeroName, "Mechanical maid", "Change gears, hit players and hit faster!", true, "komak_level" )
	hud_sync=CreateHudSyncObj()

	RegisterHam(Ham_TraceAttack,"worldspawn","trace_komakerypt2",0,true)
	RegisterHam(Ham_TraceAttack,"player","trace_komakerypt2",0,true)
	
	
	register_ham_for_weapon_bitsum(Ham_Weapon_PrimaryAttack,GUNS_BIT_SUM,"Komak_Fire_Weapon",_, true, false)

	register_ham_for_weapon_bitsum(Ham_Item_PostFrame,single_shot_wpns_bs,"Item_PostFrame_Post",1, true, false)

	set_task(1.0, "engine_repair_loop",_,_,_, "b")
}


public Item_PostFrame_Post(iEnt)
{    
	if(pev_valid(iEnt) != 2){
		return HAM_IGNORED
	}
	new id = entity_get_edict(iEnt, EV_ENT_owner);
	
	if(!is_user_alive(id)){
		
		return HAM_IGNORED
	}
	if (!sh_is_active()||!sh_get_user_has_hero(id,gHeroID) )return HAM_IGNORED
	do_fast_reload(id,iEnt,gCurrReloadRatio[id])
	return HAM_IGNORED
} 
//----------------------------------------------------------------------------------------------
public sh_hero_init(id, heroID, sh_init_mode:mode){
	if(heroID!=gHeroID) return

	reset_komak(id)
	
	
}

public komak_is_top_speed(id){

	return !((gCurrFireRatio[id]<cvar_val(float, pcvar_max_fire_ratio))||
			(gCurrReloadRatio[id]<cvar_val(float, pcvar_max_reload_ratio)))
}
public Komak_Fire_Weapon(entity)
{

	if(pev_valid(entity)!=2)
		return HAM_IGNORED


	new id = get_pdata_cbase(entity, m_pPlayer, XO_WEAPON)
	
	if(!client_is_hero_user(id, gHeroID)){
		return HAM_IGNORED
	}

	return do_fast_shot(entity,gCurrFireRatio[id])

}
public trace_komakerypt2(this, idattacker, Float:damage, Float:direction[3], traceresult, damagebits)
{
	if(damage<=0.0){
		return HAM_IGNORED
	}

	new return_result=HAM_IGNORED;
	new client_is_hittable_here=is_user_alive(this)
	if(client_is_hittable_here){
		if(sh_get_user_has_hero(this,gHeroID) ){

			new hitgroup=get_tr2(traceresult,TR_iHitgroup);
			switch(hitgroup){
				case HIT_RIGHTARM:{
					set_tr2(traceresult,TR_iHitgroup,HIT_SHIELD);
					SetHamParamTraceResult(5,traceresult)
					return_result=HAM_IGNORED
				}
			}

		}
	}
	
	if( !sh_is_active() ||!is_user_alive(idattacker)||!sh_get_user_has_hero(idattacker,gHeroID) ){
		
		return return_result;
	
	}
	
	static blown_engine_cooldown;
	blown_engine_cooldown = cvar_val(num, pcvar_blown_engine_cooldown)
	
	if(client_is_hittable_here && !gClutchDown[idattacker])
	{
		if(sh_clients_are_same_team(this,idattacker)){

			return return_result;
		}
		if(g_komak_hits[idattacker]>red_line){
		
			emit_sound(idattacker,CHAN_ITEM,  KOMAK_FAST_SHOT, 1.0, ATTN_NORM, 0, komak_pitch(idattacker))
		
		}
		
		if(!komak_is_top_speed(idattacker)){
			g_komak_hits[idattacker]=min(g_komak_hits[idattacker]+1, max_rpm);
		}
		if((g_komak_hits[idattacker]>=max_rpm)&&BLOW_ENGINE){
		
			reset_komak(idattacker)
			ultimateTimer(idattacker, blown_engine_cooldown * 1.0)
			gEngineRepairTimer[idattacker]=blown_engine_cooldown
			sh_chat_message(idattacker,gHeroID,"Blown engine!!!!")
			emit_sound(idattacker,CHAN_ITEM,  KOMAK_BLOWN_ENGINE, 1.0, ATTN_NORM, 0, PITCH_NORM)
		
			
		}
	}
	else if(!gClutchDown[idattacker]&&RESET_ON_MISS){

		if(!komak_is_top_speed(idattacker)){
			emit_sound(idattacker,CHAN_ITEM,  KOMAK_MISSED_SHOT, 1.0, ATTN_NORM, 0, PITCH_NORM)
			g_komak_hits[idattacker]=max(0,g_komak_hits[idattacker]-1);
			if(!g_komak_hits[idattacker]){
				komak_gear_change(idattacker,false)
			}
		}
		
	}
	stats_komak(idattacker)
	return return_result;
	
}
public engine_repair_loop(id){
	if ( !sh_is_active() || sh_is_freezetime() ) return

	for(new i=1;i< sh_maxplayers()+1;i++){
		if(!is_user_alive(i)){
			continue
		}
		if(sh_get_user_has_hero(i,gHeroID)){
		
			if((gEngineRepairTimer[i]>0)){
				
				gEngineRepairTimer[i]--;
				
				
			}
			if(!is_user_bot(i)){
				komak_hud(i)
			}
		}
	}
	
	
}
komak_hud(id){
	static hud_msg[128];
	formatex(hud_msg,127,"[SH] %s:^nGear: %d|%d^nCurr rpm: %d|%d^nCurrent fire ration: %0.2f^nCurrent reload ration: %0.2f^nEngine broken? %s^n",
					gHeroName,
					g_komak_gear[id],
					max_gears,
					g_komak_hits[id],
					max_rpm,
					gCurrFireRatio[id],
					gCurrReloadRatio[id],
					gEngineRepairTimer[id]>0? "Yeah...":"Nope... ALL ready!"
					);
	
	if(gEngineRepairTimer[id]>0){
		set_hudmessage(broken_color[0], broken_color[1], broken_color[2], 1.0, 0.2, broken_color[3], 0.0, 1.0,0.0,0.0)
	}
	else if(komak_is_top_speed(id)){
		set_hudmessage(top_speed_color[0], top_speed_color[1], top_speed_color[2], 1.0, 0.2, top_speed_color[3], 0.0, 1.0,0.0,0.0)
	}
	else if(g_komak_hits[id]>red_line){
		set_hudmessage(redline_color[0], redline_color[1], redline_color[2], 1.0, 0.2, redline_color[3], 0.0, 1.0,0.0,0.0)
	}
	else{
		set_hudmessage(good_color[0], good_color[1], good_color[2], 1.0, 0.2, good_color[3], 0.0, 1.0,0.0,0.0)
	}
	ShowSyncHudMsg(id, hud_sync, "%s", hud_msg)



}
//----------------------------------------------------------------------------------------------
public plugin_cfg()
{
	loadCVARS();
	gear_ratios[0]=1.0
	for(new i=1;i<=max_gears;i++){
		gear_ratios[i]=floatmul(gear_ratios[i-1],gear_ratio)
	
	
	}
}
//----------------------------------------------------------------------------------------------
public loadCVARS()
{	

	max_rpm = get_cvar_num("komak_max_rpm")
	red_line = get_cvar_num("komak_red_line")
	gear_ratio = get_cvar_float("komak_gear_ratio")
	max_gears = get_cvar_num("komak_max_gears")
	max_gears = min(max_gears,MAX_GEARS)
}
public reset_komak(id){

	if ( sh_get_user_has_hero(id,gHeroID) ) {
		g_komak_hits[id]=0;
		g_komak_gear[id]=1;
		gCurrFireRatio[id]=cvar_val(float,pcvar_base_fire_ratio);
		gCurrReloadRatio[id]=cvar_val(float,pcvar_base_reload_ratio);
	}

}
Float:get_max_added_fire_ratio(id){

	
	return floatmin(cvar_val(float, pcvar_max_fire_ratio),
				floatmul(floatmul(gear_ratios[clamp(0,g_komak_gear[id]-1)],
						float(max_rpm)),
						cvar_val(float, pcvar_fire_ratio_per_hit)))
	

}
Float:get_max_added_reload_ratio(id){

	
	return floatmin(
		cvar_val(float, pcvar_max_reload_ratio),
		floatmul(floatmul(gear_ratios[clamp(0,g_komak_gear[id]-1)],
		float(max_rpm)),
		cvar_val(float, pcvar_reload_ratio_per_hit)))
	

}
Float:get_added_fire_ratio(id){

	
	new Float:float_hits=float(g_komak_hits[id])
	
	return floatmul(float_hits*gear_ratios[clamp(0,g_komak_gear[id]-1)],
		cvar_val(float, pcvar_fire_ratio_per_hit))
	

}
Float:get_added_reload_ratio(id){

	new Float:float_hits=float(g_komak_hits[id])

	return floatmul(float_hits*gear_ratios[clamp(0,g_komak_gear[id]-1)],
		cvar_val(float, pcvar_reload_ratio_per_hit))
	

}
stats_komak(id){
	gCurrFireRatio[id]=floatadd(
				cvar_val(float, pcvar_base_fire_ratio),floatmin(get_max_added_fire_ratio(id),get_added_fire_ratio(id)))
	gCurrReloadRatio[id]=floatadd(
				cvar_val(float, pcvar_base_reload_ratio),floatmin(get_max_added_reload_ratio(id),get_added_reload_ratio(id)))
}

public komak_gear_change(id,is_up){
	
	new increment= is_up?1:-1
	new the_gear=max(1,min(g_komak_gear[id]+increment,max_gears))
	new new_hits
	if(!is_up){
		if(g_komak_gear[id]>1){
			new_hits=red_line
		
		}
		else{
			new_hits=0
		}
	
	}
	else{
		new_hits=min(max_rpm,floatround(float(g_komak_hits[id])*(gear_ratios[g_komak_gear[id]]/gear_ratios[the_gear])))
	
	}
	g_komak_hits[id]=new_hits
	g_komak_gear[id]=the_gear
	
}

//----------------------------------------------------------------------------------------------
public sh_hero_key(id, heroID, sh_key_mode:key)
{
if ( gHeroID != heroID ||!sh_get_user_has_hero(id,gHeroID) ) return

switch(key)
{
	case SH_KEYDOWN: {
		komak_kd(id)
	}
	
	case SH_KEYUP: {
		
		komak_ku(id)
	}
}
}
public komak_kd(id)
{
	if ( !sh_is_active()||!is_user_alive(id)||!sh_get_user_has_hero(id,gHeroID) ||(g_komak_gear[id]==max_gears)) return PLUGIN_HANDLED
	

	if ( sh_get_cooldown_flag(id)) {
		sh_chat_message(id,gHeroID,"Youve blown the engine! Wait %d more seconds!",gEngineRepairTimer[id])
		playSoundDenySelect(id)
		return PLUGIN_HANDLED
	}
	gClutchDown[id]=true;
	
	return PLUGIN_HANDLED
}
public komak_pitch(id){

	return floatround(float(g_komak_hits[id])/float(max_rpm)*float(150))

}
public komak_ku(id)
{
	
	if ( !sh_is_active()||!is_user_alive(id)||!sh_get_user_has_hero(id,gHeroID) ||!gClutchDown[id]) return PLUGIN_HANDLED
	
	gClutchDown[id]=false
	if(g_komak_hits[id]<red_line){
		
		playSoundDenySelect(id)
		return PLUGIN_HANDLED
	
	}
	emit_sound(id,CHAN_WEAPON,  KOMAK_GEAR_UP, 1.0, ATTN_NORM, 0, PITCH_NORM)
	komak_gear_change(id,true)
	
	return PLUGIN_HANDLED
}


public sh_extra_damage_fwd_pre(&victim, &attacker, &damage, &my_hitpoint_enum:bodypart,&sh_damage_mode:dmgMode, &sh_extra_damage_flags:sh_extra_dmg_flags, const Float:dmgOrigin[3],&dmg_type,&sh_thrash_brat_dmg_type:new_dmg_type, custom_weapon_id){
	if ( !sh_is_active() ||  !is_user_connected(victim)||!is_user_connected(attacker)){
	
		return DMG_FWD_PASS
	}
	if(sh_get_user_has_hero(victim,gHeroID) ){
		if(sh_clients_are_same_team(victim,attacker)){
			return DMG_FWD_PASS
		
		}
		switch(bodypart){
			case MY_HIT_RIGHTARM:{
				bodypart=MY_HIT_SHIELD
				damage=0
			}
		}

	}
	return DMG_FWD_PASS
}
	
//----------------------------------------------------------------------------------------------
public sh_client_spawn(id)
{	
if(is_user_alive(id) && sh_is_active()&&sh_get_user_has_hero(id,gHeroID) ){ 
	reset_komak(id)	
}
}
public plugin_precache()
{
engfunc(EngFunc_PrecacheSound, KOMAK_MISSED_SHOT)
engfunc(EngFunc_PrecacheSound, KOMAK_FAST_SHOT)
engfunc(EngFunc_PrecacheSound, KOMAK_BLOWN_ENGINE)
engfunc(EngFunc_PrecacheSound, KOMAK_GEAR_UP)
		
}