// SCARLET SPIDER!

/* CVARS - copy and paste to amxx.cfg

//Scarlet Spider
scarlet_level 6
scarlet_wallspeed 250.0				//speed he climbs

*/

#include <amxmodx>
#include <fakemeta>
#include <superheromod>

new g_heroID
new pcvar_level
new bool:g_hasScarlet[SH_MAXSLOTS+1]
new bool:g_canClimb[SH_MAXSLOTS+1]
//----------------------------------------------------------------------------------------------
public plugin_init() 
{
	// Plugin Info
	register_plugin("SUPERHERO Scarlet Spider","1.0","-=cKy=- <Killer>")
	
	// DO NOT EDIT THIS FILE TO CHANGE CVARS, USE THE AMXX.CFG
	pcvar_level=register_cvar("scarlet_level", "6")
	register_cvar("scarlet_wallspeed", "250.0")
	
	// FIRE THE EVENT TO CREATE THIS SUPERHERO!
	g_heroID = sh_create_hero("Scarlet Spider", pcvar_level);
	sh_set_hero_info(g_heroID, "Walk up walls", "Press the bound key and run into a wall to climb up it!")
	sh_set_hero_bind(g_heroID)
}
//----------------------------------------------------------------------------------------------
public sh_hero_init(id, heroID, mode)
{
	if ( g_heroID == heroID )
	{
		g_hasScarlet[id] = (mode != 0)
		g_canClimb[id]=false
	}
}
//----------------------------------------------------------------------------------------------
public wall_walk(id) 
{
	if ( is_user_alive(id) && g_hasScarlet[id] && g_canClimb[id]) {
		
		new Float:velocity[3]
		pev(id, pev_velocity, velocity)
		if ( (pev(id, pev_button)&IN_FORWARD) && (velocity[0]==0.0 || velocity[1]==0.0) ) 
		{
			velocity[2]=get_cvar_float("scarlet_wallspeed")
			set_pev(id, pev_velocity, velocity)
		}
	}
}
//----------------------------------------------------------------------------------------------
// RESPOND TO KEYDOWN
public sh_hero_key(id, heroID, key)
{
	if ( g_heroID != heroID ) return PLUGIN_HANDLED
	if ( !is_user_alive(id) || !g_hasScarlet[id] ) return PLUGIN_HANDLED

	if ( key == SH_KEYDOWN )
	{
		if ( !g_canClimb[id] ) {
			g_canClimb[id]=true
			set_task(0.1, "wall_walk", id, "", 0, "b")
			set_hudmessage(20, 255, 20, -1.0, 0.25, 0, 1.0, 1.2, 0.4, 0.4)
			show_hudmessage(id, "You can now walk up walls!")
			return PLUGIN_HANDLED
		}

		g_canClimb[id]=false
		remove_task(id)
		set_hudmessage(20, 255, 20, -1.0, 0.25, 0, 1.0, 1.2, 0.4, 0.4)
		show_hudmessage(id, "You got rid of your ability to walk up walls")
		return PLUGIN_HANDLED
	}
	return PLUGIN_HANDLED
}
//----------------------------------------------------------------------------------------------
public client_disconnected(id) 
{
	remove_task(id)
}
//----------------------------------------------------------------------------------------------
public sh_new_spawn(id) 
{
	g_canClimb[id]=false
}
//----------------------------------------------------------------------------------------------
/* AMXX-Studio Notes - DO NOT MODIFY BELOW HERE
*{\\ rtf1\\ ansi\\ deff0{\\ fonttbl{\\ f0\\ fnil Tahoma;}}\n\\ viewkind4\\ uc1\\ pard\\ lang10266\\ f0\\ fs16 \n\\ par }
*/
