

#include "../my_include/superheromod.inc"
#include "./superheromod_help_files_includes/superheromod_help_files.inc"
#include "sh_aux_stuff/sh_aux_inc.inc"
#include "sh_aux_stuff/sh_aux_inc_pt2.inc"
#include "ksun_inc/ksun_global.inc"
#include "chikoi_inc/sh_chikoi_funcs.inc"
#define CHIKOI_HITZONE_TASKID 19999

#define CHIKOI_THE_MAID_PHYSICAL_PROPERTY "Smallness"
// GLOBAL VARIABLES
new gHeroID
new const gHeroName[] = "Chikoi the Maid"
new bool:gHasChikoi[SH_MAXSLOTS+1]


//----------------------------------------------------------------------------------------------
public plugin_init()
{
	// Plugin Info
	register_plugin("SUPERHERO Chikoi the Maid", "1.0", "TastyMedula")
	
	
	// DO NOT EDIT THIS FILE TO CHANGE CVARS, USE THE SHCONFIG.CFG
	register_cvar("chikoi_level", "8")
	register_event("ResetHUD","newRound","b")
	gHeroID=shCreateHero(gHeroName, "Small maid!", "Become headshot only! But it really is headshot only! 1Shot 1Kill!", false, "chikoi_level" )
	new hero_name_arr[STRLEN_FOR_NAMES];
	arrayset(hero_name_arr,0,sizeof hero_name_arr)
	add(hero_name_arr,charsmax(hero_name_arr),gHeroName,charsmax(gHeroName))
	superheromod_help_link_hero(gHeroID, "Chikoi the maid: Help file","chikoi_the_maid_folder/","chikoi_help_file.html",hero_name_arr)
	register_event("Damage", "chikoi_damage", "b", "2!0")
	RegisterHam(Ham_TraceAttack,"player","chikoi_physical_body",_,true)
	register_srvcmd("chikoi_init", "chikoi_init")
	shRegHeroInit(gHeroName, "chikoi_init")
	
	
}

public plugin_natives(){
	
	register_native("chikoi_has_chikoi","_chikoi_has_chikoi",0);
}
public _chikoi_has_chikoi(iPlugin,iParams){

	new id=get_param(1)
	if(!client_hittable(id)){

		return 0
	}
	return gHasChikoi[id]
}
public chikoi_init()
{
	
	// First Argument is an id
	new temp[6]
	read_argv(1,temp,5)
	new id=str_to_num(temp)
	
	read_argv(2,temp,5)
	new hasPowers = str_to_num(temp)
	gHasChikoi[id]=(hasPowers!=0)
	
	
	
}
stock dmg_message(id, attacker){
	new attacker_name[128];
	new client_name[128];
	get_user_name(attacker,attacker_name,127);
	get_user_name(id,client_name,127);
	sh_chat_message(0,gHeroID,"%s has killed Chikoi the Maid (%s), the Small Maid, at your service.",attacker_name,client_name)

}
public chikoi_damage(id){
if ( !shModActive() || !is_user_alive(id) ||!gHasChikoi[id]) return PLUGIN_CONTINUE


new weapon, bodypart, attacker = get_user_attacker(id, weapon, bodypart)
new headshot = bodypart == HIT_STOMACH ? 1 : 0
if ( attacker <= 0 || attacker > SH_MAXSLOTS || attacker==id ) return PLUGIN_CONTINUE
new attacker_name[128];
new client_name[128];
get_user_name(attacker,attacker_name,127);
get_user_name(id,client_name,127);

if(headshot){

	
	sh_extra_damage(id, attacker, 1, CHIKOI_THE_MAID_PHYSICAL_PROPERTY, headshot,SH_DMG_KILL)
	dmg_message(id, attacker)
}
if(weapon==CSW_HEGRENADE){

	return PLUGIN_HANDLED
}
return PLUGIN_CONTINUE

}

public chikoi_physical_body(id, attacker, Float:damage, Float:direction[3], tracehandle, damagebits){

	if(!client_hittable(id)){

		return HAM_IGNORED;

	}
	if(!gHasChikoi[id]){

		return HAM_IGNORED;

	}
	if(sh_clients_are_same_team(id,attacker)){

		return HAM_IGNORED
	}
	new hitgroup=get_tr2(tracehandle,TR_iHitgroup);
	switch(hitgroup){
		case HIT_STOMACH:{
			set_tr2(tracehandle,TR_iHitgroup,HIT_HEAD);
			SetHamParamTraceResult(5,tracehandle)
		}
		case HIT_HEAD:{

			
			if(!spores_has_ksun(id)){
				return HAM_SUPERCEDE
			}
		}
		case HIT_CHEST:{

			
			if(!spores_has_ksun(id)){
				return HAM_SUPERCEDE
			}
		}
		default:{
			return HAM_SUPERCEDE
		}
	}
	return HAM_HANDLED;
}
//----------------------------------------------------------------------------------------------
public plugin_cfg()
{
	loadCVARS();
	
}
//----------------------------------------------------------------------------------------------
public loadCVARS()
{
}
public reset_chikoi(id){

	if ( gHasChikoi[id]) {
		
		if(!is_user_bot(id)){
			sh_chat_message(id,gHeroID,"Hello player! I am Chikoi the maid, The Small Maid, at your service.")
		}
	}

}
//----------------------------------------------------------------------------------------------
public newRound(id)
{	
if(is_user_alive(id) && shModActive()&&gHasChikoi[id]){ 
	reset_chikoi(id)	
}
return PLUGIN_HANDLED	
}

public sh_extra_damage_fwd_pre(&victim, &attacker, &damage,wpnDescription[32],  &headshot,&dmgMode, &bool:dmgStun, &bool:dmgFFmsg, const Float:dmgOrigin[3],&dmg_type,&sh_thrash_brat_dmg_type:new_dmg_type){
	
	if ( !sh_is_active() ||  !is_user_connected(victim)||!is_user_connected(attacker)){
	
		return DMG_FWD_PASS
	}
	if(gHasChikoi[victim]){
		if((cs_get_user_team(victim)==cs_get_user_team(attacker))){
			if(victim!=attacker){
			
				return DMG_FWD_PASS
			}
		
		}
		if(headshot){
			
			arrayset(wpnDescription,0,sizeof wpnDescription)
			copy(wpnDescription, strlen(CHIKOI_THE_MAID_PHYSICAL_PROPERTY),CHIKOI_THE_MAID_PHYSICAL_PROPERTY)
			damage=get_user_health(victim)+1;
			dmgMode=SH_DMG_KILL
			new_dmg_type=SH_NEW_DMG_SQUASHED
			dmg_message(victim, attacker)
			return DMG_FWD_PASS
		}
		else {
			return DMG_FWD_BLOCK
		}
	}
	return DMG_FWD_PASS
}
