/********************************************
***** REQUIRES MODIFIED DRACULA TO WORK *****
****** included in Required Files zip *******
******** AMX Mod X 1.75 and up ONLY *********
********************************************/

// BLADE! from Marvel Comics and the Movie series. "Daywalker" the half vampire half human that hunts vampires.

/* CVARS - copy and paste to shconfig.cfg

//Blade
blade_level 5
blade_speed 350		//How fast he runs with knife, usp, or mac10 (Default 350)
blade_knifeburns 8	//Amount of burns from a knife attack, set to -1 for continuous burn (Default 8)
blade_knifeburndmg 5	//Amount of damage per burn from knife burn (Default 5)
blade_gunburns 5 	//Amount of burns from a usp/mac10 attack (Default 5)
blade_gunburndmg 3	//Amount of damage per burn from gun burn (Default 3)

*/

/*
* v1.1 - vittu - 5/3/06
*      - Cleaned up and recoded.
*      - Modified Dracula so Blade can actually work, included with download. (sh_dracula v1.18m)
*      - Changed glock to mac10 (since that's what he uses), with optional model. 
*      - Changed damage to be determined by number of burns.
*      - Changed scream sound.
*      - Fixed and changed speed to work with knife, usp, and mac10.
*      - Removed knife damage multiplier against non-dracula's.
*
*   Hero Created by TreDizzle and AssKicR (Burn code based on Human Torch)
*   Optional MAC10 weapon model reskinned by RCCSTEBB with DSFCHOOT's help (orginal by Ghost Ops Team, Strykerwolf, and Edisleado)
*/

//---------- User Changeable Defines --------//



// Note: If you change anything from default setting you must recompile the plugin

// Unlimited ammo
// 0 = no reload, 1 = drop weapon, 3 = disable unlimited ammo [Default 3]
#define AMMO_MODE 3


// 0 = don't give free weapons, 1 = give free mac10 and usp(if T) [Default 0]
#define GIVE_WEAPONS 1



#define I_WANT_QUICK_CHECKS
#define I_WANT_CONSTANTS
#include "../my_include/superheromod.inc"
#include "../my_heroes/sh_aux_stuff/sh_aux_inc.inc"
#include "../my_heroes/sh_aux_stuff/sh_aux_stuff_natives_pt5.inc"
#include "../my_heroes/sh_aux_stuff/sh_aux_stuff_natives_pt11.inc"


// GLOBAL VARIABLES
new HeroName[] = "Blade"
new gBladeeMac10Model[STRING_SIZE] = "models/shmod/blade_v_mac10.mdl";


new dmg_source_name_short_gunburn[SAFE_BUFFER_SIZE+1]="gunburn"
new dmg_source_name_log_gunburn[SAFE_BUFFER_SIZE+1]="gunburn"
new custom_dmg_id_gunburn

new gHeroID
new bool:InKnifeBurn[SH_MAXSLOTS+1]
new bool:InGunBurn[SH_MAXSLOTS+1]
new SpriteSmoke, SpriteFire
new CvarKnifeDmg, CvarKnifeBurns, CvarGunDmg, CvarGunBurns
//----------------------------------------------------------------------------------------------
public plugin_init()
{
	// Plugin Info
	register_plugin("SUPERHERO Blade", "1.1", "TreDizzle/AssKicR/vittu")

	// DO NOT EDIT THIS FILE TO CHANGE CVARS, USE THE SHCONFIG.CFG
	create_cvar("blade_level", "5")
	create_cvar("blade_speed", "350")
	CvarKnifeBurns = create_cvar("blade_knifeburns", "8")
	CvarKnifeDmg = create_cvar("blade_knifeburndmg", "5")
	CvarGunBurns = create_cvar("blade_gunburns", "5")
	CvarGunDmg = create_cvar("blade_gunburndmg", "3")

	// FIRE THE EVENT TO CREATE THIS SUPERHERO!
	gHeroID=shCreateHero(HeroName, "Silver Knife & Bullets", "Burn Vampires with your KNIFE or Deal Extra Burning Damage with your MAC10 or USP", false, "blade_level")


	sh_register_superheromod_weapon_model(gHeroID,CSW_MAC10,gBladeeMac10Model)

	custom_dmg_id_gunburn=sh_log_custom_damage_source(gHeroID,dmg_source_name_short_gunburn,
				dmg_source_name_log_gunburn,
				0)

	RegisterHam(Ham_TraceAttack,"player","blade_damage",_,true)

	// Let Server know about the hero's varibles
	shSetShieldRestrict(HeroName)
	shSetMaxSpeed(HeroName, "blade_speed", "[7][16][29]")	
}
//----------------------------------------------------------------------------------------------
public plugin_precache()
{
	SpriteSmoke = engfunc(EngFunc_PrecacheModel,"sprites/steam1.spr")
	SpriteFire = engfunc(EngFunc_PrecacheModel,"sprites/xfire.spr")
	engfunc(EngFunc_PrecacheSound,"ambience/burning1.wav")
	engfunc(EngFunc_PrecacheSound,"controller/con_die2.wav")

}
//----------------------------------------------------------------------------------------------
public sh_hero_init(id, heroID, sh_init_mode:mode){
	if  (heroID!=gHeroID) return

	if(sh_get_user_has_hero(id,gHeroID))
	{

		if ( is_user_alive(id) )
		{
			#if GIVE_WEAPONS == 1
				blade_weapons(id)
			#endif

		}
	}
	else{
		// Check is needed since this gets run on clearpowers even if user didn't have this hero
		if ( is_user_alive(id) )
		{
			#if GIVE_WEAPONS == 1
				if ( cs_get_user_team(id) == CS_TEAM_T ){
					sh_drop_weapon(id, CSW_USP)
				}

				sh_drop_weapon(id, CSW_MAC10)
			#endif
		}
	}
}
//----------------------------------------------------------------------------------------------
public sh_client_spawn(id)
{
	blade_reset(id)

#if GIVE_WEAPONS == 1
	if ( sh_is_active() && is_user_alive(id) && sh_get_user_has_hero(id,gHeroID) )
		set_task(0.1, "blade_weapons", id)
}
//----------------------------------------------------------------------------------------------
public blade_weapons(id)
{
	if ( !sh_is_active() || !is_user_alive(id) || !sh_get_user_has_hero(id,gHeroID) )
		return

	if ( cs_get_user_team(id) == CS_TEAM_T ){
		sh_give_weapon(id, CSW_USP)
	}

	sh_give_weapon(id, CSW_MAC10)

#endif
}
//----------------------------------------------------------------------------------------------
public weapon_change(id)
{
	if ( !sh_is_active() || !sh_get_user_has_hero(id,gHeroID) )
		return

	new wpnid = read_data(2)

	if ( wpnid != CSW_MAC10 )
		return


#if AMMO_MODE < 3
	new clip = read_data(3)

	// Never Run Out of Ammo!
	if ( clip == 0 )
		sh_reload_ammo(id, AMMO_MODE)
#endif
}
burndmgfunc(id, attacker, my_hitpoint_enum:the_hitpoint, Float:damage){

	new Float:extraDamage = damage * 2.0- damage
	if (floatround(extraDamage)>0){
		sh_extra_damage(id,attacker,floatround(extraDamage),
					the_hitpoint,
					_,_,_,_,
					SH_NEW_DMG_FIRE,
					custom_dmg_id_gunburn)

	}
}
public blade_damage(id, attacker, Float:damage, Float:direction[3], traceresult, damagebits)
{	
	if(damage<=0.0){
		return HAM_IGNORED
	}
	
	if( !sh_is_active() || !is_user_alive(id) || !is_user_connected(id)|| !sh_get_player_has_hero_prop(id, SH_BLEED_POWERS)) return HAM_IGNORED;
	if ( (attacker==id)||!is_user_connected(attacker)||!sh_get_user_has_hero(attacker,gHeroID) ) return HAM_IGNORED
	
	new weapon = get_user_weapon(attacker)
	
	new my_hitpoint_enum:the_hitpoint= my_hitpoint_enum:get_tr2(traceresult,TR_Hitgroup)

	switch(weapon)
		{
			case CSW_KNIFE:
			{
				// Make sure user is not already in a knifeburn
				if ( InKnifeBurn[id] ){
					return HAM_IGNORED;
				}

				set_knifeburn(id, attacker)
				burndmgfunc(id, attacker, the_hitpoint, damage)
			}

			case CSW_MAC10, CSW_USP:
			{
				// Make sure user is not already in a gunburn
				if ( InGunBurn[id] ){
					return HAM_IGNORED;
				}


				set_gunburn(id, attacker)
				burndmgfunc(id, attacker, the_hitpoint, damage)
			}
		}
			

	return HAM_IGNORED;
}
//----------------------------------------------------------------------------------------------
// Keep public for hero Longshot to call this
public set_knifeburn(id, attacker)
{
	if ( !sh_is_active() || !is_user_alive(id) || InKnifeBurn[id] )
		return

	// Extra checks for use with hero Longshot
	if ( !sh_get_user_has_hero(attacker,gHeroID) || !sh_get_player_has_hero_prop(id, SH_BLEED_POWERS))
		return

	new knifeBurns = get_pcvar_num(CvarKnifeBurns)

	switch(knifeBurns)
	{
		case -1:
		{
			InKnifeBurn[id] = true

			new args[2]
			args[0] = id
			args[1] = attacker

			set_task(0.3, "knifeburn", id, args, 2, "b")
		}

		case 0:
			return

		default:
		{
			InKnifeBurn[id] = true

			new args[2]
			args[0] = id
			args[1] = attacker

			new Float:burnStopTime = knifeBurns * 0.3 + 0.6
			set_task(0.3, "knifeburn", id, args, 2, "a", knifeBurns)
			set_task(burnStopTime, "stop_knifeburn", id)	
		}
	}

	// If already burning no need to set sound again
	if ( !InGunBurn[id] )
		emit_sound(id, CHAN_STATIC, "ambience/burning1.wav", 1.0, ATTN_NORM, 0, PITCH_NORM)

	vampire_scream(id)
}
//----------------------------------------------------------------------------------------------
public knifeburn(args[])
{
	new id = args[0]
	new attacker = args[1]

	if ( !sh_is_active() || !is_user_alive(id) )
	{
		blade_reset(id)
		return
	}

	if ( InKnifeBurn[id] )
	{
		burn_effect(id)

		new knifeDmg = get_pcvar_num(CvarKnifeDmg)
		new hpAfterDmg = get_user_health(id) - knifeDmg

		// Prevents the sh_extra_damage from saying you attacked a teammate for every cycle of the loop
		if ( hpAfterDmg <= 0 )
			sh_extra_damage(id, attacker, knifeDmg,
					_,_,_,_,_,
					SH_NEW_DMG_FIRE,
					custom_dmg_id_gunburn)
		else
			set_user_health(id, hpAfterDmg)
	}
}
//----------------------------------------------------------------------------------------------
set_gunburn(id, attacker)
{
	if ( !sh_is_active() || !is_user_alive(id) || InGunBurn[id] )
		return

	new gunBurns = get_pcvar_num(CvarGunBurns)

	if ( gunBurns <= 0 )
		return

	InGunBurn[id] = true

	new args[2]
	args[0] = id
	args[1] = attacker

	new Float:burnStopTime = gunBurns * 0.3 + 0.6
	set_task(0.3, "gunburn", id, args, 2, "a", gunBurns)
	set_task(burnStopTime, "stop_gunburn", id)

	// If already burning no need to set sound again
	if ( !InKnifeBurn[id] )
		emit_sound(id, CHAN_STATIC, "ambience/burning1.wav", 1.0, ATTN_NORM, 0, PITCH_NORM)

	vampire_scream(id)
}
//----------------------------------------------------------------------------------------------
public gunburn(args[])
{
	new id = args[0]
	new attacker = args[1]

	if ( !sh_is_active() || !is_user_alive(id) )
	{
		blade_reset(id)
		return
	}

	if ( InGunBurn[id] )
	{
		burn_effect(id)

		new gunDmg = get_pcvar_num(CvarGunDmg)
		new hpAfterDmg = get_user_health(id) - gunDmg

		// Prevents the sh_extra_damage from saying you attacked a teammate for every cycle of the loop
		if ( hpAfterDmg <= 0 )
			sh_extra_damage(id, attacker, gunDmg,
					_,_,_,_,_,
					SH_NEW_DMG_FIRE,
					custom_dmg_id_gunburn)
		else
			set_user_health(id, hpAfterDmg)
	}
}
//----------------------------------------------------------------------------------------------
burn_effect(id)
{
	if ( !is_user_connected(id) )
		return

	new rx, ry, rz, forigin[3]

	rx = generate_int(-30, 30)
	ry = generate_int(-30, 30)
	rz = generate_int(-30, 30)

	get_user_origin(id, forigin)

	//TE_SPRITE - additive sprite, plays 1 cycle
	message_begin(MSG_PVS, SVC_TEMPENTITY, forigin)
	write_byte(17)
	write_coord(forigin[0]+rx)	// coord, coord, coord (position)
	write_coord(forigin[1]+ry)
	write_coord(forigin[2]+10+rz)
	write_short(SpriteFire)	// short (sprite index)
	write_byte(30)		// byte (scale in 0.1's)
	write_byte(200)		// byte (brightness)
	message_end()

	//Smoke
	message_begin(MSG_PVS, SVC_TEMPENTITY, forigin)
	write_byte(5)
	write_coord(forigin[0]+(rx*2))	// coord, coord, coord (position)
	write_coord(forigin[1]+(ry*2))
	write_coord(forigin[2]+100+(rz*2))
	write_short(SpriteSmoke)	// short (sprite index)
	write_byte(60)			// byte (scale in 0.1's)
	write_byte(15)			// byte (framerate)
	message_end()
}
//----------------------------------------------------------------------------------------------
vampire_scream(id)
{
	if ( is_user_connected(id) )
		emit_sound(id, CHAN_AUTO, "controller/con_die2.wav", 1.0, ATTN_NORM, 0, PITCH_HIGH)
}
//----------------------------------------------------------------------------------------------
public stop_knifeburn(id)
{
	// Check and seperate function prevents removing the burning sound if still in other burn type
	if ( !InGunBurn[id] && is_user_connected(id) )
		emit_sound(id, CHAN_STATIC, "ambience/burning1.wav", 1.0, ATTN_NORM, SND_STOP, PITCH_NORM)

	InKnifeBurn[id] = false
}
//----------------------------------------------------------------------------------------------
public stop_gunburn(id)
{
	// Check and seperate function prevents removing the burning sound if still in other burn type
	if ( !InKnifeBurn[id] && is_user_connected(id) )
		emit_sound(id, CHAN_STATIC, "ambience/burning1.wav", 1.0, ATTN_NORM, SND_STOP, PITCH_NORM)

	InGunBurn[id] = false
}
//----------------------------------------------------------------------------------------------
blade_reset(id)
{
	remove_task(id)

	if ( InKnifeBurn[id] )
		stop_knifeburn(id)

	if ( InGunBurn[id] )
		stop_gunburn(id)
}
//----------------------------------------------------------------------------------------------
public client_connect(id)
{
	blade_reset(id)
}
//----------------------------------------------------------------------------------------------