 //CloneTrooper

 //Credits go to Vittu for Master Chief�s Morphing Code and Teh Creators of Cyclops
 
 /* CVARS - copy and paste to shconfig.cfg

 //CTrooper
 CTrooper_level 10
 CTrooper_ak47mult 2.0            //Damage multiplyer for his Ak47
 CTrooper_health 150        //Default 150
 CTrooper_armor 150        //Default 150
 CTrooper_teamcolored 1    //Default 1,

 //Version 1.0 - Added hero and Added Player and Gun Model (First Created
 //Version 1.1 - Added Laser shots to gun to add more Realism to the Star Wars factor
 //Version 1.2 - Re-Coded and Compiled for AMXX to work again...(Permissiobn or Om3gA
 //Version 1.3 - Re-Coded and addet Laser bullets
 //Version 2.0 - Re-Codet and addet Laser bullets that work
 //Version 2.1 - Ad-Codes he works with the laser and gives you a free AK_47
 //Version 2.2 - Ad-Codes addet unlimited bullets
 //Version 2.3 - Ad-Codes/mdl addet a p mdl and he spawns with an AK_47 when you re-spawn
 //Version 2.4 - Ad-Codes Addet a new mdl and teamcolored lasers thx to JTP
 //version 2.5 - Cleand up the code
 //Version 2.6 - Fixed teh Laser Tracer So now Teh Laser Is Where Ya Shoot Removed Xtra Speed And Gravity And made a CZ Version
 //Version 2.7 - Fix for SND_STOP compile error
 */

#include "../my_include/superheromod.inc"
#include "../my_heroes/sh_aux_stuff/sh_aux_inc.inc"
#include "../my_heroes/sh_aux_stuff/sh_aux_stuff_natives_pt1.inc"
#include "../my_heroes/sh_aux_stuff/sh_aux_stuff_natives_pt5.inc"
#include "../my_include/my_author_header.inc"

// GLOBAL VARIABLES
new gHeroName[]="Clone Trooper"
new lastammo[33]
new gHeroID
 //----------------------------------------------------------------------------------------------
 public plugin_init()
 {
	my_authored_register_func("SUPERHERO Clone Trooper","2.7","Om3gA",true,AUTHOR)

	// DO NOT EDIT THIS FILE TO CHANGE CVARS, USE THE SHCONFIG.CFG
	register_cvar("ctrooper_level", "0")
	register_cvar("ctrooper_ak47mult", "2.0")
	register_cvar("ctrooper_health", "150")
	register_cvar("ctrooper_armor", "150")
	// FIRE THE EVENT TO CREATE THIS SUPERHERO!
	gHeroID=shCreateHero(gHeroName, "CTrooper", "Become a Clone Trooper! - Cooler Player Model and Gun and laser bullets", false, "CTrooper_level" )
	sh_register_superheromod_model(gHeroID,
								"models/player/clonetrooper/clonetrooper.mdl",
								"models/player/clonetrooper/clonetrooper.mdl",
								"clonetrooper",
								"CTrooper - Prepared for war..SIR!",
								"CTrooper - All systems down...")
	// REGISTER EVENTS THIS HERO WILL RESPOND TO! (AND SERVER COMMANDS)

	// INIT
	register_srvcmd("CTrooper_init", "CTrooper_init")
	shRegHeroInit(gHeroName, "CTrooper_init")
	register_event("CurWeapon", "make_tracer", "be", "1=1", "3>0")
	register_event("CurWeapon", "weaponChange", "be", "1=1")
	register_event("ResetHUD", "newSpawn", "b")
	register_event("Damage", "CTrooper_damage", "b", "2!0")
	
	// Let Server know about Master Chief's Variables
	shSetShieldRestrict(gHeroName)
	shSetMaxHealth(gHeroName, "ctrooper_health")
	shSetMaxArmor(gHeroName, "ctrooper_armor")
	init_hud_syncs()
 }
 //----------------------------------------------------------------------------------------------
 public plugin_precache()
 {
	engfunc(EngFunc_PrecacheSound,"weapons/electro5.wav")
	engfunc(EngFunc_PrecacheModel,"models/shmod/clonetrooper_v_ak47.mdl")
	engfunc(EngFunc_PrecacheModel,"models/shmod/clonetrooper_p_ak47.mdl")
 }
 //----------------------------------------------------------------------------------------------
 public CTrooper_init()
 {
	// First Argument is an id
	new temp[6]
	read_argv(1,temp,5)
	new id = str_to_num(temp)

	//Reset thier shield restrict status
	//Shield restrict MUST be before weapons are given out
	shResetShield(id)

	if ( is_user_connected(id) ) {
		if (sh_user_has_hero(id,gHeroID) ) {
			CTrooper_weapons(id)
			switchmodel(id)
		}
		else {
			engclient_cmd(id, "drop", "weapon_ak47")
			shRemHealthPower(id)
			shRemArmorPower(id)
			shRemGravityPower(id)
			shRemSpeedPower(id)
		}
	}
 }
 //----------------------------------------------------------------------------------------------
 public make_tracer(id)
 {
	if(!client_hittable(id)) return PLUGIN_CONTINUE
	if (!sh_user_has_hero(id,gHeroID)) return PLUGIN_CONTINUE
	new clip, ammo
	new wpnid = get_user_weapon(id, clip, ammo)
	new CsTeams:user_team=cs_get_user_team(id)

	if ((lastammo[id] > clip) && (wpnid == CSW_AK47) ) {

		new vec1[3], vec2[3]
		new Float:fvec1[3], Float:fvec2[3]
		get_user_origin(id, vec1, 1) // origin; your camera point.
		get_user_origin(id, vec2, 3) // termina; where your bullet goes (4 is cs-only)

		IVecFVec(vec1,fvec1)
		IVecFVec(vec2,fvec2)

		laser_line(id,fvec1,fvec2,false,{RED,GREEN,GREEN},_,true)
		aura(id,LineColors[((user_team==CS_TEAM_CT)?GREEN:RED)])
	}

	lastammo[id] = clip

	return PLUGIN_CONTINUE
 }
 //----------------------------------------------------------------------------------------------
 public newSpawn(id)
 {
	if ( sh_user_has_hero(id,gHeroID)&& is_user_alive(id) && shModActive() ) {
		set_task(0.1, "CTrooper_weapons", id)

		new clip, ammo, wpnid = get_user_weapon(id,clip,ammo)
		if (wpnid != CSW_AK47 && wpnid > 0) {
			new wpn[32]
			get_weaponname(wpnid,wpn,31)
			engclient_cmd(id,wpn)
		}
	}
 }
 //----------------------------------------------------------------------------------------------
 public switchmodel(id)
 {
	if ( !is_user_alive(id) || !sh_user_has_hero(id,gHeroID) ) return

	new clip, ammo, wpnid = get_user_weapon(id, clip, ammo)

	if (wpnid == CSW_AK47) {

		Entvars_Set_String(id, EV_SZ_viewmodel, "models/shmod/clonetrooper_v_ak47.mdl")
		// Weapon Model change for 3rd person view - vittu
		Entvars_Set_String(id, EV_SZ_weaponmodel, "models/shmod/clonetrooper_p_ak47.mdl")
	}
 }
 //----------------------------------------------------------------------------------------------
 public weaponChange(id)
 {
	if ( !sh_user_has_hero(id,gHeroID)|| !shModActive() ) return

	new wpnid = read_data(2)
	new clip = read_data(3)

	if ( wpnid != CSW_AK47 ) return

	switchmodel(id)

	// Never Run Out of Ammo!
	if ( clip == 0 ) {
		shReloadAmmo(id)
	}
 }
 //----------------------------------------------------------------------------------------------
 public CTrooper_weapons(id)
 {
	if ( is_user_alive(id) ) {
		shGiveWeapon(id,"weapon_ak47")
	}
 }
 //----------------------------------------------------------------------------------------------
 public CTrooper_damage(id)
 {
	if (!shModActive() || !is_user_alive(id)) return

	new damage = read_data(2)
	new weapon, bodypart, attacker = get_user_attacker(id, weapon, bodypart)
	new headshot = bodypart == 1 ? 1 : 0

	if ( attacker <= 0 || attacker > SH_MAXSLOTS||attacker == id ) return
//sh_user_has_hero(id,gHeroID)
	if ( sh_user_has_hero(attacker,gHeroID)&& weapon == CSW_AK47 && is_user_alive(id) ) {
		if ( sh_user_has_hero(attacker,gHeroID) && is_user_alive(id) ) {
			// do extra damage
			new extraDamage = floatround(damage * get_cvar_float("ctrooper_ak47mult") - damage)
			if (extraDamage > 0) sh_extra_damage( id, attacker, extraDamage, "ak47", headshot )
		}
	}
 }
/* AMXX-Studio Notes - DO NOT MODIFY BELOW HERE
*{\\ rtf1\\ ansi\\ deff0{\\ fonttbl{\\ f0\\ fnil Tahoma;}}\n\\ viewkind4\\ uc1\\ pard\\ lang1030\\ f0\\ fs16 \n\\ par }
*/
