 //CloneTrooper

 //Credits go to Vittu for Master Chief�s Morphing Code and Teh Creators of Cyclops
 
 /* CVARS - copy and paste to shconfig.cfg

 //CTrooper
 CTrooper_level 10
 CTrooper_ak47mult 2.0            //Damage multiplyer for his Ak47
 CTrooper_health 150        //Default 150
 CTrooper_armor 150        //Default 150
 CTrooper_teamcolored 1    //Default 1,

 //Version 1.0 - Added hero and Added Player and Gun Model (First Created
 //Version 1.1 - Added Laser shots to gun to add more Realism to the Star Wars factor
 //Version 1.2 - Re-Coded and Compiled for AMXX to work again...(Permissiobn or Om3gA
 //Version 1.3 - Re-Coded and addet Laser bullets
 //Version 2.0 - Re-Codet and addet Laser bullets that work
 //Version 2.1 - Ad-Codes he works with the laser and gives you a free AK_47
 //Version 2.2 - Ad-Codes addet unlimited bullets
 //Version 2.3 - Ad-Codes/mdl addet a p mdl and he spawns with an AK_47 when you re-spawn
 //Version 2.4 - Ad-Codes Addet a new mdl and teamcolored lasers thx to JTP
 //version 2.5 - Cleand up the code
 //Version 2.6 - Fixed teh Laser Tracer So now Teh Laser Is Where Ya Shoot Removed Xtra Speed And Gravity And made a CZ Version
 //Version 2.7 - Fix for SND_STOP compile error
 */
#define I_WANT_CONSTANTS
#define I_WANT_MISC_FUNCS
#include "../my_include/superheromod.inc"
#include "../my_heroes/sh_aux_stuff/sh_aux_inc.inc"
#include "../my_heroes/sh_aux_stuff/sh_aux_stuff_natives_pt1.inc"
#include "../my_heroes/sh_aux_stuff/sh_aux_funcs_misc_pt2.inc"
#include "../my_heroes/sh_aux_stuff/sh_aux_stuff_natives_pt5.inc"
#include "../my_include/my_author_header.inc"

#define CTROOPER_LASERGUN_CLASSID CSW_AK47 
// GLOBAL VARIABLES
new gHeroName[]="Clone Trooper"
new gHeroID

new dmg_source_name_short_lazah_guun[SAFE_BUFFER_SIZE+1]="lazah_guun"
new dmg_source_name_log_lazah_guun[SAFE_BUFFER_SIZE+1]="lazah_guun"
new custom_dmg_id_lazah_guun

new pcvar_extra_lazadmg
 //----------------------------------------------------------------------------------------------
 public plugin_init()
 {
	my_authored_register_func("SUPERHERO Clone Trooper","2.7","Om3gA",true,AUTHOR)

	// DO NOT EDIT THIS FILE TO CHANGE CVARS, USE THE SHCONFIG.CFG
	register_cvar("ctrooper_level", "0")
	pcvar_extra_lazadmg = register_cvar("ctrooper_ak47mult", "2.0")
	register_cvar("ctrooper_health", "150")
	register_cvar("ctrooper_armor", "150")
	// FIRE THE EVENT TO CREATE THIS SUPERHERO!
	gHeroID=shCreateHero(gHeroName, "CTrooper", "Become a Clone Trooper! - Cooler Player Model and Gun and laser bullets", false, "CTrooper_level" )
	sh_register_superheromod_model(gHeroID,
								"models/player/clonetrooper/clonetrooper.mdl",
								"models/player/clonetrooper/clonetrooper.mdl",
								"clonetrooper",
								"CTrooper - Prepared for war..SIR!",
								"CTrooper - All systems down...")
	sh_register_superheromod_weapon_model(gHeroID,CTROOPER_LASERGUN_CLASSID,"models/shmod/clonetrooper_v_ak47.mdl","models/shmod/clonetrooper_p_ak47.mdl")
	
	register_ham_hook_multiple(Ham_TraceAttack,
							full_entity_array_for_trace_attack,
							length_of_trace_attack_entity_array,
							"ctrooper_laser_gun",
							1,
							true)
	
	custom_dmg_id_lazah_guun=sh_log_custom_damage_source(gHeroID,
					dmg_source_name_short_lazah_guun,
					dmg_source_name_log_lazah_guun,0)

	register_event("CurWeapon", "weaponChange", "be", "1=1")
	register_event("Damage", "CTrooper_damage", "b", "2!0")
	
	// Let Server know about Master Chief's Variables
	shSetShieldRestrict(gHeroName)
	shSetMaxHealth(gHeroName, "ctrooper_health")
	shSetMaxArmor(gHeroName, "ctrooper_armor")
 }
//----------------------------------------------------------------------------------------------
public sh_hero_init(id, heroID, mode){
	if  (heroID!=gHeroID) return
	

	if ( is_user_connected(id) ) {
		if (sh_user_has_hero(id,gHeroID) ) {
			CTrooper_weapons(id)
		}
		else {
			sh_drop_weapon(id, CTROOPER_LASERGUN_CLASSID)
		}
	}
 }
 //----------------------------------------------------------------------------------------------
 public ctrooper_laser_gun(Victim, Attacker, Float:Damage, Float:Direction[3], Ptr, DamageBits)
 {
	new bool:the_result=generic_weapon_tracer_logic(Attacker,_,CTROOPER_LASERGUN_CLASSID,gHeroID,true,sh_custom_color:{RED,GREEN,GREEN})
	

	if(the_result){
		emit_sound(Attacker,CHAN_BODY,LASER_LINE_DEFAULT_SOUND,VOL_NORM,ATTN_NORM,0,PITCH_NORM)
		aura(Attacker,LineColors[((cs_get_user_team(Attacker)==CS_TEAM_CT)?GREEN:RED)])
	}
 }
 //----------------------------------------------------------------------------------------------
 public sh_client_spawn(id)
 {
	if ( sh_user_has_hero(id,gHeroID)&& is_user_alive(id) && sh_is_active() ) {
		set_task(0.1, "CTrooper_weapons", id)

		new clip, ammo, wpnid = get_user_weapon(id,clip,ammo)
		if (wpnid != CTROOPER_LASERGUN_CLASSID && wpnid > 0) {
			new wpn[32]
			get_weaponname(wpnid,wpn,31)
			engclient_cmd(id,wpn)
		}
	}
 }
 //----------------------------------------------------------------------------------------------
 public weaponChange(id)
 {
	if ( !sh_user_has_hero(id,gHeroID)|| !sh_is_active() ) return

	new wpnid = read_data(2)
	new clip = read_data(3)

	if ( wpnid != CTROOPER_LASERGUN_CLASSID ) return

	// Never Run Out of Ammo!
	if ( clip == 0 ) {
		sh_reload_ammo(id)
	}
 }
 //----------------------------------------------------------------------------------------------
 public CTrooper_weapons(id)
 {
	if ( is_user_alive(id) ) {
		sh_give_weapon(id,CTROOPER_LASERGUN_CLASSID)
	}
 }
 //----------------------------------------------------------------------------------------------
 public CTrooper_damage(id)
 {
	if (!sh_is_active() || !is_user_alive(id)) return

	new damage = read_data(2)
	new weapon, bodypart, attacker = get_user_attacker(id, weapon, bodypart)

	if ( attacker <= 0 || attacker > SH_MAXSLOTS||attacker == id ) return
//sh_user_has_hero(id,gHeroID)
	new bool:has_hero= sh_user_has_hero(attacker,gHeroID)
	if ( has_hero && weapon == CTROOPER_LASERGUN_CLASSID && is_user_alive(id) ) {
		new extraDamage = floatround(damage * cvar_val(float, pcvar_extra_lazadmg) - damage)
		
		if (extraDamage > 0){
			sh_extra_damage(id, attacker, extraDamage, 
					dmg_source_name_log_lazah_guun,
					my_hitpoint_enum:bodypart,
					_,_,_,_,
					SH_NEW_DMG_ENERGY_BLAST,
					custom_dmg_id_lazah_guun)
		}
	}
 }
/* AMXX-Studio Notes - DO NOT MODIFY BELOW HERE
*{\\ rtf1\\ ansi\\ deff0{\\ fonttbl{\\ f0\\ fnil Tahoma;}}\n\\ viewkind4\\ uc1\\ pard\\ lang1030\\ f0\\ fs16 \n\\ par }
*/
