// GOKU! - from Dragon Ball, Z, GT series.

/* CVARS - copy and paste to shconfig.cfg

//Goku
goku_level 10
goku_aps 5			//The amount of AP gained per second (Default 5)
goku_apl 250			//AP amount multiplied by ssjlevel = AP required for each ssjlevel and cost of ssjlevel power use (Default 250)
goku_hpl 30			//HP amount multiplied by ssjlevel, ex. 30*ssj2 = +60HP (Default 30)
goku_hpmax 500			//Max HP that can be gained (Default 500)
goku_speedbase 300		//Initial Speed boost for ssjlevel 1, only sets if you are slower (Default 300)
goku_speedadd 25		//Speed added to goku_speedbase every next ssjlevel (Default 25)
goku_damage1 70		//Max Damage for ssjlevel 1 power (Default 70)
goku_damage2 100		//Max Damage for ssjlevel 2 power (Default 100)
goku_damage3 175		//Max Damage for ssjlevel 3 power (Default 175)
goku_damage4 300		//Max Damage for ssjlevel 4 power (Default 300)
goku_radius1 100		//Max Radius of Damage for ssjlevel 1 power (Default 100)
goku_radius2 300		//Max Radius of Damage for ssjlevel 2 power (Default 300)
goku_radius3 700		//Max Radius of Damage for ssjlevel 3 power (Default 700)
goku_radius4 1500		//Max Radius of Damage for ssjlevel 4 power (Default 1500)
goku_blast_decals 1		//Show the burn decals on the walls (0-no 1-yes)

*/

/*
* v1.5 - vittu - 11/24/05
*      - Fixed crash to AMX since it can't register a MSG_ONE_UNRELIABLE message.
*
* v1.4 - vittu - 10/24/05
*      - Cleaned/Changed up code and formatted sounds to smaller file size for release.
*      - Consolodated cvars and global variables so less are declared. Instead
*          of individual settings, multipliers of one cvar are now used. Left 
*          damage and radius cvars of powers for more customization.
*
* v1.3 - vittu - 9/10/05
*      - Added guided kamehameha.
*
* v1.2 - vittu - 5/29/05
*      - Added Health and Speed boost to Saiyan level.
*      - Increased time of powerup effect.
*
* v1.1 - vittu - 5/26/05
*      - Recoded from scratch but kept basic premise.
*      - Created entities for power instead of beams.
*
*   Hero concept and originally by |RIC|_ALBANIAN.
*   Entity creation partially based on Bazooka, which is based on Missiles Launcher 3.8.2 by Eric Lidman & jtp10181.
*
*   ***Warning: This hero contains many extra files and may cause problems if you are precaching too much.***
*
*   Extra sprites and sounds used from Earth's Special Forces a HL mod - http://www.esforces.com/
*     and some sounds from http://www.esf-world.com/
*/
#define I_WANT_CONSTANTS
#define I_WANT_QUICK_CHECKS
#define I_WANT_MISC_FUNCS
#include "../my_include/superheromod.inc"
#include "../my_heroes/sh_aux_stuff/sh_aux_inc.inc"
#include "../my_heroes/sh_aux_stuff/sh_aux_stuff_natives_pt1.inc"
#include "../my_heroes/sh_aux_stuff/sh_aux_stuff_natives_pt2.inc"
#include "../my_heroes/sh_aux_stuff/sh_aux_stuff_natives_pt3.inc"
#include "../my_include/my_author_header.inc"

// GLOBAL VARIBLES
new g_heroName[]="Goku"
new bool:g_inStun[SH_MAXSLOTS+1]
new g_isSaiyanLevel[SH_MAXSLOTS+1]
new g_powerNum[SH_MAXSLOTS+1]
new g_powerID[SH_MAXSLOTS+1]
new g_maxRadius[SH_MAXSLOTS+1]
new g_maxDamage[SH_MAXSLOTS+1]
new g_lastWeapon[SH_MAXSLOTS+1]
new g_prevWeapon[SH_MAXSLOTS+1]
new bool:g_weaponSwitched[SH_MAXSLOTS+1]
new g_ssjLevel[4]
new Float:g_ssjSpeed[4]
stock goku_hud_sync

new g_armorPts, g_spriteSmoke, g_spriteTrailY, g_spriteTrailB, g_spriteTrailR
new g_spriteExplosionY, g_spriteExplosionB, g_spriteExplosionR, g_spritePowerUp
new gHeroID


new goku_dmgs_arr[5][sh_extra_damage_struct] = {
	{"", "", -1},
	{"goku_ki_blast", "goku_ki_blast", -1},
	{"goku_kamehameha", "goku_kamehameha", -1},
	{"goku_super_kamehameha", "goku_super_kamehameha", -1},
	{"spirit_bomb", "spirit_bomb", -1}

}


new pcvar_aps,
	pcvar_apl,
	pcvar_hpl,
	pcvar_hpmax,
	pcvar_speedbase,
	pcvar_speedadd,
	pcvar_damage1,
	pcvar_damage2,
	pcvar_damage3,
	pcvar_damage4,
	pcvar_radius1,
	pcvar_radius2,
	pcvar_radius3,
	pcvar_radius4,
	pcvar_decals,
	pcvar_powerup_explode_radius_ssj4

//----------------------------------------------------------------------------------------------
public plugin_init()
{
	my_authored_register_func("SUPERHERO Goku","1.5","RIC|_ALBANIAN / 0 / vittu",true,AUTHOR)

	// DO NOT EDIT THIS FILE TO CHANGE CVARS, USE THE SHCONFIG.CFG
	register_cvar("goku_level", "10")
	pcvar_aps = register_cvar("goku_aps", "5")
	pcvar_apl = register_cvar("goku_apl", "250")
	pcvar_hpl = register_cvar("goku_hpl", "30")
	pcvar_hpmax = register_cvar("goku_hpmax", "500")
	pcvar_speedbase = register_cvar("goku_speedbase", "300")
	pcvar_speedadd = register_cvar("goku_speedadd", "25")
	pcvar_damage1 = register_cvar("goku_damage1", "50")
	pcvar_damage2 = register_cvar("goku_damage2", "80")
	pcvar_damage3 = register_cvar("goku_damage3", "150")
	pcvar_damage4 = register_cvar("goku_damage4", "300")
	pcvar_radius1 = register_cvar("goku_radius1", "100")
	pcvar_radius2 = register_cvar("goku_radius2", "300")
	pcvar_radius3 = register_cvar("goku_radius3", "700")
	pcvar_radius4 = register_cvar("goku_radius4", "1500")
	pcvar_decals = register_cvar("goku_blast_decals", "1")
	pcvar_powerup_explode_radius_ssj4 = register_cvar("goku_powerup_explode_radius_ssj4", "300")

	// FIRE THE EVENT TO CREATE THIS SUPERHERO!
	gHeroID=shCreateHero(g_heroName, "Super Saiyan Powers", "Generate KI/Armor to transform into Super Saiyan forms. Get a Special Power plus an HP/Speed boost for each SSJ Level.", true, "goku_level")


	for(new i=1;i<sizeof goku_dmgs_arr;i++){

		goku_dmgs_arr[i][the_wpn_id] = sh_log_custom_damage_source(gHeroID,
				goku_dmgs_arr[i][short_dmg_name],
				goku_dmgs_arr[i][long_dmg_name],
				0)
	}

	register_entity_as_wall_touchable("vexd_goku_power","goku_power_touch")
	register_custom_touchable("vexd_goku_power","goku_power_touch",player_vector,1)

	register_event("CurWeapon", "curweapon", "be", "1=1")


	goku_hud_sync=CreateHudSyncObj()
	// LOOP
	set_task(1.0, "goku_loop", 0, "", 0, "b")
	init_explosion_defaults()
}
//----------------------------------------------------------------------------------------------
public plugin_precache()
{
	engfunc(EngFunc_PrecacheSound,"shmod/goku_ki_blast.wav")
	engfunc(EngFunc_PrecacheSound,"shmod/goku_kamehameha.wav")
	engfunc(EngFunc_PrecacheSound,"shmod/goku_10x_kamehameha.wav")
	engfunc(EngFunc_PrecacheSound,"shmod/goku_spirit_bomb.wav")
	engfunc(EngFunc_PrecacheSound,"shmod/goku_powerup1.wav")
	engfunc(EngFunc_PrecacheSound,"shmod/goku_powerup2.wav")
	engfunc(EngFunc_PrecacheSound,"shmod/goku_powerup3.wav")
	engfunc(EngFunc_PrecacheSound,"shmod/goku_powerup4.wav")
	engfunc(EngFunc_PrecacheSound,"player/pl_pain2.wav")
	engfunc(EngFunc_PrecacheModel,"sprites/shmod/esf_ki_blast.spr")
	engfunc(EngFunc_PrecacheModel,"sprites/shmod/esf_kamehameha_blue.spr")
	engfunc(EngFunc_PrecacheModel,"sprites/shmod/esf_kamehameha_red.spr")
	engfunc(EngFunc_PrecacheModel,"sprites/shmod/esf_spirit_bomb.spr")
	g_spriteTrailY = engfunc(EngFunc_PrecacheModel,"sprites/shmod/esf_trail_yellow.spr")
	g_spriteTrailB = engfunc(EngFunc_PrecacheModel,"sprites/shmod/esf_trail_blue.spr")
	g_spriteTrailR = engfunc(EngFunc_PrecacheModel,"sprites/shmod/esf_trail_red.spr")
	g_spriteExplosionY = engfunc(EngFunc_PrecacheModel,"sprites/shmod/esf_exp_yellow.spr")
	g_spriteExplosionB = engfunc(EngFunc_PrecacheModel,"sprites/shmod/esf_exp_blue.spr")
	g_spriteExplosionR = engfunc(EngFunc_PrecacheModel,"sprites/shmod/esf_exp_red.spr")
	g_spritePowerUp = engfunc(EngFunc_PrecacheModel,"sprites/shmod/esf_powerup.spr")
	g_spriteSmoke = engfunc(EngFunc_PrecacheModel,"sprites/wall_puff4.spr")
}
//----------------------------------------------------------------------------------------------
public sh_hero_init(id, heroID, mode){
	if(heroID!=gHeroID) return
	
	if ( sh_user_has_hero(id,gHeroID)) {
		goku_setarmor(id)
	}
	//This gets run if they had the power but don't anymore
	else {
		// remove the power if it was used and user dropped hero
		if ( g_powerID[id] > 0 ) {
			remove_power(id, g_powerID[id])
		}
	}

}
//----------------------------------------------------------------------------------------------
public plugin_cfg()
{
	loadCVARS()
}
//----------------------------------------------------------------------------------------------
public loadCVARS()
{
	// These cvars are checked very often
	g_armorPts = cvar_val(num,pcvar_aps)
	g_ssjLevel[0] = cvar_val(num,pcvar_apl)
	g_ssjLevel[1] = g_ssjLevel[0] * 2
	g_ssjLevel[2] = g_ssjLevel[0] * 3
	g_ssjLevel[3] = g_ssjLevel[0] * 4
	g_ssjSpeed[0] = cvar_val(float,pcvar_speedbase)
	g_ssjSpeed[1] = g_ssjSpeed[0] + cvar_val(float,pcvar_speedadd)
	g_ssjSpeed[2] = g_ssjSpeed[1] + cvar_val(float,pcvar_speedadd)
	g_ssjSpeed[3] = g_ssjSpeed[2] + cvar_val(float,pcvar_speedadd)
}
//----------------------------------------------------------------------------------------------
public sh_client_spawn(id)
{
	g_inStun[id] = false

	if ( sh_is_active() && sh_user_has_hero(id,gHeroID) && is_user_alive(id) ) {
		// Set armor in x seconds to avoid breaking max ap settings in other heroes
		set_task(0.5, "goku_setarmor", id)
		g_isSaiyanLevel[id] = 0
	}
}
//----------------------------------------------------------------------------------------------
public goku_setarmor(id)
{
	if ( is_user_alive(id) ) {
		// Start a Goku off with 100 AP, even if user has more from other heroes
		give_item(id, "item_assaultsuit")
		set_user_armor(id, 100)
	}
}

//----------------------------------------------------------------------------------------------
public sh_hero_key(id, heroID, key)
{
if ( gHeroID != heroID ||!sh_user_has_hero(id,gHeroID) ) return

switch(key)
{
	case SH_KEYDOWN: {
		goku_kd(id)
	}
	
	case SH_KEYUP: {
		
		goku_ku(id)
	}
}
}
//----------------------------------------------------------------------------------------------
// RESPOND TO KEYDOWN
public goku_kd(id)
{
	if (!sh_is_inround()) return

	if ( !is_user_alive(id) || !sh_user_has_hero(id,gHeroID) ) return

	// Reload CVARS to make sure the variables are current
	loadCVARS()

	new userArmor = get_user_armor(id)

	if ( userArmor < g_ssjLevel[0] ) {
		playSoundDenySelect(id)
		client_print(id, print_chat, "[SH](Goku) Not enough KI/Armor")
		return
	}

	// Prevent too many entities, which would cause server problems
	if( g_powerID[id] ){
		playSoundDenySelect(id)
		client_print(id,print_chat,"[SH](Goku) You cannot use more than one power at a time.")
		return
	}

	// Remember this weapon...
	new clip, ammo, weaponID = get_user_weapon(id, clip, ammo)
	g_lastWeapon[id] = weaponID
	g_weaponSwitched[id] = true

	// Switch to knife
	engclient_cmd(id, "weapon_knife")

	if ( userArmor >= g_ssjLevel[0] && userArmor < g_ssjLevel[1] ) {
		client_print(id,print_chat,"[SH](Goku) Ki Blast!")
		emit_sound(id, CHAN_STATIC, "shmod/goku_ki_blast.wav", 0.8, ATTN_NORM, 0, PITCH_NORM)
		set_user_armor(id, userArmor-g_ssjLevel[0])
		g_maxDamage[id] = cvar_val(num,pcvar_damage1)
		g_maxRadius[id] = cvar_val(num,pcvar_radius1)
		g_powerNum[id] = 1
	}
	else if ( userArmor >= g_ssjLevel[1] && userArmor < g_ssjLevel[2] ) {
		client_print(id,print_chat,"[SH](Goku) Kamehameha!!")
		// Wish this sound was shorter
		emit_sound(id, CHAN_STATIC, "shmod/goku_kamehameha.wav", 0.8, ATTN_NORM, 0, PITCH_NORM)
		set_user_armor(id, userArmor-g_ssjLevel[1])
		g_maxDamage[id] = cvar_val(num,pcvar_damage2)
		g_maxRadius[id] = cvar_val(num,pcvar_radius2)
		g_powerNum[id] = 2
	}
	else if ( userArmor >= g_ssjLevel[2] && userArmor < g_ssjLevel[3] ) {
		client_print(id,print_chat,"[SH](Goku) 10x Kamehameha!!!")
		// Wish this sound was shorter
		emit_sound(id, CHAN_STATIC, "shmod/goku_10x_kamehameha.wav", 0.8, ATTN_NORM, 0, PITCH_NORM)
		set_user_armor(id, userArmor-g_ssjLevel[2])
		g_maxDamage[id] = cvar_val(num,pcvar_damage3)
		g_maxRadius[id] = cvar_val(num,pcvar_radius3)
		g_powerNum[id] = 3
	}
	else if ( userArmor >= g_ssjLevel[3] ) {

		client_print(id,print_chat,"[SH](Goku) Spirit Bomb!!!!")
		emit_sound(id, CHAN_STATIC, "shmod/goku_spirit_bomb.wav", 0.8, ATTN_NORM, 0, PITCH_NORM)
		set_user_armor(id, userArmor-g_ssjLevel[3])
		g_maxDamage[id] = cvar_val(num,pcvar_damage4)
		g_maxRadius[id] = cvar_val(num,pcvar_radius4)
		g_powerNum[id] = 4
	}

	create_power(id)
}
//----------------------------------------------------------------------------------------------
public goku_ku(id)
{
	if ( !sh_is_inround() ) return

	if ( !is_user_alive(id) || !sh_user_has_hero(id,gHeroID)|| !g_weaponSwitched[id] ) return

	// Switch back to previous weapon... Only if power was used...
	if (g_lastWeapon[id] != CSW_KNIFE) shSwitchWeaponID(id, g_lastWeapon[id])
	g_weaponSwitched[id] = false
}
//----------------------------------------------------------------------------------------------
public create_power(id)
{
	new Float:vOrigin[3], Float:vAngles[3], Float:vAngle[3], entModel[40]
	new Float:entScale, Float:entSpeed, trailModel, trailLength, trailWidth
	new Float:VecMins[3] = {-1.0,-1.0,-1.0}
	new Float:VecMaxs[3] = {1.0,1.0,1.0}

	// Seting entSpeed higher then 2000.0 will not go where you aim
	// Vec Mins/Maxes must be below +-5.0 to make a burndecal
	switch(g_powerNum[id]){
		case 1:{
			entModel = "sprites/shmod/esf_ki_blast.spr"
			entScale = 0.20
			entSpeed = 2000.0
			trailModel = g_spriteTrailY
			trailLength = 1
			trailWidth = 2
		}
		case 2:{
			entModel = "sprites/shmod/esf_kamehameha_blue.spr"
			entScale = 1.20
			entSpeed = 1500.0
			trailModel = g_spriteTrailB
			trailLength = 100
			trailWidth = 8
			VecMins[0] = -2.0
			VecMins[1] = -2.0
			VecMins[2] = -2.0
			VecMaxs[0] = 2.0
			VecMaxs[1] = 2.0
			VecMaxs[2] = 2.0
		}
		case 3:{
			entModel = "sprites/shmod/esf_kamehameha_red.spr"
			entScale = 2.00
			entSpeed = 1000.0
			trailModel = g_spriteTrailR
			trailLength = 100
			trailWidth = 16
			VecMins[0] = -3.0
			VecMins[1] = -3.0
			VecMins[2] = -3.0
			VecMaxs[0] = 3.0
			VecMaxs[1] = 3.0
			VecMaxs[2] = 3.0
		}
		case 4:{
			entModel = "sprites/shmod/esf_spirit_bomb.spr"
			entScale = 0.70
			entSpeed = 800.0
			VecMins[0] = -4.0
			VecMins[1] = -4.0
			VecMins[2] = -4.0
			VecMaxs[0] = 4.0
			VecMaxs[1] = 4.0
			VecMaxs[2] = 4.0
		}
	}

	// Get users postion and angles
	entity_get_vector(id, EV_VEC_origin, vOrigin)
	entity_get_vector(id, EV_VEC_angles, vAngles)
	entity_get_vector(id, EV_VEC_v_angle, vAngle)

	// Change height for entity origin
	if (g_powerNum[id] == 4) vOrigin[2] += 110
	else vOrigin[2] += 6

	new newEnt = create_entity("info_target")
	if( newEnt == 0 ) {
		client_print(id, print_chat, "[SH](Goku) Power Creation Failure")
		return
	}

	g_powerID[id] = newEnt

	entity_set_string(newEnt, EV_SZ_classname, "vexd_goku_power")
	entity_set_model(newEnt, entModel)

	entity_set_vector(newEnt, EV_VEC_mins, VecMins)
	entity_set_vector(newEnt, EV_VEC_maxs, VecMaxs)

	entity_set_origin(newEnt, vOrigin)
	entity_set_vector(newEnt, EV_VEC_angles, vAngles)
	entity_set_vector(newEnt, EV_VEC_v_angle, vAngle)

	entity_set_int(newEnt, EV_INT_solid, 2)
	entity_set_int(newEnt, EV_INT_movetype, 5)
	entity_set_int(newEnt, EV_INT_rendermode, 5)
	entity_set_float(newEnt, EV_FL_renderamt, 255.0)
	entity_set_float(newEnt, EV_FL_scale, entScale)
	entity_set_edict(newEnt, EV_ENT_owner, id)


	// Create a VelocityByAim() function, but instead of users
	// eyesight make it start from the entity's origin - vittu
	new Float:fl_Velocity[3], AimVec[3], velOrigin[3]

	velOrigin[0] = floatround(vOrigin[0])
	velOrigin[1] = floatround(vOrigin[1])
	velOrigin[2] = floatround(vOrigin[2])

	get_user_origin(id, AimVec, 3)

	new distance = get_distance(velOrigin, AimVec)

	// Stupid Check but lets make sure you don't devide by 0
	if (!distance) distance = 1

	new Float:invTime = entSpeed / distance

	fl_Velocity[0] = (AimVec[0] - vOrigin[0]) * invTime
	fl_Velocity[1] = (AimVec[1] - vOrigin[1]) * invTime
	fl_Velocity[2] = (AimVec[2] - vOrigin[2]) * invTime

	entity_set_vector(newEnt, EV_VEC_velocity, fl_Velocity)

	// No trail on Spirit Bomb
	if ( g_powerNum[id] == 4 ) return

	// Set Trail on entity
	message_begin(MSG_BROADCAST, SVC_TEMPENTITY)
	write_byte(22)			// TE_BEAMFOLLOW
	write_short(newEnt)		// entity:attachment to follow
	write_short(trailModel)	// sprite index
	write_byte(trailLength)	// life in 0.1's
	write_byte(trailWidth)	// line width in 0.1's
	write_byte(255)	//colour
	write_byte(255)
	write_byte(255)
	write_byte(255)	// brightness
	message_end()

	if ( g_powerNum[id] == 2 || g_powerNum[id] == 3 ) {
		new iNewVelocity[3], args[6]
		iNewVelocity[0] = floatround(fl_Velocity[0])
		iNewVelocity[1] = floatround(fl_Velocity[1])
		iNewVelocity[2] = floatround(fl_Velocity[2])

		// Pass varibles used to guide entity with
		args[0] = id
		args[1] = newEnt
		args[2] = floatround(entSpeed)
		args[3] = iNewVelocity[0]
		args[4] = iNewVelocity[1]
		args[5] = iNewVelocity[2]

		set_task(0.1, "guide_kamehameha", newEnt, args, 6)
	}
}
//----------------------------------------------------------------------------------------------
public guide_kamehameha(args[])
{
	new AimVec[3], avgFactor
	new Float:fl_origin[3]
	new id = args[0]
	new ent = args[1]
	new speed = args[2]

	if ( !is_valid_ent(ent) ) return

	if ( !is_user_connected(id) ) {
		goku_power_touch(ent,0)
		return
	}

	get_user_origin(id, AimVec, 3)

	entity_get_vector(ent, EV_VEC_origin, fl_origin)

	new iNewVelocity[3]
	new origin[3]

	origin[0] = floatround(fl_origin[0])
	origin[1] = floatround(fl_origin[1])
	origin[2] = floatround(fl_origin[2])

	if ( g_powerNum[id] == 2 )
	avgFactor = 3
	else if ( g_powerNum[id] == 3 )
	avgFactor = 6
	// stupid check but why not
	else
	avgFactor = 8

	new velocityVec[3], length

	velocityVec[0] = AimVec[0]-origin[0]
	velocityVec[1] = AimVec[1]-origin[1]
	velocityVec[2] = AimVec[2]-origin[2]

	length = sqroot(velocityVec[0]*velocityVec[0] + velocityVec[1]*velocityVec[1] + velocityVec[2]*velocityVec[2])
	// Stupid Check but lets make sure you don't devide by 0
	if ( !length ) length = 1

	velocityVec[0] = velocityVec[0]*speed/length
	velocityVec[1] = velocityVec[1]*speed/length
	velocityVec[2] = velocityVec[2]*speed/length

	iNewVelocity[0] = (velocityVec[0] + (args[3] * (avgFactor-1))) / avgFactor
	iNewVelocity[1] = (velocityVec[1] + (args[4] * (avgFactor-1))) / avgFactor
	iNewVelocity[2] = (velocityVec[2] + (args[5] * (avgFactor-1))) / avgFactor

	new Float:fl_iNewVelocity[3]
	fl_iNewVelocity[0] = float(iNewVelocity[0])
	fl_iNewVelocity[1] = float(iNewVelocity[1])
	fl_iNewVelocity[2] = float(iNewVelocity[2])

	entity_set_vector(ent, EV_VEC_velocity, fl_iNewVelocity)

	args[3] = iNewVelocity[0]
	args[4] = iNewVelocity[1]
	args[5] = iNewVelocity[2]

	set_task(0.1, "guide_kamehameha", ent, args, 6)
}
public goku_power_touch(pToucher, pTouched) {

	if (pToucher <= 0) return
	if (!is_valid_ent(pToucher)) return

	new id = entity_get_edict(pToucher, EV_ENT_owner)
	if(!is_user_alive(id)){
		return
	}
	if(!is_valid_ent(g_powerID[id])){
		return
	}
	new dmgRadius = g_maxRadius[id]
	new maxDamage = g_maxDamage[id]
	new Float:fl_vExplodeAt[3]
	new spriteExp = g_spriteExplosionY

	switch(g_powerNum[id]){
		case 2:{
			spriteExp = g_spriteExplosionB
		}
		case 3:{
			spriteExp = g_spriteExplosionR
		}
	}

	entity_get_vector(pToucher, EV_VEC_origin, fl_vExplodeAt)

	new vExplodeAt[3]
	vExplodeAt[0] = floatround(fl_vExplodeAt[0])
	vExplodeAt[1] = floatround(fl_vExplodeAt[1])
	vExplodeAt[2] = floatround(fl_vExplodeAt[2])


	explosion_custom_entity(pToucher,
									float(dmgRadius),float(maxDamage),
									"func_breakable",
									default_explode_knock_force_magnitude,0)
	// Cause the Damage
	new vicOrigin[3], Float:dRatio,  distance, damage
	new players[SH_MAXSLOTS], pnum, vic

	get_players(players, pnum, "a")

	for (new i = 0; i < pnum; i++) {
		vic = players[i]
		if( !is_user_alive(vic) ) continue
		if ( get_user_team(id) == get_user_team(vic) && !get_cvar_num("mp_friendlyfire") && id != vic ) continue

		get_user_origin(vic, vicOrigin)
		distance = get_distance(vExplodeAt, vicOrigin)

		if ( distance < dmgRadius ) {

			dRatio = floatdiv(float(distance), float(dmgRadius))
			damage = maxDamage - floatround(maxDamage * dRatio)

			// Lessen damage taken by self by half
			if ( vic == id ){
				damage = floatround(damage / 2.0)
			}
			sh_extra_damage(vic, id, damage,
								goku_dmgs_arr[g_powerNum[id]][short_dmg_name],
								_,_,_,_,_,
								SH_NEW_DMG_ENERGY_BLAST,
								goku_dmgs_arr[g_powerNum[id]][the_wpn_id])
			
			if((g_powerNum[id]>=3)&&is_user_connected(vic)&&!is_user_alive(vic)){

					new Float:vic_origin_f[3]
					IVecFVec(vicOrigin,vic_origin_f)
					gross_kill_gibs_fx(vic,vic_origin_f,fl_vExplodeAt)
			}

			// Make them feel it
			sh_screenShake(vic, 10, 10, 10)
			emit_sound(vic, CHAN_BODY, "player/pl_pain2.wav", 1.0, ATTN_NORM, 0, PITCH_NORM)

			new Float:fl_Time = distance / 125.0
			new Float:fl_vicVelocity[3]
			fl_vicVelocity[0] = (vicOrigin[0] - vExplodeAt[0]) / fl_Time
			fl_vicVelocity[1] = (vicOrigin[1] - vExplodeAt[1]) / fl_Time
			fl_vicVelocity[2] = (vicOrigin[2] - vExplodeAt[2]) / fl_Time
			entity_set_vector(vic, EV_VEC_velocity, fl_vicVelocity)
		}
	}

	// Make some Effects
	new blastSize = floatround(dmgRadius / 12.0)

	// Explosion Sprite
	message_begin(MSG_BROADCAST, SVC_TEMPENTITY)
	write_byte(23)			//TE_GLOWSPRITE
	write_coord(vExplodeAt[0])
	write_coord(vExplodeAt[1])
	write_coord(vExplodeAt[2])
	write_short(spriteExp)	// model
	write_byte(01)			// life 0.x sec
	write_byte(blastSize)	// size
	write_byte(255)		// brightness
	message_end()

	// Explosion (smoke, sound/effects)
	message_begin(MSG_BROADCAST, SVC_TEMPENTITY)
	write_byte(3)			//TE_EXPLOSION
	write_coord(vExplodeAt[0])
	write_coord(vExplodeAt[1])
	write_coord(vExplodeAt[2])
	write_short(g_spriteSmoke)		// model
	write_byte(blastSize+5)	// scale in 0.1's
	write_byte(20)			// framerate
	write_byte(10)			// flags
	message_end()

	// Create Burn Decals, if they are used
	if ( cvar_val(num,pcvar_decals) == 1 ) {
		// Change burn decal according to blast size
		new decal_id
		if ( blastSize <= 18 ) {
			//radius ~< 216
			decal_id = g_burnDecal[generate_int(0,2)]
		}
		else {
			decal_id = g_burnDecalBig[generate_int(0,2)]
		}

		// Create the burn decal
		message_begin(MSG_BROADCAST, SVC_TEMPENTITY)
		write_byte(109)		//TE_GUNSHOTDECAL
		write_coord(vExplodeAt[0])
		write_coord(vExplodeAt[1])
		write_coord(vExplodeAt[2])
		write_short(0)			//?
		write_byte(decal_id)	//decal
		message_end()
	}

	remove_entity(pToucher)

	// Reset the Varibles
	g_powerNum[id] = 0
	g_powerID[id] = 0
}
//----------------------------------------------------------------------------------------------
public remove_power(id, powerID)
{
	new Float:fl_vOrigin[3]

	entity_get_vector(powerID, EV_VEC_origin, fl_vOrigin)

	// Create an effect of kamehameha being removed
	message_begin(MSG_BROADCAST, SVC_TEMPENTITY)
	write_byte(14)		//TE_IMPLOSION
	write_coord(floatround(fl_vOrigin[0]))
	write_coord(floatround(fl_vOrigin[1]))
	write_coord(floatround(fl_vOrigin[2]))
	write_byte(200)	// radius
	write_byte(40)		// count
	write_byte(45)		// life in 0.1's
	message_end()

	g_powerNum[id] = 0
	g_powerID[id] = 0

	remove_entity(powerID)
}
//----------------------------------------------------------------------------------------------
public goku_loop()
{
	if ( !sh_is_active() ||!sh_is_inround()) return

	new players[SH_MAXSLOTS], pnum, id

	get_players(players, pnum, "a")

	for (new i = 0; i < pnum; i++) {
		id = players[i]
		if ( sh_user_has_hero(id,gHeroID)&& is_user_alive(id) ) {

			new userArmor = get_user_armor(id)

			// Give him armor
			if ( userArmor < g_ssjLevel[3] ) {
				if ( userArmor + g_armorPts > g_ssjLevel[3] ) {
					set_user_armor(id, g_ssjLevel[3])
				}
				else {
					// Give the armor item if armor is 0 so CS knows the player has armor
					if ( userArmor <= 0 ) give_item(id, "item_assaultsuit")

					set_user_armor(id, userArmor + g_armorPts)
				}
			}

			// Check armor again after it's been set
			userArmor = get_user_armor(id)

			if ( userArmor < g_ssjLevel[0] ) {
				// run it this way so it doesn't check all the elses
				if ( g_isSaiyanLevel[id] > 0 ) {
					sh_reset_max_speed(id)
					g_isSaiyanLevel[id] = 0
				}
			}
			else if ( userArmor >= g_ssjLevel[0] && userArmor < g_ssjLevel[1] ) {
				// Set these items only once when armor is ssjlevel 1
				if ( g_isSaiyanLevel[id] < 1 ) {
					new parm[2]
					parm[0] = id
					parm[1] = 5
					powerup_effect(parm)
					set_task(0.1, "powerup_effect", 0, parm, 2, "a", 19)

					set_hudmessage(255, 255, 100, -1.0, 0.25, 0, 0.25, 3.0, 0.0, 0.0)
					ShowSyncHudMsg(id, goku_hud_sync, "Goku - You've turned Super Saiyan")
					emit_sound(id, CHAN_STATIC, "shmod/goku_powerup1.wav", 0.8, ATTN_NORM, 0, PITCH_NORM)

					g_isSaiyanLevel[id] = 1
					ssj_boost(id)
				}
			}
			else if ( userArmor >= g_ssjLevel[1] && userArmor < g_ssjLevel[2] ) {
				// Set these items only once when armor is ssjlevel 2
				if ( g_isSaiyanLevel[id] < 2 ) {
					new parm[2]
					parm[0] = id
					parm[1] = 7
					powerup_effect(parm)
					set_task(0.1, "powerup_effect", 0, parm, 2, "a", 39)

					set_hudmessage(222, 226, 0, -1.0, 0.25, 0, 0.25, 3.0, 0.0, 0.0)
					ShowSyncHudMsg(id, goku_hud_sync, "Goku - You've turned Super Saiyan 2")
					emit_sound(id, CHAN_STATIC, "shmod/goku_powerup2.wav", 0.8, ATTN_NORM, 0, PITCH_NORM)

					g_isSaiyanLevel[id] = 2
					ssj_boost(id)
				}
			}
			else if ( userArmor >= g_ssjLevel[2] && userArmor < g_ssjLevel[3] ) {
				// Set these items only once when armor is ssjlevel 3
				if ( g_isSaiyanLevel[id] < 3 ) {
					new parm[2]
					parm[0] = id
					parm[1] = 9
					powerup_effect(parm)
					set_task(0.1, "powerup_effect", 0, parm, 2, "a", 59)

					set_hudmessage(248, 220, 117, -1.0, 0.25, 0, 0.25, 3.0, 0.0, 0.0)
					ShowSyncHudMsg(id, goku_hud_sync,"Goku - You've turned Super Saiyan 3")
					emit_sound(id, CHAN_STATIC, "shmod/goku_powerup3.wav", 0.8, ATTN_NORM, 0, PITCH_NORM)

					g_isSaiyanLevel[id] = 3
					ssj_boost(id)
				}
			}
			else if ( userArmor >= g_ssjLevel[3] ) {
				// Set these items only once when armor is ssjlevel 4
				if ( g_isSaiyanLevel[id] < 4 ) {
					new parm[2]
					parm[0] = id
					parm[1] = 11
					powerup_effect(parm)
					set_task(0.1, "powerup_effect", 0, parm, 2, "a", 79)

					set_hudmessage(196, 0, 0, -1.0, 0.25, 0, 0.25, 3.0, 0.0, 0.0)
					ShowSyncHudMsg(id, goku_hud_sync,"Goku - You've turned Super Saiyan 4")
					emit_sound(id, CHAN_STATIC, "shmod/goku_powerup4.wav", 0.8, ATTN_NORM, 0, PITCH_NORM)

					g_isSaiyanLevel[id] = 4
					shake_n_stun(id)
					ssj_boost(id)
				}
			}
		}
	}
}
//----------------------------------------------------------------------------------------------
public ssj_boost(id)
{
	if ( !sh_is_active() || !sh_user_has_hero(id,gHeroID) || !is_user_alive(id) || !sh_is_inround()) return
	if ( !g_isSaiyanLevel[id] ) return

	// Speed Boost
	new speedNum = g_isSaiyanLevel[id] - 1
	if ( get_user_maxspeed(id) < g_ssjSpeed[speedNum] && !g_inStun[id] ) {
		set_user_maxspeed(id, g_ssjSpeed[speedNum])
	}

	// HP boost
	new userHealth = get_user_health(id)
	if ( userHealth < cvar_val(num,pcvar_hpmax)) {
		new addHP = cvar_val(num,pcvar_hpl) * g_isSaiyanLevel[id]
		if ( userHealth + addHP > cvar_val(num,pcvar_hpmax)) {
			set_user_health(id, cvar_val(num,pcvar_hpmax) )
		}
		else {
			set_user_health(id, userHealth + addHP)
		}
	}
}
//----------------------------------------------------------------------------------------------
public curweapon(id)
{
	if ( !sh_is_active() || !sh_user_has_hero(id,gHeroID)|| !is_user_alive(id) || !sh_is_inround()) return
	if ( !g_isSaiyanLevel[id] || g_inStun[id] ) return

	new wpnid = read_data(2)

	if ( g_prevWeapon[id] != wpnid ) {
		switch(g_isSaiyanLevel[id]) {
			case 1: if ( get_user_maxspeed(id) < g_ssjSpeed[0] ) set_user_maxspeed(id, g_ssjSpeed[0])
			case 2: if ( get_user_maxspeed(id) < g_ssjSpeed[1] ) set_user_maxspeed(id, g_ssjSpeed[1])
			case 3: if ( get_user_maxspeed(id) < g_ssjSpeed[2] ) set_user_maxspeed(id, g_ssjSpeed[2])
			case 4: if ( get_user_maxspeed(id) < g_ssjSpeed[3] ) set_user_maxspeed(id, g_ssjSpeed[3])
		}
	}
	g_prevWeapon[id] = wpnid
}
//----------------------------------------------------------------------------------------------
public shake_n_stun(id)
{
	new idOrigin[3], vicOrigin[3]
	new players[SH_MAXSLOTS], pnum, vic

	get_user_origin(id, idOrigin)

	get_players(players, pnum, "a")

	for (new i = 0; i < pnum; i++) {
		vic = players[i]
		if ( !is_user_alive(vic) ) continue

		get_user_origin(vic, vicOrigin)


		if ( sh_clients_are_same_team(id,vic) ) continue


		new distance = get_distance(idOrigin, vicOrigin)

		if ( distance <= cvar_val(num,pcvar_radius4)) {
			sh_screenShake(vic, 14, 14, 14)
			g_inStun[vic] = true

			shStun(vic, 5)
			set_user_maxspeed(vic, 150.0)

			set_task(5.0, "reset_instun", vic)

			if ( vic == id ) continue
			// Let them know why they get shaken and stunned, except the person that leveled
			new gokuName[32]
			get_user_name(id, gokuName, 31)
			set_hudmessage(196, 0, 0, -1.0, 0.20, 0, 0.25, 3.0, 0.0, 0.0)
			ShowSyncHudMsg(id, goku_hud_sync,"Goku - %s has turned Super Saiyan 4", gokuName)
		}
	}
	explosion(gHeroID,id,float(cvar_val(num, pcvar_powerup_explode_radius_ssj4)),100.0,default_explode_knock_force_magnitude*0.25,_,1)
}
//----------------------------------------------------------------------------------------------
public reset_instun(id)
{
	g_inStun[id] = false

	if ( !sh_is_active() || !sh_user_has_hero(id,gHeroID)|| !is_user_alive(id) ) return

	switch(g_isSaiyanLevel[id]) {
		case 1: if ( get_user_maxspeed(id) < g_ssjSpeed[0] ) set_user_maxspeed(id, g_ssjSpeed[0])
		case 2: if ( get_user_maxspeed(id) < g_ssjSpeed[1] ) set_user_maxspeed(id, g_ssjSpeed[1])
		case 3: if ( get_user_maxspeed(id) < g_ssjSpeed[2] ) set_user_maxspeed(id, g_ssjSpeed[2])
		case 4: if ( get_user_maxspeed(id) < g_ssjSpeed[3] ) set_user_maxspeed(id, g_ssjSpeed[3])
	}
}
//----------------------------------------------------------------------------------------------
public powerup_effect(parm[])
{
	if ( !sh_is_active() || !sh_is_inround()) return

	new id = parm[0]

	if ( !is_user_alive(id) ) return

	new Size = parm[1]
	new players[SH_MAXSLOTS], pnum
	new idOthers, Origin[3]

	get_players(players, pnum, "a")

	// Show a powerup to all alive players except the one being powered up.
	for (new i = 0; i < pnum; i++) {
		idOthers = players[i]
		if ( !is_user_alive(idOthers) ) continue

		get_user_origin(id, Origin)

		// power up sprite - additive sprite, plays 1 cycle
		message_begin(MSG_ONE, SVC_TEMPENTITY, Origin, idOthers)
		write_byte(17)			// TE_SPRITE
		write_coord(Origin[0])	// center position
		write_coord(Origin[1])
		write_coord(Origin[2]+20)
		write_short(g_spritePowerUp)	// sprite index
		write_byte(Size)		// scale in 0.1's
		write_byte(50)			// brightness
		message_end()

		// power up sprite - additive sprite, plays 1 cycle
		message_begin(MSG_ONE, SVC_TEMPENTITY, Origin, idOthers)
		write_byte(17)			// TE_SPRITE
		write_coord(Origin[0]+5) // center position
		write_coord(Origin[1])
		write_coord(Origin[2]+20)
		write_short(g_spritePowerUp)	// sprite index
		write_byte(Size)		// scale in 0.1's
		write_byte(50)			// brightness
		message_end()

		// power up sprite - additive sprite, plays 1 cycle
		message_begin(MSG_ONE, SVC_TEMPENTITY, Origin, idOthers)
		write_byte(17)			// TE_SPRITE
		write_coord(Origin[0]-5)	// center position
		write_coord(Origin[1])
		write_coord(Origin[2]+20)
		write_short(g_spritePowerUp)	// sprite index
		write_byte(Size)		// scale in 0.1's
		write_byte(50)			// brightness
		message_end()

		// power up sprite - additive sprite, plays 1 cycle
		message_begin(MSG_ONE, SVC_TEMPENTITY, Origin, idOthers)
		write_byte(17)			// TE_SPRITE
		write_coord(Origin[0])	// center position
		write_coord(Origin[1]+5)
		write_coord(Origin[2]+10)
		write_short(g_spritePowerUp)	// sprite index
		write_byte(Size)		// scale in 0.1's
		write_byte(50)			// brightness
		message_end()

		// power up sprite - additive sprite, plays 1 cycle
		message_begin(MSG_ONE, SVC_TEMPENTITY, Origin, idOthers)
		write_byte(17)			// TE_SPRITE
		write_coord(Origin[0])	// center position
		write_coord(Origin[1]-5)
		write_coord(Origin[2]+10)
		write_short(g_spritePowerUp)	// sprite index
		write_byte(Size)		// scale in 0.1's
		write_byte(50)			// brightness
		message_end()
	}
}
//----------------------------------------------------------------------------------------------
public sh_round_end()
{
	for (new id=1; id < sh_maxplayers()+1; id++) {
		if ( sh_user_has_hero(id,gHeroID)) {
			g_isSaiyanLevel[id] = 0
			sh_reset_max_speed(id)
			if ( g_powerID[id] > 0 ) {
				remove_power(id, g_powerID[id])
			}
		}
	}
}
//----------------------------------------------------------------------------------------------
public client_disconnected(id)
{
	if( sh_user_has_hero(id,gHeroID) && g_powerID[id] > 0 ) {
		remove_power(id, g_powerID[id])
	}
}
//----------------------------------------------------------------------------------------------
/* AMXX-Studio Notes - DO NOT MODIFY BELOW HERE
*{\\ rtf1\\ ansi\\ deff0{\\ fonttbl{\\ f0\\ fnil Tahoma;}}\n\\ viewkind4\\ uc1\\ pard\\ lang1049\\ f0\\ fs16 \n\\ par }
*/
