// GOHAN! - from Dragon Ball Z, Goku and Chi Chi's first son.

/* CVARS - copy and paste to shconfig.cfg

//Gohan
gohan_level 10
gohan_health 150		//default 150
gohan_gravity 0.40		//default 0.40 = low gravity
gohan_speed 800		//How fast he is with all weapons
gohan_healpoints 10		//The # of HP healed per second
gohan_healmax 400		//Max # HP gohan can heal to

*/

/*
* v1.2 - vittu - 6/19/05
*      - Minor code clean up.
*
* v1.1 - vittu - 3/13/05
*      - recoded from ArtofDrowning07 cleaned up code
*      - new cvar from ArtofDrowning07, gohan_healmax, you
*         can choose how much goten will heal to now
*/

#include "../my_include/superheromod.inc"

// GLOBAL VARIABLES
#define TASKID 100000
new gHeroName[]="Gohan"
new gHealPoints, gHealAmount
new gHeroID
//----------------------------------------------------------------------------------------------
public plugin_init()
{
	// Plugin Info
	register_plugin("SUPERHERO Gohan", "1.2", "sharky")

	// DO NOT EDIT THIS FILE TO CHANGE CVARS, USE THE SHCONFIG.CFG
	create_cvar("gohan_level", "10")
	create_cvar("gohan_health", "150")
	create_cvar("gohan_gravity", "0.40")
	create_cvar("gohan_speed", "800")
	create_cvar("gohan_healpoints", "10")
	create_cvar("gohan_healmax", "400")

	// FIRE THE EVENT TO CREATE THIS SUPERHERO!
	gHeroID=shCreateHero(gHeroName, "Super Power-Up", "Start with more HP, gain even more each second. Also, has Ultra Speed and Low Gravity!", false, "gohan_level")


	// HEAL LOOP

	// Let Server know about Gohan's Variables
	shSetMaxHealth(gHeroName, "gohan_health")
	shSetMinGravity(gHeroName, "gohan_gravity")
	shSetMaxSpeed(gHeroName, "gohan_speed", "[0]")

	//Set Varibles when plugin loads
	gHealPoints = get_cvar_num("gohan_healpoints")
	gHealAmount = get_cvar_num("gohan_healmax")
}
//----------------------------------------------------------------------------------------------
public sh_hero_init(id, heroID, sh_init_mode:mode){
	if(heroID!=gHeroID) return
	
	remove_task(id+TASKID)
	set_task(1.0, "gohan_loop", id+TASKID, "", 0, "b")

	//Sets this variable to the current status
}
//----------------------------------------------------------------------------------------------
public gohan_loop(id)
{
		id-=TASKID
		if ( sh_get_user_has_hero(id,gHeroID) && is_user_alive(id) ) {
			// Let the server add the hps back since the # of max hps is controlled by it
			// I.E. Superman has more than 100 hps etc.
			shAddHPs(id, gHealPoints, gHealAmount)
		}
}
//----------------------------------------------------------------------------------------------
