// GHOSTFACE! - Woodsboro Killer from the Scream movies.

/* CVARS - copy and paste to shconfig.cfg

//Ghostface (Scream)
ghostface_level 0
ghostface_health 100		//Default 100 (no extra health)
ghostface_armor 100		//Default 100
ghostface_gravity 1.0		//Default 1.0 = no extra gravity (0.50 is 50% of normal gravity, ect.)
ghostface_knifespeed 290	//Speed when holding knife, Default 290 (for faster then normal speed set to 261 or higher)
ghostface_knifemult 1.5		//Damage multiplyer for his knife, Default 1.5
ghostface_healpoints 5		//The # of HP healed per second, Default 5
// Below only used if USE_PLAYER_MODEL is uncommented

*/


/*
* v1.0 - vittu - 7/3/08
*      - Complete rework of entire code, started from scratch.
*      - Renamed Hero to Ghostface, as it is the true character name and Scream is just the movie.
*
*    Recreated due to demand and newly available CS model, as old had HL model (which is not allowed).
*    Hero orginally named Scream created by some jerk-off who shall not be named.
*    Hero was ripped from Masterchief + Wolverine.
*    There was also another version that was Chucky + Wolverine. That is not this one.
*
*    Knife model by Dennispls.
*    Player model by Hoffa(origninal HLDM model), converted to CS by xVox-Bloodstonex(Re-skin/Highres/Hack/Rigg), & Luca (Hands).
*    (Note: Models differ from Scream, because these better represent the character.)
*/


//---------- User Changeable Defines --------//


// Comment out to not use the Knife model
#define USE_WPN_MODEL


//------- Do not edit below this point ------//
#define I_WANT_CONSTANTS
#include "../my_include/superheromod.inc"
#include "../my_heroes/sh_aux_stuff/sh_aux_inc.inc"
#include "../my_heroes/sh_aux_stuff/sh_aux_stuff_natives_pt5.inc"

// GLOBAL VARIABLES
new HeroName[] = "Ghostface (Scream)"
new gHeroID
new PlayerMaxHealth[SH_MAXSLOTS+1]
new HealPoints
new CvarKnifeDmgMult, CvarHealPoints

new const Model_Player[STRING_SIZE] = "models/player/ghostface/ghostface.mdl"
new const Model_Player_Name[STRING_SIZE] = "ghostface"

#define Model_V_Knife "models/shmod/ghostface_v_knife.mdl"
#define Model_P_Knife "models/shmod/ghostface_p_knife.mdl"

//----------------------------------------------------------------------------------------------
public plugin_init()
{
	// Plugin Info
	register_plugin("SUPERHERO Ghostface", "1.0", "vittu")

	// DO NOT EDIT THIS FILE TO CHANGE CVARS, USE THE SHCONFIG.CFG
	register_cvar("ghostface_level", "0")
	register_cvar("ghostface_health", "100")
	register_cvar("ghostface_armor", "100")
	register_cvar("ghostface_gravity", "1.0")
	register_cvar("ghostface_knifespeed", "290")
	CvarKnifeDmgMult = register_cvar("ghostface_knifemult", "1.5")
	CvarHealPoints = register_cvar("ghostface_healpoints", "5")

	// FIRE THE EVENT TO CREATE THIS SUPERHERO!
	gHeroID=shCreateHero(HeroName, "Knife Dmg & HP Regen", "Become the Woodsboro Serial Killer - get a Bowie Knife that deals Extra Damage, also Regen Health.", false, "ghostface_level")
	sh_register_superheromod_model(gHeroID,
								Model_Player,
								Model_Player,
								Model_Player_Name,
								"",
								"")
	
	sh_register_superheromod_weapon_model(gHeroID,CSW_KNIFE,Model_V_Knife,Model_P_Knife)


	// EVENTS
	register_event("Damage", "ghostface_damage", "b", "2!0")

	// Let Server know about the hero's variables
	shSetMaxHealth(HeroName, "ghostface_health")
	shSetMaxArmor(HeroName, "ghostface_armor")
	shSetMinGravity(HeroName, "ghostface_gravity")
	shSetMaxSpeed(HeroName, "ghostface_knifespeed", "[29]")

	register_srvcmd("ghostface_maxhealth", "ghostface_maxhealth")
	shRegMaxHealth(HeroName, "ghostface_maxhealth")

	// HEAL LOOP
	set_task(1.0, "heal_loop", _, _, _, "b")
}
//----------------------------------------------------------------------------------------------
public plugin_cfg()
{
	HealPoints = get_pcvar_num(CvarHealPoints)	
}
//----------------------------------------------------------------------------------------------
public ghostface_damage(id)
{
	if ( !sh_is_active() || !is_user_alive(id) )
		return

	new weapon, bodypart, attacker = get_user_attacker(id, weapon, bodypart)

	if ( attacker <= 0 || attacker > SH_MAXSLOTS||attacker == id )
		return

	if (sh_user_has_hero(attacker,gHeroID) && weapon == CSW_KNIFE )
	{
		new damage = read_data(2)
		new extraDamage = floatround(damage * get_pcvar_float(CvarKnifeDmgMult) - damage)
		if ( extraDamage > 0 )
			sh_extra_damage(id, attacker, extraDamage, "knife", my_hitpoint_enum:bodypart)
	}
}
//----------------------------------------------------------------------------------------------
public ghostface_maxhealth()
{
	new id[6]
	new health[9]

	read_argv(1,id,5)
	read_argv(2,health,8)

	PlayerMaxHealth[str_to_num(id)] = str_to_num(health)
}
//----------------------------------------------------------------------------------------------
public heal_loop()
{
	if ( !sh_is_active() ) return

	for ( new id = 1; id <= SH_MAXSLOTS; id++ ) {
		if ( sh_user_has_hero(id,gHeroID) && is_user_alive(id) ) {
			// Let the server add the hps back since the # of max hps is controlled by it
			// I.E. Superman has more than 100 hps etc.
			shAddHPs(id, HealPoints, PlayerMaxHealth[id])
		}
	}
}
//----------------------------------------------------------------------------------------------