// POISON IVY! - from Batman. Poison Ivy is immune to all forms of poison and her body manufactures poisons at will.

/* CVARS - copy and paste to shconfig.cfg

//Poison Ivy
poisonivy_level 0
poisonivy_damage 1		//Damage per second from infection
poisonivy_cooldown 0.0	//Seconds before you can infect another player
poisonivy_xpbased 0		//Do they cause more damage each xp level, 0=no 1=yes (def=0)
poisonivy_dpl 1		//Amount of additonal damage per level
poisonivy_maxdpl 0		//Maximum possible damage amount if xpbased (0=no max set)
poisonivy_self 1		//Can users with Poison Ivy be infected, 0=no 1=yes

*/

/*
* v1.5 - vittu - 7/3/05
*      - Fixed crash to AMX caused by the previous update, since
*          AMX can't register a MSG_ONE_UNRELIABLE message.
*
* v1.4 - vittu - 6/27/05
*      - Minor update for FF servers, prevents the sh_extra_damage
*          from saying you attacked a teammate for every cycle.
*
* v1.3 - vittu - 6/22/05
*      - Minor code clean up.
*
* v1.2 - vittu - 4/7/05
*      - Removed some useless code and cleaned up.
*      - Added poison HUD icon and a sound to when a user gets poisoned.
*      - Added cooldown cvar and XP based damage possiblity thru cvar.
*      - Added cvar option for not poisoning users with Poison Ivy,
*         since the charater is immune to all poisons.
*
*    Hero orginally created by AssKicR
*/
#include "../my_include/superheromod.inc"
#include "../my_heroes/sh_aux_stuff/sh_aux_consts.inc"
#include "../my_heroes/special_fx_inc/sh_yakui_get_set.inc"
#include "../my_heroes/special_fx_inc/sh_gatling_special_fx.inc"



new dmg_source_name_short_poison_ivy_drain[SAFE_BUFFER_SIZE+1]="poison_ivy_drain"
new dmg_source_name_log_poison_ivy_drain[SAFE_BUFFER_SIZE+1]="poison_ivy_drain"
new custom_dmg_id_poison_ivy_drain

// GLOBAL VARIABLES
new gHeroName[]="Poison Ivy"
new gHeroID
new gIsPoisonedMask[SH_MAXSLOTS+1] = {0, ...}
new gPoisonDamage[SH_MAXSLOTS+1]
new gPlayerLevels[SH_MAXSLOTS+1]
new gmsgDamage, gmsgIcon
//----------------------------------------------------------------------------------------------
public plugin_init()
{
	// Plugin Info
	register_plugin("SUPERHERO Poison Ivy", "1.5", "AssKicR / vittu")

	// DO NOT EDIT THIS FILE TO CHANGE CVARS, USE THE SHCONFIG.CFG
	create_cvar("poisonivy_level", "0")
	create_cvar("poisonivy_damage", "1")
	create_cvar("poisonivy_cooldown", "0.0")
	create_cvar("poisonivy_xpbased", "0")
	create_cvar("poisonivy_dpl", "1")
	create_cvar("poisonivy_maxdpl", "0")
	create_cvar("poisonivy_self", "0")

	// FIRE THE EVENT TO CREATE THIS SUPERHERO!
	gHeroID=shCreateHero(gHeroName, "Infect Poison", "Infect the enemy with your Poisoned Bullets or Poisoned Knife", false, "poisonivy_level")


	register_event("Damage", "poisonivy_damage", "b", "2!0")

	// LOOP
	set_task(1.0, "poisonivy_loop", 0, "", 0, "b")

	// LEVELS
	register_srvcmd("poisonivy_levels", "poisonivy_levels")
	shRegLevels(gHeroName, "poisonivy_levels")

	gmsgDamage = get_user_msgid("Damage")
	gmsgIcon = get_user_msgid("StatusIcon")

	custom_dmg_id_poison_ivy_drain=sh_log_custom_damage_source(gHeroID,
				dmg_source_name_short_poison_ivy_drain,
				dmg_source_name_log_poison_ivy_drain,
				0)

}
//----------------------------------------------------------------------------------------------
public sh_hero_init(id, heroID, sh_init_mode:mode){
	if(heroID!=gHeroID) return

	// This gets run if they had the power but don't anymore
	if ( !sh_get_user_has_hero(id,gHeroID)&& is_user_connected(id) ) {
		remove_poison(id)
	}

}
//----------------------------------------------------------------------------------------------
public poisonivy_levels()
{
	new id[5]
	new lev[5]

	read_argv(1,id,4)
	read_argv(2,lev,4)

	gPlayerLevels[str_to_num(id)] = str_to_num(lev)
}
//----------------------------------------------------------------------------------------------
public sh_client_spawn(id)
{
	if ( is_user_alive(id) && sh_is_active() ) {

		reset_poisoned(id)

		if( sh_get_user_has_hero(id,gHeroID)) {

			sh_unset_cooldown_flag(id)

			// Set damage amount per user
			if ( get_cvar_num("poisonivy_xpbased") ) {

				new poison = ( (gPlayerLevels[id] - get_cvar_num("poisonivy_level")) * get_cvar_num("poisonivy_dpl") + get_cvar_num("poisonivy_damage") )

				// Set max possible damage if one is set
				if ( get_cvar_num("poisonivy_maxdpl") > 0 ) {
					if ( poison > get_cvar_num("poisonivy_maxdpl") ) {
						poison = get_cvar_num("poisonivy_maxdpl")
					}
				}

				// Stupid checks
				if (poison > 0) {
					gPoisonDamage[id] = poison
				}
				else if (poison == 0) {
					gPoisonDamage[id] = get_cvar_num("poisonivy_damage")
				}
				else {
					gPoisonDamage[id] = 0
				}
			}
			else {
				gPoisonDamage[id] = get_cvar_num("poisonivy_damage")
			}
		}
	}
}
//----------------------------------------------------------------------------------------------
public poisonivy_damage(id)
{
	if ( !sh_is_active() || !is_user_alive(id) ) return

	new weapon, bodypart, attacker = get_user_attacker(id, weapon, bodypart)

	if ( attacker <= 0 || attacker > SH_MAXSLOTS ||attacker == id ) return

	// If already poisoned no need to set it twice
	if( Get_BitVar(gIsPoisonedMask[id],attacker) ) return

	// Can users with Poison Ivy be poisoned
	if ( !get_cvar_num("poisonivy_self") ) {
		if ( sh_get_user_has_hero(id,gHeroID)) return
	}

	if ( sh_get_user_has_hero(attacker,gHeroID)&& weapon != CSW_HEGRENADE && is_user_alive(id) && !sh_get_cooldown_flag(attacker)&& id != attacker ) {
		// Set a poisoned player
		emit_sound(id, CHAN_STATIC, PIERCE_WOUND_SFX, 1.0, ATTN_NORM, 0, PITCH_NORM)
		Assign_BitVar(gIsPoisonedMask[id],attacker,true_for_macro) 
		if((gatling_get_fx_num(id)>KILL)&&(gatling_get_fx_num(id)<fx_id)){
			gatling_set_fx_num(id,POISON)
		}

		// Set a cooldown if there is one until user can poison another player
		if (get_cvar_float("poisonivy_cooldown") > 0.0){
			sh_set_cooldown(attacker, get_cvar_float("poisonivy_cooldown"))
		}
	}
}
//----------------------------------------------------------------------------------------------
public poisonivy_loop()
{
	if ( !sh_is_active() ) return

	for ( new attacker = 1; attacker < sh_maxplayers()+1; attacker++ ) {
		if ( !sh_get_user_has_hero(attacker,gHeroID) || !is_user_connected(attacker) ) continue

		for ( new id = 1; id < sh_maxplayers()+1; id++ ) {
			if (  is_user_alive(id) ) {
				if(!Get_BitVar(gIsPoisonedMask[id],attacker) ) continue

				new damage = gPoisonDamage[attacker]

				sh_extra_damage(id, attacker, damage,
											_,_,_,_,_,
											SH_NEW_DMG_DRAIN,
											custom_dmg_id_poison_ivy_drain)

				new origin[3]
				get_user_origin(id, origin)

				// Poison HUD Icon
				message_begin(MSG_ONE, gmsgIcon, {0,0,0}, id)
				write_byte(1)				// status (0=hide, 1=show, 2=flash)
				write_string("dmg_poison")	// sprite name
				write_byte(0)		// red
				write_byte(125)	// green
				write_byte(0)		// blue
				message_end()

				// Remove poison icon
				set_task(0.3, "remove_poisonicon", id)

				// Show damage, damage origin is self
				message_begin(MSG_ONE, gmsgDamage, {0,0,0}, id)
				write_byte(30)			// dmg_save
				write_byte(30)			// dmg_take
				write_long((1 << 16))	// visibleDamageBits
				write_coord(origin[0])	// damageOrigin.x
				write_coord(origin[1])	// damageOrigin.y
				write_coord(origin[2])	// damageOrigin.z
				message_end()
			}
		}
	}
}
//----------------------------------------------------------------------------------------------
public client_connect(id)
{
	reset_poisoned(id)
}
//----------------------------------------------------------------------------------------------
public client_disconnected(id)
{
	remove_poison(id)

	reset_poisoned(id)
}
//----------------------------------------------------------------------------------------------
public sh_client_death(id)
{

	reset_poisoned(id)
}
//----------------------------------------------------------------------------------------------
public reset_poisoned(victim)
{
	// Resets poison status on victim if poisoned by any posion ivy's
	for ( new attacker = 1; attacker < sh_maxplayers()+1; attacker++ ) {
		if ( Get_BitVar(gIsPoisonedMask[victim],attacker)  ) {
			Assign_BitVar(gIsPoisonedMask[victim],attacker,false_for_macro) 
		}
	}
}
//----------------------------------------------------------------------------------------------
public remove_poison(attacker)
{
	new players[SH_MAXSLOTS], pnum, victim
	get_players(players, pnum, "a")

	// Removes poison on alive players that the attacker poisoned
	for (new i = 0; i < pnum; i++) {
		victim = players[i]
		if ( Get_BitVar(gIsPoisonedMask[victim],attacker)  ) {
			Assign_BitVar(gIsPoisonedMask[victim],attacker,false_for_macro) 
			if(gatling_get_fx_num(victim)==POISON){
				gatling_set_fx_num(victim,FX_ID_NONE)
			}
		}
	}
}
//----------------------------------------------------------------------------------------------
public remove_poisonicon(id)
{
	if ( !is_user_connected(id) ) return

	// Poison HUD Icon, reset to none
	message_begin(MSG_ONE, gmsgIcon, {0,0,0}, id)
	write_byte(0)				// status (0=hide, 1=show, 2=flash)
	write_string("dmg_poison")	// sprite name
	write_byte(0)		// red
	write_byte(0)		// green
	write_byte(0)		// blue
	message_end()
}
//----------------------------------------------------------------------------------------------
/* AMXX-Studio Notes - DO NOT MODIFY BELOW HERE
*{\\ rtf1\\ ansi\\ deff0{\\ fonttbl{\\ f0\\ fnil Tahoma;}}\n\\ viewkind4\\ uc1\\ pard\\ lang2070\\ f0\\ fs16 \n\\ par }
*/
