//Riddick

//This is basically just wolverine with a different model and different default CVAR settings
//Done as a request because someone else made it and refused to share

/* CVARS - copy and paste to shconfig.cfg

//Riddick
riddick_level 0
riddick_healpoints 5			//The # of HP healed per second
riddick_knifespeed 340			//Speed of riddick in knife mode
riddick_knifemult 1.8			//Multiplier for knife damage

*/

#define I_WANT_QUICK_CHECKS
#define I_WANT_MISC_FUNCS
#define I_WANT_CONSTANTS
#include "../my_include/superheromod.inc"
#include "../my_heroes/sh_aux_stuff/sh_aux_inc.inc"
#include "../my_heroes/sh_aux_stuff/sh_aux_stuff_natives_pt5.inc"

// GLOBAL VARIABLES
new gHeroName[]="Riddick"
new gHeroID
new gHealPoints


new dmg_source_name_short_dual_knife[SAFE_BUFFER_SIZE+1]="dual_knife"
new dmg_source_name_log_dual_knife[SAFE_BUFFER_SIZE+1]="dual_knife"
new custom_dmg_id_dual_knife

//----------------------------------------------------------------------------------------------
public plugin_init()
{
	// Plugin Info
	register_plugin("SUPERHERO Riddick","1.0","JTP10181")

	// DO NOT EDIT THIS FILE TO CHANGE CVARS, USE THE SHCONFIG.CFG
	create_cvar("riddick_level", "0" )
	create_cvar("riddick_healpoints", "3" )
	create_cvar("riddick_knifespeed", "290")
	create_cvar("riddick_knifemult", "1.35" )

	// FIRE THE EVENT TO CREATE THIS SUPERHERO!
	gHeroID=shCreateHero(gHeroName, "Auto Heal + SuperKnife", "Auto-Heal, Knife Damage, Extra Knife Speed", false, "riddick_level" )
	
	sh_register_superheromod_weapon_model(gHeroID,CSW_KNIFE,"models/shmod/riddick_knife.mdl")

	custom_dmg_id_dual_knife=sh_log_custom_damage_source(gHeroID,
					dmg_source_name_short_dual_knife,
					dmg_source_name_log_dual_knife,1)

	// HEAL LOOP
	set_task(1.0,"riddick_loop",0,"",0,"b" )

	// EXTRA KNIFE DAMAGE
	RegisterHam(Ham_TraceAttack,"player","riddick_damage",_,true)

	// Let Server know about Woverines max knife speed
	shSetMaxSpeed(gHeroName, "riddick_knifespeed", "[29]" )

	gHealPoints = get_cvar_num("riddick_healpoints")
}
//----------------------------------------------------------------------------------------------
public riddick_loop()
{
	if (!sh_is_active()) return
	for ( new id = 1; id < sh_maxplayers()+1; id++ ) {
		if (  sh_get_user_has_hero(id,gHeroID) && is_user_alive(id)  )   {
			// Let the server add the hps back since the # of max hps is controlled by it
			// I.E. Superman has more than 100 hps etc.
			shAddHPs(id, gHealPoints, sh_get_max_hp(id))
		}
	}
}
//RegisterHam(Ham_TraceAttack,"player","riddick_damage",_,true)
public riddick_damage(id, attacker, Float:damage, Float:direction[3], traceresult, damagebits)
{	
	if(damage<=0.0){
		return HAM_IGNORED
	}
	
	if( !sh_is_active() || !is_user_alive(id) || !is_user_connected(id)) return HAM_IGNORED;
	if ( (attacker==id)||!is_user_connected(attacker)||!sh_get_user_has_hero(attacker,gHeroID)) return HAM_IGNORED
	
	new weapon = get_user_weapon(attacker)
	
	if((weapon!=CSW_KNIFE)){

		return HAM_IGNORED
	}

	new my_hitpoint_enum:the_hitpoint= my_hitpoint_enum:get_tr2(traceresult,TR_Hitgroup)

	new Float:extraDamage = damage * get_cvar_float("riddick_knifemult") - damage
	
	if (floatround(extraDamage)>0){
		sh_extra_damage(id, attacker, floatround(extraDamage),
						the_hitpoint,
						_,_,_,_,
						SH_NEW_DMG_SUPER_MELEE,
						custom_dmg_id_dual_knife)
	}

	return HAM_IGNORED;
}
//----------------------------------------------------------------------------------------------
public sh_client_spawn(id)
{
	if (sh_get_user_has_hero(id,gHeroID)&& is_user_alive(id) && sh_is_active() ) {
		new clip, ammo, wpnid = get_user_weapon(id,clip,ammo)
		if (wpnid != CSW_KNIFE && wpnid > 0) {
			new wpn[32]
			get_weaponname(wpnid,wpn,31)
			engclient_cmd(id,wpn)
		}
	}
}
//----------------------------------------------------------------------------------------------
/* AMXX-Studio Notes - DO NOT MODIFY BELOW HERE
*{\\ rtf1\\ ansi\\ deff0{\\ fonttbl{\\ f0\\ fnil Tahoma;}}\n\\ viewkind4\\ uc1\\ pard\\ lang1030\\ f0\\ fs16 \n\\ par }
*/
