// Veronika

/* CVARS - copy and paste to shconfig.cfg

//Veronika
veronika_level 8
veronika_akmulti 2.0			//Damage multiplyer for his ak47
veronika_grenades 5				//Grenades given
veronika_m203rad 200
veronika_m203dmg 120
*/

//veronika by DuPeR/Yang
// Thanx to the original code of MP5+203 Mod by PaintLancer


#define I_WANT_CONSTANTS
#define I_WANT_MATH_FUNCS
#define I_WANT_MISC_FUNCS

#include "../my_include/superheromod.inc"
#include "../my_heroes/sh_aux_stuff/sh_aux_inc.inc"
#include "../my_heroes/sh_aux_stuff/sh_aux_stuff_natives_pt1.inc"
#include "../my_heroes/sh_aux_stuff/sh_aux_stuff_natives_pt3.inc"
#include "../my_heroes/sh_aux_stuff/sh_aux_stuff_natives_pt5.inc"
#include "../my_include/my_author_header.inc"

#define veronika_ak_v_mdl "models/shmod/veronika/ak47grenade.mdl"
#define veronika_ak_p_mdl "models/shmod/veronika/p_9mmar.mdl"

// VARIABLES
new gHeroName[]="Veronika"

new dmg_source_name_short_ak[SAFE_BUFFER_SIZE+1]="ak_gl"
new dmg_source_name_log_ak[SAFE_BUFFER_SIZE+1]="ak47_glauncher"
new custom_dmg_id_ak

new dmg_source_name_short_grenade[SAFE_BUFFER_SIZE+1]="m203"
new dmg_source_name_log_grenade[SAFE_BUFFER_SIZE+1]="m203_grenade"
new custom_dmg_id_grenade

#define VERONIKA_GRENADE_SPEED 1250
new g_ammo[33]
new g_m203_loaded[33]
new gHeroID
//sprites
new m_iTrail
new xplode

#define TE_BEAMFOLLOW 22

//----------------------------------------------------------------------------------------------
public plugin_init()
{
	my_authored_register_func("SUPERHERO Veronika","1.3","DuPeR/Yang",true,AUTHOR)
	
	// DO NOT EDIT THIS FILE TO CHANGE CVARS, USE THE SHCONFIG.CFG
	create_cvar("veronika_level", "8")
	create_cvar("veronika_akmulti", "2")
	//create_cvar("veronika_crazynade","0") //makes nades bounce off all walls with perfect elasticity until it hits an entity or player...can get crazy
	create_cvar("veronika_m203conc","10.0")  //force of knockback
	create_cvar("veronika_m203trail","1")  //nade trails
	create_cvar("veronika_m203rad","200")  //radius of dmg
	create_cvar("veronika_m203dmg","75")  //dmg
	create_cvar("veronika_grenades","5")  //cool down period b4 gets another one
	

	register_entity_as_wall_touchable("m203_nade","veronika_gren_touch")
	register_custom_touchable("m203_nade","veronika_gren_touch",player_vector,1)
	
	// FIRE THE EVENT TO CREATE THIS SUPERHERO!
	gHeroID=shCreateHero(gHeroName, "Resident Evil", "AK Grenade Launcher Right Mouse Button.", false, "veronika_level" )
	
	sh_register_superheromod_weapon_model(gHeroID,CSW_AK47, veronika_ak_v_mdl, veronika_ak_p_mdl)

	custom_dmg_id_ak=sh_log_custom_damage_source(gHeroID,dmg_source_name_short_ak,dmg_source_name_log_ak,0)
	custom_dmg_id_grenade=sh_log_custom_damage_source(gHeroID,dmg_source_name_short_grenade,dmg_source_name_log_grenade,0)
	// REGISTER EVENTS THIS HERO WILL RESPOND TO! (AND SERVER COMMANDS)
	
	register_event("CurWeapon", "weaponChange","be","1=1")
	register_event("Damage", "veronika_damage","b","2!0")
	
	//handle when player presses attack2
	register_forward(FM_CmdStart, "CmdStart")
	
	
	shSetShieldRestrict(gHeroName)
}
//----------------------------------------------------------------------------------------------
public plugin_precache()
{
	engfunc(EngFunc_PrecacheModel,"models/grenade.mdl")
	engfunc(EngFunc_PrecacheSound,"shmod/glauncher.wav")
	engfunc(EngFunc_PrecacheSound,"shmod/a_exm2.wav")
	
	m_iTrail = engfunc(EngFunc_PrecacheModel,"sprites/smoke.spr")
	xplode = engfunc(EngFunc_PrecacheModel,"sprites/shmod/zerogxplode2.spr")
}

//----------------------------------------------------------------------------------------------
public sh_hero_init(id, heroID, sh_init_mode:mode){
	if(heroID!=gHeroID) return

	g_ammo[id] = get_cvar_num("veronika_grenades")
	g_m203_loaded[id] = 1
	
	if ( !is_user_alive(id) ) return
	
	if ( sh_get_user_has_hero(id,gHeroID) ) {
		veronika_weapons(id)
		}
	else {
		sh_drop_weapon(id,CSW_AK47)
	}
}
//----------------------------------------------------------------------------------------------
public sh_client_spawn(id)
{
	if ( sh_get_user_has_hero(id,gHeroID)&& is_user_alive(id) && sh_is_active() ) {
		set_task(0.1, "veronika_weapons", id)
		g_ammo[id] = get_cvar_num("veronika_grenades")
		new clip, ammo, wpnid = get_user_weapon(id,clip,ammo)
		if (wpnid != CSW_AK47 && wpnid > 0) {
			new wpn[32]
			get_weaponname(wpnid,wpn,31)
			engclient_cmd(id,wpn)
		}
	}
	new grenada = find_ent_by_class(-1, "m203_nade")
	while(grenada) {
		remove_entity(grenada)
		grenada = find_ent_by_class(grenada, "m203_nade")
	}
}
//----------------------------------------------------------------------------------------------
public veronika_weapons(id)
{
	if ( is_user_alive(id) && sh_is_active() ) {
		sh_give_weapon(id,CSW_AK47)
	}
}
//----------------------------------------------------------------------------------------------
public weaponChange(id)
{
	if ( !sh_get_user_has_hero(id,gHeroID)|| !sh_is_active() ) return
	
	new wpnid = read_data(2)
	new clip = read_data(3)
	
	if ( wpnid != CSW_AK47 ) return
	
		
	// Never Run Out of Ammo!
	if ( clip == 0 ) {
		sh_reload_ammo(id)
	}
}
//----------------------------------------------------------------------------------------------
public veronika_damage(id)
{
	if (!sh_is_active() || !is_user_alive(id)) return
	
	new damage = read_data(2)
	new weapon, bodypart, attacker = get_user_attacker(id, weapon, bodypart)

	if ( attacker <= 0 || attacker > SH_MAXSLOTS ||attacker == id ) return
	
	if ( sh_get_user_has_hero(attacker,gHeroID) && weapon == CSW_AK47 && is_user_alive(id) ) {
		// do extra damage
		new extraDamage = floatround(damage * get_cvar_float("veronika_akmulti") - damage)
		if (extraDamage > 0){
			sh_extra_damage( id, attacker, extraDamage,
								my_hitpoint_enum:bodypart ,
								_,_,_,_,
								SH_NEW_DMG_SUPER_BULLET,
								custom_dmg_id_ak)

		}
	}
}
//----------------------------------------------------------------------------------------------
public CmdStart(id, uc_handle)
{

	if(!sh_is_active()||sh_is_freezetime()){
		return FMRES_IGNORED
	}
	if(!is_user_alive(id)){
			
		return FMRES_IGNORED
	}

	if(!sh_get_user_has_hero(id,gHeroID)){
			
		return FMRES_IGNORED
	}

	new button = get_uc(uc_handle, UC_Buttons);
	new clip, ammo, weapon = get_user_weapon(id, clip, ammo);
	
	if((weapon==CSW_AK47)&& (button& IN_ATTACK2 )){

			launch_nade(id)
			return FMRES_IGNORED
	}
	return FMRES_IGNORED
}


public launch_nade(id)
{
	if( !sh_get_user_has_hero(id,gHeroID)|| !(is_user_alive(id)) || g_m203_loaded[id] == 0 )
		return PLUGIN_CONTINUE
	
	if(g_ammo[id] == 0)
	{
		client_print(id, print_center, "You are out of m203 grenades!")
		return PLUGIN_CONTINUE
	}
	
	entity_set_int(id, EV_INT_weaponanim, 3)
	
	new Float: Origin[3], Float: Velocity[3], Float: vAngle[3], Ent
	
	entity_get_vector(id, EV_VEC_origin , Origin)
	entity_get_vector(id, EV_VEC_v_angle, vAngle)
	
	//client_print(id, print_center, "Origin: %f-%f-%f", Origin[0], Origin[1], Origin[2])
	//client_print(id, print_center, "vAngle: %f-%f-%f", vAngle[0], vAngle[1], vAngle[2])
	
	
	Ent = create_entity("info_target")
	
	if (!Ent) return PLUGIN_HANDLED
	
	entity_set_string(Ent, EV_SZ_classname, "m203_nade")
	entity_set_model(Ent, "models/grenade.mdl")
	
	new Float:MinBox[3] = {-1.0, -1.0, -1.0}
	new Float:MaxBox[3] = {1.0, 1.0, 1.0}
	entity_set_vector(Ent, EV_VEC_mins, MinBox)
	entity_set_vector(Ent, EV_VEC_maxs, MaxBox)
	
	entity_set_vector(Ent, EV_VEC_angles, vAngle)
	
	entity_set_int(Ent, EV_INT_effects, 2)
	//default
	//entity_set_int(Ent, EV_INT_solid, SOLID_TRIGGER)
	//entity_set_int(Ent, EV_INT_movetype, MOVETYPE_BOUNCE)
	entity_set_int(Ent, EV_INT_solid, SOLID_TRIGGER)
	entity_set_int(Ent, EV_INT_movetype, MOVETYPE_BOUNCE)
	entity_set_edict(Ent, EV_ENT_owner, id)
	
	VelocityByAim(id, VERONIKA_GRENADE_SPEED , Velocity)
	new Float:mini_Velocity[3];
	multiply_3d_vector_by_scalar(Velocity,1.0/float(VERONIKA_GRENADE_SPEED),mini_Velocity);
	multiply_3d_vector_by_scalar(mini_Velocity,30.0,mini_Velocity);
	add_3d_vectors(Origin,mini_Velocity,Origin);
	entity_set_origin(Ent, Origin)
	entity_set_vector(Ent, EV_VEC_velocity ,Velocity)
	
	emit_sound(id,CHAN_VOICE,"shmod/glauncher.wav", 1.0, ATTN_NORM, 0, PITCH_NORM)
	
	g_m203_loaded[id] = 0
	
	ammo_hud(id,g_ammo[id],0)
	g_ammo[id]--
	ammo_hud(id,g_ammo[id],1)
	
	new parm[1]
	parm[0] = Ent
	
	set_task(0.2, "grentrail",id,parm,1)
	
	parm[0] = id
	set_task(2.0, "m203_reload",id+9910,parm,1)
	
	return PLUGIN_CONTINUE
}

public m203_reload(parm[])
{
	g_m203_loaded[parm[0]] = 1
}

public veronika_gren_touch(pToucher, pTouched)
{
	
	if (pToucher <= 0) return
	if (!is_valid_ent(pToucher)) return

	new damradius = get_cvar_num("veronika_m203rad")//200
	new maxdamage = get_cvar_num("veronika_m203dmg")//70
	
	new tkill = 0
	new Float:fl_vExplodeAt[3]
	entity_get_vector(pToucher, EV_VEC_origin, fl_vExplodeAt)
	new vExplodeAt[3]
	vExplodeAt[0] = floatround(fl_vExplodeAt[0])
	vExplodeAt[1] = floatround(fl_vExplodeAt[1])
	vExplodeAt[2] = floatround(fl_vExplodeAt[2])
	new oid = entity_get_edict(pToucher, EV_ENT_owner)
	new origin[3],dist,i,Float:dRatio,damage
	
	for ( i = 0; i < 32; i++)
	{
		if((is_user_alive(i)))
		{
			get_user_origin(i,origin)
			dist = get_distance(origin,vExplodeAt)
			if (dist <= damradius)
			{
				dRatio = floatdiv(float(dist),float(damradius))
				damage = maxdamage - floatround(floatmul(float(maxdamage),dRatio))
				
				set_velocity_from_origin(i, fl_vExplodeAt, get_cvar_float("veronika_m203conc")*damage) // ThantiK's he-conc function - tried getting it to recognize m203 nades but failed so imported function
				
				if(i == oid){
					do_victim(i,oid,damage,0)
				}
				if(cvar_exists("mp_friendlyfire"))
				{
					if( get_cvar_num("mp_friendlyfire"))
					{
						if(get_user_team(i) == get_user_team(oid)){
							tkill = 1
						}
						do_victim(i,oid,damage,tkill)
					}
					else
					{
						if(get_user_team(i) != get_user_team(oid))
						{
							do_victim(i,oid,damage,0)
						}
					}
				}
				else if(i != oid){
					do_victim(i,oid,damage,0)
				}
			}
		}
	}
	
	message_begin(MSG_BROADCAST, SVC_TEMPENTITY)
	write_byte(17)
	write_coord(vExplodeAt[0])
	write_coord(vExplodeAt[1])
	write_coord(vExplodeAt[2] + 60)
	write_short(xplode)
	write_byte(20)
	write_byte(200)
	message_end()
	
	emit_sound(pToucher, CHAN_WEAPON, "shmod/a_exm2.wav", VOL_NORM, ATTN_NORM, 0, PITCH_NORM)
	
	remove_entity(pToucher)
}

do_victim(victim,attacker,damage,tk)
{	
	sh_extra_damage(victim,attacker,damage,_,_,tk?SH_EXTRA_DMG_FLAG_dmgFFmsg:SH_EXTRA_DMG_FLAG_NONE,_,_,_,custom_dmg_id_grenade)
}


public grentrail(parm[])
{
new gid = parm[0]

if (gid)
{
	message_begin( MSG_BROADCAST, SVC_TEMPENTITY )
	write_byte( TE_BEAMFOLLOW )
	write_short(gid) // entity
	write_short(m_iTrail)  // model
	write_byte( 10 )       // life
	write_byte( 5 )        // width
	write_byte( 255 )      // r, g, b
	write_byte( 255 )    // r, g, b
	write_byte( 255 )      // r, g, b
	write_byte( 100 ) // brightness
	
	message_end() // move PHS/PVS data sending into here (SEND_ALL, SEND_PVS, SEND_PHS)
}
}


public client_connect(id)
{
g_m203_loaded[id] = 1
}

public sh_client_death(id)
{
if ( sh_get_user_has_hero(id,gHeroID))
{
	ammo_hud(id,g_ammo[id],0)
}
}
/* AMXX-Studio Notes - DO NOT MODIFY BELOW HERE
*{\\ rtf1\\ ansi\\ deff0{\\ fonttbl{\\ f0\\ fnil Tahoma;}}\n\\ viewkind4\\ uc1\\ pard\\ lang1030\\ f0\\ fs16 \n\\ par }
*/
